// Code generated by nightseam. DO NOT EDIT.
package supervisorprotocol

import (
	workerprotocol "example.test/generated/api/go/worker-protocol"
	runtime "github.com/Bitspark/nightseam/runtime/go"
)

// schema is the family's wire description, as the runtime validates it; a type of another family is validated by that family's own validator.
var schema = runtime.MustSchema("{\"types\":{\"Envelope\":{\"kind\":\"record\",\"fields\":[{\"name\":\"version\",\"type\":\"integer\",\"required\":true},{\"name\":\"kind\",\"type\":\"string\",\"required\":true},{\"name\":\"id\",\"type\":\"string\",\"required\":false},{\"name\":\"method\",\"type\":\"string\",\"required\":false},{\"name\":\"params\",\"type\":\"json\",\"required\":false},{\"name\":\"result\",\"type\":\"json\",\"required\":false},{\"name\":\"error\",\"type\":\"json\",\"required\":false},{\"name\":\"event\",\"type\":\"string\",\"required\":false},{\"name\":\"data\",\"type\":\"json\",\"required\":false},{\"name\":\"traceparent\",\"type\":\"string\",\"required\":false},{\"name\":\"tracestate\",\"type\":\"string\",\"required\":false},{\"name\":\"meta\",\"type\":{\"map\":\"string\"},\"required\":false}]},\"Handle\":{\"kind\":\"record\",\"fields\":[{\"name\":\"channel\",\"type\":\"integer\",\"required\":true}]},\"Shift\":{\"kind\":\"record\",\"fields\":[{\"name\":\"name\",\"type\":\"string\",\"required\":true}]},\"Watch\":{\"kind\":\"record\",\"fields\":[{\"name\":\"shift\",\"type\":\"Shift\",\"required\":true},{\"name\":\"sink\",\"type\":\"worker.ProgressSink\",\"required\":true},{\"name\":\"spares\",\"type\":{\"array\":\"worker.ProgressSink\"},\"required\":false}]}}}", WireDigest(), map[string]*runtime.Schema{"worker": workerprotocol.WireSchema()})

// WireSchema supplies the family's descriptor and imports for scoped validation.
func WireSchema() *runtime.Schema { return schema }

// WireDigest is the SHA-256 digest of the family's exact wire description.
func WireDigest() string { return "1a6675c586988b8fd34c91a5eef591d806533e49042b0b8eae99f4143ec4a75a" }

// ValidateRaw verifies a named contract value, including null and field presence; at roots the diagnostic where a family that imports this one holds the value.
func ValidateRaw(name string, data []byte, at ...string) error {
	return schema.ValidateRaw(name, data, at...)
}

// ValidateExpressionRaw verifies a type expression and rejects trailing values.
func ValidateExpressionRaw(expression any, data []byte, at ...string) error {
	return schema.ValidateExpressionRaw(expression, data, at...)
}

// ValidateValue validates a typed value before publishing it on the wire.
func ValidateValue(expression any, value any) error { return schema.ValidateValue(expression, value) }

// MustTypeExpression decodes a generated expression and panics on one it cannot read; callers ordinarily use named types.
func MustTypeExpression(encoded string) any { return runtime.MustTypeExpression(encoded) }
