// Code generated by nightseam. DO NOT EDIT.
import { DuplexPeer, DuplexError, wirePair, forwardWire, type AdapterContext, type WireModelContext, type ValueAdapter, type ValueContext } from "@nightseam/runtime";
import { at, mount, pipe as framePipe, type Wire } from '@nightseam/duplex';
import { toWire, prepareFromWire } from './index.ts';
import type * as Protocol from "@example/worker-client/types";
import type { AnyFamily, FamilyBinding } from "@example/worker-client/types";

export type Presentation = (wire: Wire) => { wire: Wire; close(): void } | Promise<{ wire: Wire; close(): void }>;
export interface Options {
 context?: AdapterContext;
 remoteContext?: AdapterContext;
 presentation?: Presentation;
 inputs?: Readonly<Record<string, unknown>>;
 equal?: (method: string, direct: unknown, roundTrip: unknown) => void | Promise<void>;
 callContext?: WireModelContext & { valueContext?: unknown };
}
function once(action: () => void): () => void { let closed=false; return () => { if (!closed) { closed=true; action(); } }; }
function hasMethod(facet:unknown,name:string):boolean{for(let current=facet;current!=null&&current!==Object.prototype;current=Object.getPrototypeOf(current)){if(Object.prototype.hasOwnProperty.call(current,name))return typeof (facet as Record<string,unknown>)[name]==='function';}return false;}
export const local: Presentation = wire => ({wire,close(){}});
export const mounted: Presentation = wire => {const root=mount(new Map([['family',wire]]));return {wire:at(root,['family']),close:once(()=>root.close(1000,''))};};
export const forwarded: Presentation = wire => {
 const [left,right]=wirePair();
 try { const detach=forwardWire(right,wire); return {wire:left,close:once(()=>{detach();left.close(1000,'');})}; }
 catch(error){left.close(1000,'');throw error;}
};
export const pipe: Presentation = async wire => {
 const [left,right]=framePipe(); let detach=()=>{};
 const server=new DuplexPeer({role:'server',prepare(peer){detach=forwardWire(peer.wire(),wire);}});
 const client=new DuplexPeer({role:'client'});
 const close=once(()=>{detach();client.close();server.close();left.close(1000,'');right.close(1000,'');});
 try {await Promise.all([server.attach(right),client.attach(left)]);return {wire:client.wire(),close};}
 catch(error){close();throw error;}
};
type Outcome = {ok:true;value:unknown}|{ok:false;error:unknown};
async function outcome(call:()=>unknown):Promise<Outcome>{try{return {ok:true,value:await call()};}catch(error){return {ok:false,error};}}
function canonical(value:unknown):string {
 if(value===undefined)return 'undefined';
 if(typeof value==='function'||typeof value==='symbol'||typeof value==='bigint')throw new Error('result needs an equal observer');
 if(value===null||typeof value!=='object')return JSON.stringify(value);
 if(Array.isArray(value))return '['+value.map(canonical).join(',')+']';
 return '{'+Object.keys(value).sort().map(key=>JSON.stringify(key)+':'+canonical((value as Record<string,unknown>)[key])).join(',')+'}';
}
async function compare(method:string,expected:Outcome,actual:Outcome,equal:Options['equal']):Promise<void>{
 if(!expected.ok || !actual.ok){
  const code=(error:unknown)=>error instanceof DuplexError?error.code:'internal';
  if(!expected.ok&&!actual.ok&&code(expected.error)===code(actual.error)){
   if(expected.error instanceof DuplexError && actual.error instanceof DuplexError && (expected.error.message!==actual.error.message || canonical(expected.error.data)!==canonical(actual.error.data)))throw new Error(method+': public error changed');
   return;
  }
  throw new Error(method+': direct and round-trip outcomes differ');
 }
 if(equal){await equal(method,expected.value,actual.value);return;}
 if(canonical(expected.value)!==canonical(actual.value))throw new Error(method+': direct and round-trip results differ');
}

export async function pair(model: Protocol.ServerModel, options: Options): Promise<{ model: Protocol.ServerModel; close(): void }> {
  const wire = toWire(model, options.context ?? {});
  let close = once(() => wire.close(1000, ''));
  try {
  const view = await (options.presentation ?? pipe)(wire);
  const rootClose = close; close = once(() => { try { view.close(); } finally { rootClose(); } });
  const prepared = prepareFromWire(view.wire, options.remoteContext ?? {});
  const viewClose = close; close = once(() => { try { prepared.close(); } finally { viewClose(); } });
  return { model: await prepared.complete(options.callContext), close };
  } catch (error) { close(); throw error; }
}
const examples: Readonly<Record<string, { raw?: string; reason?: string }>> = {
"Cancel": { raw: "{\"binding\":\"‹binding›\",\"contract\":\"worker/Cancel\"}", reason: "a live reference illustration needs a caller-supplied native value" },
"Job": { raw: "{\"ticket\":\"‹id›\",\"cancel\":{\"binding\":\"‹binding›\",\"contract\":\"worker/Cancel\"},\"rename\":{\"binding\":\"‹binding›\",\"contract\":\"worker/Rename\"}}", reason: "a live reference illustration needs a caller-supplied native value" },
"Outcome": { raw: "{\"state\":\"finished\"}", reason: "a live reference illustration needs a caller-supplied native value" },
"Percent": { raw: "0", reason: "" },
"ProgressSink": { raw: "{\"report\":{\"binding\":\"‹binding›\",\"contract\":\"worker/Report\"}}", reason: "a live reference illustration needs a caller-supplied native value" },
"Rename": { raw: "{\"binding\":\"‹binding›\",\"contract\":\"worker/Rename\"}", reason: "a live reference illustration needs a caller-supplied native value" },
"Report": { raw: "{\"binding\":\"‹binding›\",\"contract\":\"worker/Report\"}", reason: "a live reference illustration needs a caller-supplied native value" },
"Sinks": { raw: "{\"‹key›\":{\"report\":{\"binding\":\"‹binding›\",\"contract\":\"worker/Report\"}}}", reason: "a live reference illustration needs a caller-supplied native value" },
"Start": { raw: "{\"ticket\":{\"id\":\"‹id›\",\"label\":\"‹label›\"},\"progress\":{\"report\":{\"binding\":\"‹binding›\",\"contract\":\"worker/Report\"}},\"watchers\":[{\"binding\":\"‹binding›\",\"contract\":\"worker/Report\"}]}", reason: "a live reference illustration needs a caller-supplied native value" },
"Supervise": { raw: "{\"sinks\":{\"‹key›\":{\"report\":{\"binding\":\"‹binding›\",\"contract\":\"worker/Report\"}}}}", reason: "a live reference illustration needs a caller-supplied native value" },
"Ticket": { raw: "{\"id\":\"‹id›\",\"label\":\"‹label›\"}", reason: "" },
"Watchers": { raw: "[{\"binding\":\"‹binding›\",\"contract\":\"worker/Report\"}]", reason: "a live reference illustration needs a caller-supplied native value" },
};
/** A fresh documented data witness, validated by the caller's exact value adapter. */
export function example<T>(name: string, adapter: ValueAdapter<T>): T { const value = Object.prototype.hasOwnProperty.call(examples,name) ? examples[name] : undefined; if (!value) throw new Error('unknown example '+name); if (value.reason || adapter.needsContext) throw new Error('example '+name+' unavailable: '+(value.reason || 'an acquiring adapter needs a native witness')); return adapter.import(undefined, JSON.parse(value.raw!)); }
/** Exercise every method on two fresh equivalent models; missing evidence is an error. */
export async function smoke(model: Protocol.ServerModel, opposite: Protocol.Client, options: Options): Promise<void> {
  const bindings = {};
  const inputs = new Map<string,unknown>(); const seen = new Map<string,number>(); let inputError: unknown;
  const observed: Protocol.ServerModel = remote => { const value=model(remote);
  if(!hasMethod(value?.methods,"describe"))throw new Error("model method describe is required");
  if(!hasMethod(value?.methods,"start"))throw new Error("model method start is required");
  return { ...value, methods: {
  async describe(input,context) { const key="describe"; seen.set(key,(seen.get(key)??0)+1); const tracked=inputs.has(key),expected=inputs.get(key);inputs.delete(key); if(tracked)try { await compare("describe.request",{ok:true,value:expected},{ok:true,value:input},options.equal); } catch(error){inputError=error;throw error;} return value.methods.describe(input,context); },
  async start(input,context) { const key="start"; seen.set(key,(seen.get(key)??0)+1); const tracked=inputs.has(key),expected=inputs.get(key);inputs.delete(key); if(tracked)try { await compare("start.request",{ok:true,value:expected},{ok:true,value:input},options.equal); } catch(error){inputError=error;throw error;} return value.methods.start(input,context); },
  } }; };
  const prepared = await pair(observed, options);
  try {
  const remote = prepared.model(opposite); const direct = model(opposite);
  {
  let input: unknown;
  if (options.inputs && Object.prototype.hasOwnProperty.call(options.inputs,"describe")) { input=options.inputs["describe"]; } else {
  if (false) throw new Error("input describe needs a caller-supplied native value");
  input = JSON.parse("{\"id\":\"‹id›\",\"label\":\"‹label›\"}");
  }
  inputs.set("describe",input);
  const before=seen.get("describe")??0;
  const actual = await outcome(() => remote.methods.describe(input as Protocol.Ticket, options.callContext as WireModelContext));
  if(inputError!==undefined)throw inputError;
  if((seen.get("describe")??0)<=before)throw new Error("describe: model was not reached");
  const expected = await outcome(() => direct.methods.describe(input as Protocol.Ticket, options.callContext as WireModelContext));
  await compare("describe", expected, actual, options.equal);
  }
  {
  let input: unknown;
  if (options.inputs && Object.prototype.hasOwnProperty.call(options.inputs,"start")) { input=options.inputs["start"]; } else {
  if (true) throw new Error("input start needs a caller-supplied native value");
  input = JSON.parse("{\"ticket\":{\"id\":\"‹id›\",\"label\":\"‹label›\"},\"progress\":{\"report\":{\"binding\":\"‹binding›\",\"contract\":\"worker/Report\"}},\"watchers\":[{\"binding\":\"‹binding›\",\"contract\":\"worker/Report\"}]}");
  }
  if (!options.equal) throw new Error("start: requires an equal observer for live values");
  inputs.set("start",input);
  const before=seen.get("start")??0;
  const actual = await outcome(() => remote.methods.start(input as Protocol.Start, options.callContext as WireModelContext & { valueContext: unknown }));
  if(inputError!==undefined)throw inputError;
  if((seen.get("start")??0)<=before)throw new Error("start: model was not reached");
  const expected = await outcome(() => direct.methods.start(input as Protocol.Start, options.callContext as WireModelContext & { valueContext: unknown }));
  await compare("start", expected, actual, options.equal);
  }
  } finally { prepared.close(); }
}
