// Code generated by nightseam. DO NOT EDIT.
package probebinding

import (
	context "context"
	json "encoding/json"
	errors "errors"
	protocol "example.com/probe/api/go/probe-protocol"
	fmt "fmt"
	duplex "github.com/Bitspark/nightseam/duplex/go"
	live "github.com/Bitspark/nightseam/live/go"
	runtime "github.com/Bitspark/nightseam/runtime/go"
	atomic "sync/atomic"
)

type serverMethods struct {
	wire        duplex.Wire
	environment runtime.AdapterContext
}
type serverEvents struct {
	wire        duplex.Wire
	environment runtime.AdapterContext
}

func accessServer(wire duplex.Wire, environment runtime.AdapterContext) protocol.Server {
	return protocol.Server{Methods: &serverMethods{wire: wire, environment: environment}, Events: &serverEvents{wire: wire, environment: environment}}
}
func (c *serverMethods) Echo(ctx context.Context, params protocol.Payload) (protocol.Payload, error) {
	var result protocol.Payload
	if err := protocol.WireSchema().ValidateValue(protocol.MustTypeExpression("\"Payload\""), params); err != nil {
		return result, err
	}
	var raw json.RawMessage
	if err := runtime.CallWire(ctx, c.wire, []string{"echo"}, params, &raw, runtime.WireCallOptions{Observer: c.environment.Options.Observer, Family: "probe", Propagator: c.environment.Options.Propagator, RequestTimeout: c.environment.Options.RequestTimeout}); err != nil {
		return result, err
	}
	if err := protocol.WireSchema().ValidateExpressionRaw(protocol.MustTypeExpression("\"Payload\""), raw); err != nil {
		return result, err
	}
	if err := json.Unmarshal(raw, &result); err != nil {
		return result, err
	}
	return result, nil
}
func (c *serverMethods) Watch(ctx context.Context, params protocol.Watch) (protocol.Subscription, error) {
	var result protocol.Subscription
	if true {
		var err error
		ctx, err = c.environment.ValueEnvironment.Select(ctx)
		if err != nil {
			return result, err
		}
	}
	raw, err := func() (json.RawMessage, error) {
		build := func(ctx context.Context) (json.RawMessage, error) {
			sent, err := func() (json.RawMessage, error) {
				var value json.RawMessage
				convert := func(ctx context.Context) (json.RawMessage, error) {
					if ctx == nil {
						return value, fmt.Errorf("a live conversion requires an active owner")
					}
					owner, ok := live.OwnerOf(ctx)
					if !ok || owner == nil {
						return value, fmt.Errorf("a live conversion requires an active owner")
					}
					converted, err := protocol.ExportWatch(owner, params)
					if err != nil {
						return value, err
					}
					if err := protocol.WireSchema().ValidateExpressionRaw(protocol.MustTypeExpression("\"Watch\""), converted); err != nil {
						return value, err
					}
					return converted, nil
				}
				if true {
					return c.environment.ValueEnvironment.Export(ctx, convert)
				}
				return convert(ctx)
			}()
			return sent, err
		}
		publish := func(sent json.RawMessage) (json.RawMessage, error) {
			var raw json.RawMessage
			err := runtime.CallWire(ctx, c.wire, []string{"watch"}, sent, &raw, runtime.WireCallOptions{Observer: c.environment.Options.Observer, Family: "probe", Propagator: c.environment.Options.Propagator, RequestTimeout: c.environment.Options.RequestTimeout})
			return raw, err
		}
		if true {
			return c.environment.ValueEnvironment.Publish(ctx, build, publish)
		}
		sent, err := build(ctx)
		if err != nil {
			return nil, err
		}
		return publish(sent)
	}()
	if err != nil {
		return result, err
	}
	received, err := func() (protocol.Subscription, error) {
		var value protocol.Subscription
		convert := func(ctx context.Context) (protocol.Subscription, error) {
			if ctx == nil {
				return value, fmt.Errorf("a live conversion requires an active owner")
			}
			owner, ok := live.OwnerOf(ctx)
			if !ok || owner == nil {
				return value, fmt.Errorf("a live conversion requires an active owner")
			}
			if err := protocol.WireSchema().ValidateExpressionRaw(protocol.MustTypeExpression("\"Subscription\""), raw); err != nil {
				return value, err
			}
			converted, err := protocol.ImportSubscription(owner, raw)
			if err != nil {
				return value, err
			}
			return converted, nil
		}
		if true {
			err := c.environment.ValueEnvironment.Import(ctx, func(ctx context.Context) error {
				converted, err := convert(ctx)
				if err == nil {
					value = converted
				}
				return err
			})
			if err != nil {
				var zero protocol.Subscription
				return zero, err
			}
			return value, nil
		}
		return convert(ctx)
	}()
	return received, err
}
func bindServer(wire duplex.Wire, lookup func() protocol.Server, environment runtime.AdapterContext) error {
	var detach []func()
	complete := false
	defer func() {
		if !complete {
			for _, off := range detach {
				off()
			}
		}
	}()
	{
		handlers := runtime.WireHandlers{Observer: environment.Options.Observer, Family: "probe"}
		handlers.Request = func(ctx context.Context, raw json.RawMessage) (any, error) {
			implementation := lookup()
			if implementation.Methods == nil {
				return nil, fmt.Errorf("model methods are required")
			}
			if err := protocol.WireSchema().ValidateExpressionRaw(protocol.MustTypeExpression("\"Payload\""), raw); err != nil {
				var public *runtime.PublicError
				if errors.As(err, &public) && public.Code == "contract_mismatch" {
					return nil, err
				}
				return nil, &runtime.PublicError{Code: "invalid_params", Message: err.Error()}
			}
			var params protocol.Payload
			if err := json.Unmarshal(raw, &params); err != nil {
				var public *runtime.PublicError
				if errors.As(err, &public) && public.Code == "contract_mismatch" {
					return nil, err
				}
				return nil, &runtime.PublicError{Code: "invalid_params", Message: err.Error()}
			}
			result, err := implementation.Methods.Echo(ctx, params)
			if err != nil {
				return nil, err
			}
			if err = protocol.WireSchema().ValidateValue(protocol.MustTypeExpression("\"Payload\""), result); err != nil {
				return nil, err
			}
			return result, nil
		}
		if handlers.Request != nil || handlers.Event != nil {
			off, err := runtime.RegisterWire(wire, []string{"echo"}, handlers)
			if err != nil {
				return err
			}
			detach = append(detach, off)
		}
	}
	{
		handlers := runtime.WireHandlers{Observer: environment.Options.Observer, Family: "probe"}
		handlers.Request = func(ctx context.Context, raw json.RawMessage) (any, error) {
			implementation := lookup()
			if implementation.Methods == nil {
				return nil, fmt.Errorf("model methods are required")
			}
			if true {
				var err error
				ctx, err = environment.ValueEnvironment.Child(ctx)
				if err != nil {
					return nil, err
				}
			}
			params, err := func() (protocol.Watch, error) {
				var value protocol.Watch
				convert := func(ctx context.Context) (protocol.Watch, error) {
					if ctx == nil {
						return value, fmt.Errorf("a live conversion requires an active owner")
					}
					owner, ok := live.OwnerOf(ctx)
					if !ok || owner == nil {
						return value, fmt.Errorf("a live conversion requires an active owner")
					}
					if err := protocol.WireSchema().ValidateExpressionRaw(protocol.MustTypeExpression("\"Watch\""), raw); err != nil {
						return value, err
					}
					converted, err := protocol.ImportWatch(owner, raw)
					if err != nil {
						return value, err
					}
					return converted, nil
				}
				if true {
					err := environment.ValueEnvironment.Import(ctx, func(ctx context.Context) error {
						converted, err := convert(ctx)
						if err == nil {
							value = converted
						}
						return err
					})
					if err != nil {
						var zero protocol.Watch
						return zero, err
					}
					return value, nil
				}
				return convert(ctx)
			}()
			if err != nil {
				var public *runtime.PublicError
				if errors.As(err, &public) && public.Code == "contract_mismatch" {
					return nil, err
				}
				return nil, &runtime.PublicError{Code: "invalid_params", Message: err.Error()}
			}
			result, err := implementation.Methods.Watch(ctx, params)
			if err != nil {
				return nil, err
			}
			sent, err := func() (json.RawMessage, error) {
				var value json.RawMessage
				convert := func(ctx context.Context) (json.RawMessage, error) {
					if ctx == nil {
						return value, fmt.Errorf("a live conversion requires an active owner")
					}
					owner, ok := live.OwnerOf(ctx)
					if !ok || owner == nil {
						return value, fmt.Errorf("a live conversion requires an active owner")
					}
					converted, err := protocol.ExportSubscription(owner, result)
					if err != nil {
						return value, err
					}
					if err := protocol.WireSchema().ValidateExpressionRaw(protocol.MustTypeExpression("\"Subscription\""), converted); err != nil {
						return value, err
					}
					return converted, nil
				}
				if true {
					return environment.ValueEnvironment.Export(ctx, convert)
				}
				return convert(ctx)
			}()
			return sent, err
		}
		if handlers.Request != nil || handlers.Event != nil {
			off, err := runtime.RegisterWire(wire, []string{"watch"}, handlers)
			if err != nil {
				return err
			}
			detach = append(detach, off)
		}
	}
	complete = true
	return nil
}

type clientMethods struct {
	wire        duplex.Wire
	environment runtime.AdapterContext
}
type clientEvents struct {
	wire        duplex.Wire
	environment runtime.AdapterContext
}

func accessClient(wire duplex.Wire, environment runtime.AdapterContext) protocol.Client {
	return protocol.Client{Methods: &clientMethods{wire: wire, environment: environment}, Events: &clientEvents{wire: wire, environment: environment}}
}
func (c *clientMethods) Reverse(ctx context.Context, params protocol.Payload) (protocol.Payload, error) {
	var result protocol.Payload
	if err := protocol.WireSchema().ValidateValue(protocol.MustTypeExpression("\"Payload\""), params); err != nil {
		return result, err
	}
	var raw json.RawMessage
	if err := runtime.CallWire(ctx, c.wire, []string{"reverse"}, params, &raw, runtime.WireCallOptions{Observer: c.environment.Options.Observer, Family: "probe", Propagator: c.environment.Options.Propagator, RequestTimeout: c.environment.Options.RequestTimeout}); err != nil {
		return result, err
	}
	if err := protocol.WireSchema().ValidateExpressionRaw(protocol.MustTypeExpression("\"Payload\""), raw); err != nil {
		return result, err
	}
	if err := json.Unmarshal(raw, &result); err != nil {
		return result, err
	}
	return result, nil
}
func (c *clientEvents) Changed(ctx context.Context, data protocol.Payload) error {
	if err := protocol.WireSchema().ValidateValue(protocol.MustTypeExpression("\"Payload\""), data); err != nil {
		return err
	}
	return runtime.EmitWire(ctx, c.wire, []string{"changed"}, data, runtime.WireEmitOptions{Observer: c.environment.Options.Observer, Family: "probe", Propagator: c.environment.Options.Propagator})
}
func bindClient(wire duplex.Wire, lookup func() protocol.Client, environment runtime.AdapterContext) error {
	var detach []func()
	complete := false
	defer func() {
		if !complete {
			for _, off := range detach {
				off()
			}
		}
	}()
	{
		handlers := runtime.WireHandlers{Observer: environment.Options.Observer, Family: "probe"}
		handlers.Event = func(ctx context.Context, raw json.RawMessage) error {
			implementation := lookup()
			if implementation.Events == nil {
				return nil
			}
			if err := protocol.WireSchema().ValidateExpressionRaw(protocol.MustTypeExpression("\"Payload\""), raw); err != nil {
				return err
			}
			var data protocol.Payload
			if err := json.Unmarshal(raw, &data); err != nil {
				return err
			}
			return implementation.Events.Changed(ctx, data)
		}
		if handlers.Request != nil || handlers.Event != nil {
			off, err := runtime.RegisterWire(wire, []string{"changed"}, handlers)
			if err != nil {
				return err
			}
			detach = append(detach, off)
		}
	}
	{
		handlers := runtime.WireHandlers{Observer: environment.Options.Observer, Family: "probe"}
		handlers.Request = func(ctx context.Context, raw json.RawMessage) (any, error) {
			implementation := lookup()
			if implementation.Methods == nil {
				return nil, fmt.Errorf("model methods are required")
			}
			if err := protocol.WireSchema().ValidateExpressionRaw(protocol.MustTypeExpression("\"Payload\""), raw); err != nil {
				var public *runtime.PublicError
				if errors.As(err, &public) && public.Code == "contract_mismatch" {
					return nil, err
				}
				return nil, &runtime.PublicError{Code: "invalid_params", Message: err.Error()}
			}
			var params protocol.Payload
			if err := json.Unmarshal(raw, &params); err != nil {
				var public *runtime.PublicError
				if errors.As(err, &public) && public.Code == "contract_mismatch" {
					return nil, err
				}
				return nil, &runtime.PublicError{Code: "invalid_params", Message: err.Error()}
			}
			result, err := implementation.Methods.Reverse(ctx, params)
			if err != nil {
				return nil, err
			}
			if err = protocol.WireSchema().ValidateValue(protocol.MustTypeExpression("\"Payload\""), result); err != nil {
				return nil, err
			}
			return result, nil
		}
		if handlers.Request != nil || handlers.Event != nil {
			off, err := runtime.RegisterWire(wire, []string{"reverse"}, handlers)
			if err != nil {
				return err
			}
			detach = append(detach, off)
		}
	}
	complete = true
	return nil
}
func normalizeContext(environment runtime.AdapterContext) (runtime.AdapterContext, error) {
	if (true) && environment.ValueEnvironment == nil {
		return environment, fmt.Errorf("a context-dependent adapter requires a value environment")
	}
	return environment, nil
}

// ToWire binds one model factory and returns its access wire.
func ToWire(model protocol.ServerModel, environment runtime.AdapterContext) (duplex.Wire, error) {
	if model == nil {
		return nil, fmt.Errorf("model factory is required")
	}
	environment, err := normalizeContext(environment)
	if err != nil {
		return nil, err
	}
	identity, err := declarationIdentity()
	if err != nil {
		return nil, err
	}
	options := environment.Options
	families := map[string]string{}
	for name, existing := range options.Families {
		families[name] = existing
	}
	families["4:echo"] = "probe"
	families["5:watch"] = "probe"
	families["7:changed"] = "probe"
	families["7:reverse"] = "probe"
	options.Families = families
	access, binding, err := runtime.NewWirePair(options)
	if err != nil {
		return nil, err
	}
	complete := false
	defer func() {
		if !complete {
			_ = access.Close(duplex.CodeInternalError, "model construction failed")
		}
	}()
	if _, err := registerIdentity(binding, identity); err != nil {
		return nil, err
	}
	implementation, err := model(accessClient(binding, environment))
	if err != nil {
		return nil, err
	}
	if implementation.Methods == nil {
		return nil, fmt.Errorf("Server methods are required")
	}
	if err := bindServer(binding, func() protocol.Server { return implementation }, environment); err != nil {
		return nil, err
	}
	complete = true
	return access, nil
}
func declarationIdentity() (runtime.DeclarationIdentity, error) {
	digest, err := protocol.WireSchema().DeclarationDigest()
	if err != nil {
		return runtime.DeclarationIdentity{}, err
	}
	return runtime.DeclarationIdentity{Path: "probe", Digest: digest}, nil
}
func registerIdentity(wire duplex.Wire, identity runtime.DeclarationIdentity) (func(), error) {
	handler, err := runtime.IdentityHandler(identity)
	if err != nil {
		return nil, err
	}
	return runtime.HandleWire(wire, []string{runtime.IdentityMethod}, func(ctx context.Context, raw json.RawMessage) (any, error) { return handler(ctx, nil, raw) })
}

// PrepareFromWire registers receivers synchronously, before the wire is attached.
// Complete checks identity and returns a factory that may be bound once. Both steps
// must finish within environment.Options.RequestTimeout. Cleanup detaches this
// interpretation's registrations, including after success, and never closes the wire.
func PrepareFromWire(wire duplex.Wire, environment runtime.AdapterContext) (complete func(context.Context) (protocol.ServerModel, error), cleanup func(), err error) {
	if wire == nil {
		return nil, nil, fmt.Errorf("wire is required")
	}
	environment, err = normalizeContext(environment)
	if err != nil {
		return nil, nil, err
	}
	identity, err := declarationIdentity()
	if err != nil {
		return nil, nil, err
	}
	preparation, err := runtime.PrepareIdentity(wire, identity, environment.Options)
	if err != nil {
		return nil, nil, err
	}
	cleanup = preparation.Close
	var implementation atomic.Pointer[protocol.Client]
	lookup := func() protocol.Client {
		if current := implementation.Load(); current != nil {
			return *current
		}
		return protocol.Client{}
	}
	if err = bindClient(preparation.Wire(), lookup, environment); err != nil {
		cleanup()
		return nil, nil, err
	}
	var checking, bound atomic.Bool
	complete = func(ctx context.Context) (protocol.ServerModel, error) {
		if !checking.CompareAndSwap(false, true) {
			return nil, fmt.Errorf("identity completion is already started")
		}
		if err := preparation.Check(ctx); err != nil {
			cleanup()
			return nil, err
		}
		return func(value protocol.Client) (protocol.Server, error) {
			if !bound.CompareAndSwap(false, true) {
				return protocol.Server{}, fmt.Errorf("model factory is already bound")
			}
			if value.Methods == nil {
				cleanup()
				return protocol.Server{}, fmt.Errorf("Client methods are required")
			}
			implementation.Store(&value)
			if err := preparation.Ready(); err != nil {
				cleanup()
				return protocol.Server{}, err
			}
			return accessServer(preparation.Wire(), environment), nil
		}, nil
	}
	return complete, cleanup, nil
}

// FromWire checks identity and returns a factory that may be bound once.
// Use PrepareFromWire before attachment when incoming delivery can begin immediately.
func FromWire(ctx context.Context, wire duplex.Wire, environment runtime.AdapterContext) (protocol.ServerModel, error) {
	complete, cleanup, err := PrepareFromWire(wire, environment)
	if err != nil {
		return nil, err
	}
	model, err := complete(ctx)
	if err != nil {
		cleanup()
		return nil, err
	}
	return model, nil
}
