// Code generated by nightseam. DO NOT EDIT.
package proofclient

import (
	context "context"
	json "encoding/json"
	errors "errors"
	probeprotocol "example.test/generated/api/go/probe-protocol"
	protocol "example.test/generated/api/go/proof-protocol"
	fmt "fmt"
	bitwire "github.com/Bitspark/bitwire/wire/go"
	duplex "github.com/Bitspark/nightseam/duplex/go"
	runtime "github.com/Bitspark/nightseam/runtime/go"
	atomic "sync/atomic"
)

type serverMethods[SEnvelope, SHandle, Item any] struct {
	wire             bitwire.Wire
	environment      runtime.AdapterContext
	adapterSEnvelope runtime.ValueAdapter[SEnvelope]
	adapterSHandle   runtime.ValueAdapter[SHandle]
	adapterItem      runtime.ValueAdapter[Item]
}
type serverEvents[SEnvelope, SHandle, Item any] struct {
	wire             bitwire.Wire
	environment      runtime.AdapterContext
	adapterSEnvelope runtime.ValueAdapter[SEnvelope]
	adapterSHandle   runtime.ValueAdapter[SHandle]
	adapterItem      runtime.ValueAdapter[Item]
}

func accessServer[SEnvelope, SHandle, Item any](wire bitwire.Wire, environment runtime.AdapterContext, adapterSEnvelope runtime.ValueAdapter[SEnvelope], adapterSHandle runtime.ValueAdapter[SHandle], adapterItem runtime.ValueAdapter[Item]) protocol.Server[SEnvelope, SHandle, Item] {
	return protocol.Server[SEnvelope, SHandle, Item]{Methods: &serverMethods[SEnvelope, SHandle, Item]{wire: wire, environment: environment, adapterSEnvelope: adapterSEnvelope, adapterSHandle: adapterSHandle, adapterItem: adapterItem}, Events: &serverEvents[SEnvelope, SHandle, Item]{wire: wire, environment: environment, adapterSEnvelope: adapterSEnvelope, adapterSHandle: adapterSHandle, adapterItem: adapterItem}}
}
func (c *serverMethods[SEnvelope, SHandle, Item]) Echo(ctx context.Context, params probeprotocol.Payload) (probeprotocol.Payload, error) {
	var result probeprotocol.Payload
	if err := protocol.WireSchema().Bind(map[string]any{"S.Envelope": c.adapterSEnvelope.Binding, "S.Handle": c.adapterSHandle.Binding, "Item": c.adapterItem.Binding}, nil).ValidateValue(protocol.MustTypeExpression("\"probe.Payload\""), params); err != nil {
		return result, err
	}
	var raw json.RawMessage
	if err := runtime.CallWire(ctx, c.wire, []string{"echo"}, params, &raw, runtime.WireCallOptions{Observer: c.environment.Options.Observer, Family: "proof", Propagator: c.environment.Options.Propagator, RequestTimeout: c.environment.Options.RequestTimeout}); err != nil {
		return result, err
	}
	if err := protocol.WireSchema().Bind(map[string]any{"S.Envelope": c.adapterSEnvelope.Binding, "S.Handle": c.adapterSHandle.Binding, "Item": c.adapterItem.Binding}, nil).ValidateExpressionRaw(protocol.MustTypeExpression("\"probe.Payload\""), raw); err != nil {
		return result, err
	}
	if err := json.Unmarshal(raw, &result); err != nil {
		return result, err
	}
	return result, nil
}
func (c *serverMethods[SEnvelope, SHandle, Item]) NoArgs(ctx context.Context) (string, error) {
	var result string
	var raw json.RawMessage
	if err := runtime.CallWire(ctx, c.wire, []string{"no_args"}, struct{}{}, &raw, runtime.WireCallOptions{Observer: c.environment.Options.Observer, Family: "proof", Propagator: c.environment.Options.Propagator, RequestTimeout: c.environment.Options.RequestTimeout}); err != nil {
		return result, err
	}
	if err := protocol.WireSchema().Bind(map[string]any{"S.Envelope": c.adapterSEnvelope.Binding, "S.Handle": c.adapterSHandle.Binding, "Item": c.adapterItem.Binding}, nil).ValidateExpressionRaw(protocol.MustTypeExpression("\"string\""), raw); err != nil {
		return result, err
	}
	if err := json.Unmarshal(raw, &result); err != nil {
		return result, err
	}
	return result, nil
}
func (c *serverMethods[SEnvelope, SHandle, Item]) Classify(ctx context.Context, params protocol.Part) (string, error) {
	var result string
	if err := protocol.WireSchema().Bind(map[string]any{"S.Envelope": c.adapterSEnvelope.Binding, "S.Handle": c.adapterSHandle.Binding, "Item": c.adapterItem.Binding}, nil).ValidateValue(protocol.MustTypeExpression("\"Part\""), params); err != nil {
		return result, err
	}
	var raw json.RawMessage
	if err := runtime.CallWire(ctx, c.wire, []string{"classify"}, params, &raw, runtime.WireCallOptions{Observer: c.environment.Options.Observer, Family: "proof", Propagator: c.environment.Options.Propagator, RequestTimeout: c.environment.Options.RequestTimeout}); err != nil {
		return result, err
	}
	if err := protocol.WireSchema().Bind(map[string]any{"S.Envelope": c.adapterSEnvelope.Binding, "S.Handle": c.adapterSHandle.Binding, "Item": c.adapterItem.Binding}, nil).ValidateExpressionRaw(protocol.MustTypeExpression("\"string\""), raw); err != nil {
		return result, err
	}
	if err := json.Unmarshal(raw, &result); err != nil {
		return result, err
	}
	return result, nil
}
func (c *serverMethods[SEnvelope, SHandle, Item]) ClassifyRich(ctx context.Context, params protocol.RichPart) (string, error) {
	var result string
	if err := protocol.WireSchema().Bind(map[string]any{"S.Envelope": c.adapterSEnvelope.Binding, "S.Handle": c.adapterSHandle.Binding, "Item": c.adapterItem.Binding}, nil).ValidateValue(protocol.MustTypeExpression("\"RichPart\""), params); err != nil {
		return result, err
	}
	var raw json.RawMessage
	if err := runtime.CallWire(ctx, c.wire, []string{"classify_rich"}, params, &raw, runtime.WireCallOptions{Observer: c.environment.Options.Observer, Family: "proof", Propagator: c.environment.Options.Propagator, RequestTimeout: c.environment.Options.RequestTimeout}); err != nil {
		return result, err
	}
	if err := protocol.WireSchema().Bind(map[string]any{"S.Envelope": c.adapterSEnvelope.Binding, "S.Handle": c.adapterSHandle.Binding, "Item": c.adapterItem.Binding}, nil).ValidateExpressionRaw(protocol.MustTypeExpression("\"string\""), raw); err != nil {
		return result, err
	}
	if err := json.Unmarshal(raw, &result); err != nil {
		return result, err
	}
	return result, nil
}
func (c *serverMethods[SEnvelope, SHandle, Item]) Parts(ctx context.Context, params protocol.PartsRequest) (protocol.Result[protocol.Parts, string], error) {
	var result protocol.Result[protocol.Parts, string]
	if false {
		var err error
		ctx, err = c.environment.ValueEnvironment.Select(ctx)
		if err != nil {
			return result, err
		}
	}
	if err := protocol.WireSchema().Bind(map[string]any{"S.Envelope": c.adapterSEnvelope.Binding, "S.Handle": c.adapterSHandle.Binding, "Item": c.adapterItem.Binding}, nil).ValidateValue(protocol.MustTypeExpression("{\"kind\":\"record\",\"fields\":[{\"name\":\"after\",\"type\":{\"nullable\":\"string\"},\"required\":false}]}"), params); err != nil {
		return result, err
	}
	var raw json.RawMessage
	if err := runtime.CallWire(ctx, c.wire, []string{"parts"}, params, &raw, runtime.WireCallOptions{Observer: c.environment.Options.Observer, Family: "proof", Propagator: c.environment.Options.Propagator, RequestTimeout: c.environment.Options.RequestTimeout}); err != nil {
		return result, err
	}
	received, err := func() (protocol.Result[protocol.Parts, string], error) {
		var value protocol.Result[protocol.Parts, string]
		convert := func(ctx context.Context) (protocol.Result[protocol.Parts, string], error) {
			if err := protocol.WireSchema().Bind(map[string]any{"S.Envelope": c.adapterSEnvelope.Binding, "S.Handle": c.adapterSHandle.Binding, "Item": c.adapterItem.Binding}, nil).ValidateExpressionRaw(protocol.MustTypeExpression("{\"apply\":\"Result\",\"with\":{\"E\":\"string\",\"T\":\"Parts\"}}"), raw); err != nil {
				return value, err
			}
			convertedConvert0 := func(input json.RawMessage) (protocol.Parts, error) {
				var zero protocol.Parts
				var converted protocol.Parts
				if err := json.Unmarshal(input, &converted); err != nil {
					return zero, err
				}
				return converted, nil
			}
			convertedConvert1 := func(input json.RawMessage) (string, error) {
				var zero string
				var converted string
				if err := json.Unmarshal(input, &converted); err != nil {
					return zero, err
				}
				return converted, nil
			}
			converted, err := protocol.ImportResult[protocol.Parts, string](raw, convertedConvert0, runtime.TypeBinding{Schema: protocol.WireSchema().Bind(map[string]any{"S.Envelope": c.adapterSEnvelope.Binding, "S.Handle": c.adapterSHandle.Binding, "Item": c.adapterItem.Binding}, nil), Type: runtime.MustTypeExpression("\"Parts\"")}, convertedConvert1, runtime.TypeBinding{Schema: protocol.WireSchema().Bind(map[string]any{"S.Envelope": c.adapterSEnvelope.Binding, "S.Handle": c.adapterSHandle.Binding, "Item": c.adapterItem.Binding}, nil), Type: runtime.MustTypeExpression("\"string\"")})
			if err != nil {
				return value, err
			}
			return converted, nil
		}
		if false {
			err := c.environment.ValueEnvironment.Import(ctx, func(ctx context.Context) error {
				converted, err := convert(ctx)
				if err == nil {
					value = converted
				}
				return err
			})
			if err != nil {
				var zero protocol.Result[protocol.Parts, string]
				return zero, err
			}
			return value, nil
		}
		return convert(ctx)
	}()
	return received, err
}
func (c *serverMethods[SEnvelope, SHandle, Item]) Relay(ctx context.Context, params protocol.Carried[SEnvelope, SHandle, Item]) (protocol.Option[protocol.Envelope], error) {
	var result protocol.Option[protocol.Envelope]
	if c.adapterSEnvelope.NeedsContext || c.adapterSHandle.NeedsContext || c.adapterItem.NeedsContext {
		var err error
		ctx, err = c.environment.ValueEnvironment.Select(ctx)
		if err != nil {
			return result, err
		}
	}
	raw, err := func() (json.RawMessage, error) {
		build := func(ctx context.Context) (json.RawMessage, error) {
			sent, err := func() (json.RawMessage, error) {
				var value json.RawMessage
				convert := func(ctx context.Context) (json.RawMessage, error) {
					convertedConvert0 := func(input SEnvelope) (json.RawMessage, error) {
						converted, err := c.adapterSEnvelope.Export(ctx, input)
						if err != nil {
							return nil, err
						}
						return converted, nil
					}
					convertedConvert1 := func(input SHandle) (json.RawMessage, error) {
						converted, err := c.adapterSHandle.Export(ctx, input)
						if err != nil {
							return nil, err
						}
						return converted, nil
					}
					convertedConvert2 := func(input Item) (json.RawMessage, error) {
						converted, err := c.adapterItem.Export(ctx, input)
						if err != nil {
							return nil, err
						}
						return converted, nil
					}
					converted, err := protocol.ExportCarried[SEnvelope, SHandle, Item](params, convertedConvert0, runtime.TypeBinding{Schema: protocol.WireSchema().Bind(map[string]any{"S.Envelope": c.adapterSEnvelope.Binding, "S.Handle": c.adapterSHandle.Binding, "Item": c.adapterItem.Binding}, nil), Type: runtime.MustTypeExpression("\"S.Envelope\"")}, convertedConvert1, runtime.TypeBinding{Schema: protocol.WireSchema().Bind(map[string]any{"S.Envelope": c.adapterSEnvelope.Binding, "S.Handle": c.adapterSHandle.Binding, "Item": c.adapterItem.Binding}, nil), Type: runtime.MustTypeExpression("\"S.Handle\"")}, convertedConvert2, runtime.TypeBinding{Schema: protocol.WireSchema().Bind(map[string]any{"S.Envelope": c.adapterSEnvelope.Binding, "S.Handle": c.adapterSHandle.Binding, "Item": c.adapterItem.Binding}, nil), Type: runtime.MustTypeExpression("\"Item\"")})
					if err != nil {
						return value, err
					}
					if err := protocol.WireSchema().Bind(map[string]any{"S.Envelope": c.adapterSEnvelope.Binding, "S.Handle": c.adapterSHandle.Binding, "Item": c.adapterItem.Binding}, nil).ValidateExpressionRaw(protocol.MustTypeExpression("\"Carried\""), converted); err != nil {
						return value, err
					}
					return converted, nil
				}
				if c.adapterSEnvelope.NeedsContext || c.adapterSHandle.NeedsContext || c.adapterItem.NeedsContext {
					return c.environment.ValueEnvironment.Export(ctx, convert)
				}
				return convert(ctx)
			}()
			return sent, err
		}
		publish := func(sent json.RawMessage) (json.RawMessage, error) {
			var raw json.RawMessage
			err := runtime.CallWire(ctx, c.wire, []string{"relay"}, sent, &raw, runtime.WireCallOptions{Observer: c.environment.Options.Observer, Family: "proof", Propagator: c.environment.Options.Propagator, RequestTimeout: c.environment.Options.RequestTimeout})
			return raw, err
		}
		if c.adapterSEnvelope.NeedsContext || c.adapterSHandle.NeedsContext || c.adapterItem.NeedsContext {
			return c.environment.ValueEnvironment.Publish(ctx, build, publish)
		}
		sent, err := build(ctx)
		if err != nil {
			return nil, err
		}
		return publish(sent)
	}()
	if err != nil {
		return result, err
	}
	received, err := func() (protocol.Option[protocol.Envelope], error) {
		var value protocol.Option[protocol.Envelope]
		convert := func(ctx context.Context) (protocol.Option[protocol.Envelope], error) {
			if err := protocol.WireSchema().Bind(map[string]any{"S.Envelope": c.adapterSEnvelope.Binding, "S.Handle": c.adapterSHandle.Binding, "Item": c.adapterItem.Binding}, nil).ValidateExpressionRaw(protocol.MustTypeExpression("{\"apply\":\"Option\",\"with\":{\"T\":\"Envelope\"}}"), raw); err != nil {
				return value, err
			}
			convertedConvert0 := func(input json.RawMessage) (protocol.Envelope, error) {
				var zero protocol.Envelope
				var converted protocol.Envelope
				if err := json.Unmarshal(input, &converted); err != nil {
					return zero, err
				}
				return converted, nil
			}
			converted, err := protocol.ImportOption[protocol.Envelope](raw, convertedConvert0, runtime.TypeBinding{Schema: protocol.WireSchema().Bind(map[string]any{"S.Envelope": c.adapterSEnvelope.Binding, "S.Handle": c.adapterSHandle.Binding, "Item": c.adapterItem.Binding}, nil), Type: runtime.MustTypeExpression("\"Envelope\"")})
			if err != nil {
				return value, err
			}
			return converted, nil
		}
		if false {
			err := c.environment.ValueEnvironment.Import(ctx, func(ctx context.Context) error {
				converted, err := convert(ctx)
				if err == nil {
					value = converted
				}
				return err
			})
			if err != nil {
				var zero protocol.Option[protocol.Envelope]
				return zero, err
			}
			return value, nil
		}
		return convert(ctx)
	}()
	return received, err
}
func bindServer[SEnvelope, SHandle, Item any](wire runtime.HandlerRegistry, lookup func() protocol.Server[SEnvelope, SHandle, Item], environment runtime.AdapterContext, adapterSEnvelope runtime.ValueAdapter[SEnvelope], adapterSHandle runtime.ValueAdapter[SHandle], adapterItem runtime.ValueAdapter[Item]) error {
	var detach []func()
	complete := false
	defer func() {
		if !complete {
			for _, off := range detach {
				off()
			}
		}
	}()
	{
		handlers := runtime.WireHandlers{Observer: environment.Options.Observer, Family: "proof"}
		handlers.Request = func(ctx context.Context, raw json.RawMessage) (any, error) {
			implementation := lookup()
			if implementation.Methods == nil {
				return nil, fmt.Errorf("model methods are required")
			}
			if err := protocol.WireSchema().Bind(map[string]any{"S.Envelope": adapterSEnvelope.Binding, "S.Handle": adapterSHandle.Binding, "Item": adapterItem.Binding}, nil).ValidateExpressionRaw(protocol.MustTypeExpression("\"Part\""), raw); err != nil {
				var public *runtime.PublicError
				if errors.As(err, &public) && public.Code == "contract_mismatch" {
					return nil, err
				}
				return nil, &runtime.PublicError{Code: "invalid_params", Message: err.Error()}
			}
			var params protocol.Part
			if err := json.Unmarshal(raw, &params); err != nil {
				var public *runtime.PublicError
				if errors.As(err, &public) && public.Code == "contract_mismatch" {
					return nil, err
				}
				return nil, &runtime.PublicError{Code: "invalid_params", Message: err.Error()}
			}
			result, err := implementation.Methods.Classify(ctx, params)
			if err != nil {
				return nil, err
			}
			if err = protocol.WireSchema().Bind(map[string]any{"S.Envelope": adapterSEnvelope.Binding, "S.Handle": adapterSHandle.Binding, "Item": adapterItem.Binding}, nil).ValidateValue(protocol.MustTypeExpression("\"string\""), result); err != nil {
				return nil, err
			}
			return result, nil
		}
		if handlers.Request != nil || handlers.Event != nil {
			off, err := runtime.RegisterWire(wire, []string{"classify"}, handlers)
			if err != nil {
				return err
			}
			detach = append(detach, off)
		}
	}
	{
		handlers := runtime.WireHandlers{Observer: environment.Options.Observer, Family: "proof"}
		handlers.Request = func(ctx context.Context, raw json.RawMessage) (any, error) {
			implementation := lookup()
			if implementation.Methods == nil {
				return nil, fmt.Errorf("model methods are required")
			}
			if err := protocol.WireSchema().Bind(map[string]any{"S.Envelope": adapterSEnvelope.Binding, "S.Handle": adapterSHandle.Binding, "Item": adapterItem.Binding}, nil).ValidateExpressionRaw(protocol.MustTypeExpression("\"RichPart\""), raw); err != nil {
				var public *runtime.PublicError
				if errors.As(err, &public) && public.Code == "contract_mismatch" {
					return nil, err
				}
				return nil, &runtime.PublicError{Code: "invalid_params", Message: err.Error()}
			}
			var params protocol.RichPart
			if err := json.Unmarshal(raw, &params); err != nil {
				var public *runtime.PublicError
				if errors.As(err, &public) && public.Code == "contract_mismatch" {
					return nil, err
				}
				return nil, &runtime.PublicError{Code: "invalid_params", Message: err.Error()}
			}
			result, err := implementation.Methods.ClassifyRich(ctx, params)
			if err != nil {
				return nil, err
			}
			if err = protocol.WireSchema().Bind(map[string]any{"S.Envelope": adapterSEnvelope.Binding, "S.Handle": adapterSHandle.Binding, "Item": adapterItem.Binding}, nil).ValidateValue(protocol.MustTypeExpression("\"string\""), result); err != nil {
				return nil, err
			}
			return result, nil
		}
		if handlers.Request != nil || handlers.Event != nil {
			off, err := runtime.RegisterWire(wire, []string{"classify_rich"}, handlers)
			if err != nil {
				return err
			}
			detach = append(detach, off)
		}
	}
	{
		handlers := runtime.WireHandlers{Observer: environment.Options.Observer, Family: "proof"}
		handlers.Request = func(ctx context.Context, raw json.RawMessage) (any, error) {
			implementation := lookup()
			if implementation.Methods == nil {
				return nil, fmt.Errorf("model methods are required")
			}
			if err := protocol.WireSchema().Bind(map[string]any{"S.Envelope": adapterSEnvelope.Binding, "S.Handle": adapterSHandle.Binding, "Item": adapterItem.Binding}, nil).ValidateExpressionRaw(protocol.MustTypeExpression("\"probe.Payload\""), raw); err != nil {
				var public *runtime.PublicError
				if errors.As(err, &public) && public.Code == "contract_mismatch" {
					return nil, err
				}
				return nil, &runtime.PublicError{Code: "invalid_params", Message: err.Error()}
			}
			var params probeprotocol.Payload
			if err := json.Unmarshal(raw, &params); err != nil {
				var public *runtime.PublicError
				if errors.As(err, &public) && public.Code == "contract_mismatch" {
					return nil, err
				}
				return nil, &runtime.PublicError{Code: "invalid_params", Message: err.Error()}
			}
			result, err := implementation.Methods.Echo(ctx, params)
			if err != nil {
				return nil, err
			}
			if err = protocol.WireSchema().Bind(map[string]any{"S.Envelope": adapterSEnvelope.Binding, "S.Handle": adapterSHandle.Binding, "Item": adapterItem.Binding}, nil).ValidateValue(protocol.MustTypeExpression("\"probe.Payload\""), result); err != nil {
				return nil, err
			}
			return result, nil
		}
		if handlers.Request != nil || handlers.Event != nil {
			off, err := runtime.RegisterWire(wire, []string{"echo"}, handlers)
			if err != nil {
				return err
			}
			detach = append(detach, off)
		}
	}
	{
		handlers := runtime.WireHandlers{Observer: environment.Options.Observer, Family: "proof"}
		handlers.Request = func(ctx context.Context, raw json.RawMessage) (any, error) {
			implementation := lookup()
			if implementation.Methods == nil {
				return nil, fmt.Errorf("model methods are required")
			}
			if err := protocol.WireSchema().Bind(map[string]any{"S.Envelope": adapterSEnvelope.Binding, "S.Handle": adapterSHandle.Binding, "Item": adapterItem.Binding}, nil).ValidateExpressionRaw(map[string]any{"empty": true}, raw); err != nil {
				var public *runtime.PublicError
				if errors.As(err, &public) && public.Code == "contract_mismatch" {
					return nil, err
				}
				return nil, &runtime.PublicError{Code: "invalid_params", Message: err.Error()}
			}
			result, err := implementation.Methods.NoArgs(ctx)
			if err != nil {
				return nil, err
			}
			if err = protocol.WireSchema().Bind(map[string]any{"S.Envelope": adapterSEnvelope.Binding, "S.Handle": adapterSHandle.Binding, "Item": adapterItem.Binding}, nil).ValidateValue(protocol.MustTypeExpression("\"string\""), result); err != nil {
				return nil, err
			}
			return result, nil
		}
		if handlers.Request != nil || handlers.Event != nil {
			off, err := runtime.RegisterWire(wire, []string{"no_args"}, handlers)
			if err != nil {
				return err
			}
			detach = append(detach, off)
		}
	}
	{
		handlers := runtime.WireHandlers{Observer: environment.Options.Observer, Family: "proof"}
		handlers.Request = func(ctx context.Context, raw json.RawMessage) (any, error) {
			implementation := lookup()
			if implementation.Methods == nil {
				return nil, fmt.Errorf("model methods are required")
			}
			if false {
				var err error
				ctx, err = environment.ValueEnvironment.Child(ctx)
				if err != nil {
					return nil, err
				}
			}
			if err := protocol.WireSchema().Bind(map[string]any{"S.Envelope": adapterSEnvelope.Binding, "S.Handle": adapterSHandle.Binding, "Item": adapterItem.Binding}, nil).ValidateExpressionRaw(protocol.MustTypeExpression("{\"kind\":\"record\",\"fields\":[{\"name\":\"after\",\"type\":{\"nullable\":\"string\"},\"required\":false}]}"), raw); err != nil {
				var public *runtime.PublicError
				if errors.As(err, &public) && public.Code == "contract_mismatch" {
					return nil, err
				}
				return nil, &runtime.PublicError{Code: "invalid_params", Message: err.Error()}
			}
			var params protocol.PartsRequest
			if err := json.Unmarshal(raw, &params); err != nil {
				var public *runtime.PublicError
				if errors.As(err, &public) && public.Code == "contract_mismatch" {
					return nil, err
				}
				return nil, &runtime.PublicError{Code: "invalid_params", Message: err.Error()}
			}
			result, err := implementation.Methods.Parts(ctx, params)
			if err != nil {
				return nil, err
			}
			sent, err := func() (json.RawMessage, error) {
				var value json.RawMessage
				convert := func(ctx context.Context) (json.RawMessage, error) {
					convertedConvert0 := func(input protocol.Parts) (json.RawMessage, error) {
						converted, err := runtime.MarshalJSON(input)
						if err != nil {
							return nil, err
						}
						return converted, nil
					}
					convertedConvert1 := func(input string) (json.RawMessage, error) {
						converted, err := runtime.MarshalJSON(input)
						if err != nil {
							return nil, err
						}
						return converted, nil
					}
					converted, err := protocol.ExportResult[protocol.Parts, string](result, convertedConvert0, runtime.TypeBinding{Schema: protocol.WireSchema().Bind(map[string]any{"S.Envelope": adapterSEnvelope.Binding, "S.Handle": adapterSHandle.Binding, "Item": adapterItem.Binding}, nil), Type: runtime.MustTypeExpression("\"Parts\"")}, convertedConvert1, runtime.TypeBinding{Schema: protocol.WireSchema().Bind(map[string]any{"S.Envelope": adapterSEnvelope.Binding, "S.Handle": adapterSHandle.Binding, "Item": adapterItem.Binding}, nil), Type: runtime.MustTypeExpression("\"string\"")})
					if err != nil {
						return value, err
					}
					if err := protocol.WireSchema().Bind(map[string]any{"S.Envelope": adapterSEnvelope.Binding, "S.Handle": adapterSHandle.Binding, "Item": adapterItem.Binding}, nil).ValidateExpressionRaw(protocol.MustTypeExpression("{\"apply\":\"Result\",\"with\":{\"E\":\"string\",\"T\":\"Parts\"}}"), converted); err != nil {
						return value, err
					}
					return converted, nil
				}
				if false {
					return environment.ValueEnvironment.Export(ctx, convert)
				}
				return convert(ctx)
			}()
			return sent, err
		}
		if handlers.Request != nil || handlers.Event != nil {
			off, err := runtime.RegisterWire(wire, []string{"parts"}, handlers)
			if err != nil {
				return err
			}
			detach = append(detach, off)
		}
	}
	{
		handlers := runtime.WireHandlers{Observer: environment.Options.Observer, Family: "proof"}
		handlers.Request = func(ctx context.Context, raw json.RawMessage) (any, error) {
			implementation := lookup()
			if implementation.Methods == nil {
				return nil, fmt.Errorf("model methods are required")
			}
			if adapterSEnvelope.NeedsContext || adapterSHandle.NeedsContext || adapterItem.NeedsContext {
				var err error
				ctx, err = environment.ValueEnvironment.Child(ctx)
				if err != nil {
					return nil, err
				}
			}
			params, err := func() (protocol.Carried[SEnvelope, SHandle, Item], error) {
				var value protocol.Carried[SEnvelope, SHandle, Item]
				convert := func(ctx context.Context) (protocol.Carried[SEnvelope, SHandle, Item], error) {
					if err := protocol.WireSchema().Bind(map[string]any{"S.Envelope": adapterSEnvelope.Binding, "S.Handle": adapterSHandle.Binding, "Item": adapterItem.Binding}, nil).ValidateExpressionRaw(protocol.MustTypeExpression("\"Carried\""), raw); err != nil {
						return value, err
					}
					convertedConvert0 := func(input json.RawMessage) (SEnvelope, error) {
						var zero SEnvelope
						converted, err := adapterSEnvelope.Import(ctx, input)
						if err != nil {
							return zero, err
						}
						return converted, nil
					}
					convertedConvert1 := func(input json.RawMessage) (SHandle, error) {
						var zero SHandle
						converted, err := adapterSHandle.Import(ctx, input)
						if err != nil {
							return zero, err
						}
						return converted, nil
					}
					convertedConvert2 := func(input json.RawMessage) (Item, error) {
						var zero Item
						converted, err := adapterItem.Import(ctx, input)
						if err != nil {
							return zero, err
						}
						return converted, nil
					}
					converted, err := protocol.ImportCarried[SEnvelope, SHandle, Item](raw, convertedConvert0, runtime.TypeBinding{Schema: protocol.WireSchema().Bind(map[string]any{"S.Envelope": adapterSEnvelope.Binding, "S.Handle": adapterSHandle.Binding, "Item": adapterItem.Binding}, nil), Type: runtime.MustTypeExpression("\"S.Envelope\"")}, convertedConvert1, runtime.TypeBinding{Schema: protocol.WireSchema().Bind(map[string]any{"S.Envelope": adapterSEnvelope.Binding, "S.Handle": adapterSHandle.Binding, "Item": adapterItem.Binding}, nil), Type: runtime.MustTypeExpression("\"S.Handle\"")}, convertedConvert2, runtime.TypeBinding{Schema: protocol.WireSchema().Bind(map[string]any{"S.Envelope": adapterSEnvelope.Binding, "S.Handle": adapterSHandle.Binding, "Item": adapterItem.Binding}, nil), Type: runtime.MustTypeExpression("\"Item\"")})
					if err != nil {
						return value, err
					}
					return converted, nil
				}
				if adapterSEnvelope.NeedsContext || adapterSHandle.NeedsContext || adapterItem.NeedsContext {
					err := environment.ValueEnvironment.Import(ctx, func(ctx context.Context) error {
						converted, err := convert(ctx)
						if err == nil {
							value = converted
						}
						return err
					})
					if err != nil {
						var zero protocol.Carried[SEnvelope, SHandle, Item]
						return zero, err
					}
					return value, nil
				}
				return convert(ctx)
			}()
			if err != nil {
				var public *runtime.PublicError
				if errors.As(err, &public) && public.Code == "contract_mismatch" {
					return nil, err
				}
				return nil, &runtime.PublicError{Code: "invalid_params", Message: err.Error()}
			}
			result, err := implementation.Methods.Relay(ctx, params)
			if err != nil {
				return nil, err
			}
			sent, err := func() (json.RawMessage, error) {
				var value json.RawMessage
				convert := func(ctx context.Context) (json.RawMessage, error) {
					convertedConvert0 := func(input protocol.Envelope) (json.RawMessage, error) {
						converted, err := runtime.MarshalJSON(input)
						if err != nil {
							return nil, err
						}
						return converted, nil
					}
					converted, err := protocol.ExportOption[protocol.Envelope](result, convertedConvert0, runtime.TypeBinding{Schema: protocol.WireSchema().Bind(map[string]any{"S.Envelope": adapterSEnvelope.Binding, "S.Handle": adapterSHandle.Binding, "Item": adapterItem.Binding}, nil), Type: runtime.MustTypeExpression("\"Envelope\"")})
					if err != nil {
						return value, err
					}
					if err := protocol.WireSchema().Bind(map[string]any{"S.Envelope": adapterSEnvelope.Binding, "S.Handle": adapterSHandle.Binding, "Item": adapterItem.Binding}, nil).ValidateExpressionRaw(protocol.MustTypeExpression("{\"apply\":\"Option\",\"with\":{\"T\":\"Envelope\"}}"), converted); err != nil {
						return value, err
					}
					return converted, nil
				}
				if false {
					return environment.ValueEnvironment.Export(ctx, convert)
				}
				return convert(ctx)
			}()
			return sent, err
		}
		if handlers.Request != nil || handlers.Event != nil {
			off, err := runtime.RegisterWire(wire, []string{"relay"}, handlers)
			if err != nil {
				return err
			}
			detach = append(detach, off)
		}
	}
	complete = true
	return nil
}

type clientMethods[SEnvelope, SHandle, Item any] struct {
	wire             bitwire.Wire
	environment      runtime.AdapterContext
	adapterSEnvelope runtime.ValueAdapter[SEnvelope]
	adapterSHandle   runtime.ValueAdapter[SHandle]
	adapterItem      runtime.ValueAdapter[Item]
}
type clientEvents[SEnvelope, SHandle, Item any] struct {
	wire             bitwire.Wire
	environment      runtime.AdapterContext
	adapterSEnvelope runtime.ValueAdapter[SEnvelope]
	adapterSHandle   runtime.ValueAdapter[SHandle]
	adapterItem      runtime.ValueAdapter[Item]
}

func accessClient[SEnvelope, SHandle, Item any](wire bitwire.Wire, environment runtime.AdapterContext, adapterSEnvelope runtime.ValueAdapter[SEnvelope], adapterSHandle runtime.ValueAdapter[SHandle], adapterItem runtime.ValueAdapter[Item]) protocol.Client[SEnvelope, SHandle, Item] {
	return protocol.Client[SEnvelope, SHandle, Item]{Methods: &clientMethods[SEnvelope, SHandle, Item]{wire: wire, environment: environment, adapterSEnvelope: adapterSEnvelope, adapterSHandle: adapterSHandle, adapterItem: adapterItem}, Events: &clientEvents[SEnvelope, SHandle, Item]{wire: wire, environment: environment, adapterSEnvelope: adapterSEnvelope, adapterSHandle: adapterSHandle, adapterItem: adapterItem}}
}
func (c *clientEvents[SEnvelope, SHandle, Item]) Changed(ctx context.Context, data probeprotocol.Payload) error {
	if err := protocol.WireSchema().Bind(map[string]any{"S.Envelope": c.adapterSEnvelope.Binding, "S.Handle": c.adapterSHandle.Binding, "Item": c.adapterItem.Binding}, nil).ValidateValue(protocol.MustTypeExpression("\"probe.Payload\""), data); err != nil {
		return err
	}
	return runtime.EmitWire(ctx, c.wire, []string{"changed"}, data, runtime.WireEmitOptions{Observer: c.environment.Options.Observer, Family: "proof", Propagator: c.environment.Options.Propagator})
}
func (c *clientEvents[SEnvelope, SHandle, Item]) PartAdded(ctx context.Context, data protocol.RichPart) error {
	if err := protocol.WireSchema().Bind(map[string]any{"S.Envelope": c.adapterSEnvelope.Binding, "S.Handle": c.adapterSHandle.Binding, "Item": c.adapterItem.Binding}, nil).ValidateValue(protocol.MustTypeExpression("\"RichPart\""), data); err != nil {
		return err
	}
	return runtime.EmitWire(ctx, c.wire, []string{"part.added"}, data, runtime.WireEmitOptions{Observer: c.environment.Options.Observer, Family: "proof", Propagator: c.environment.Options.Propagator})
}
func bindClient[SEnvelope, SHandle, Item any](wire runtime.HandlerRegistry, lookup func() protocol.Client[SEnvelope, SHandle, Item], environment runtime.AdapterContext, adapterSEnvelope runtime.ValueAdapter[SEnvelope], adapterSHandle runtime.ValueAdapter[SHandle], adapterItem runtime.ValueAdapter[Item]) error {
	var detach []func()
	complete := false
	defer func() {
		if !complete {
			for _, off := range detach {
				off()
			}
		}
	}()
	{
		handlers := runtime.WireHandlers{Observer: environment.Options.Observer, Family: "proof"}
		handlers.Event = func(ctx context.Context, raw json.RawMessage) error {
			implementation := lookup()
			if implementation.Events == nil {
				return nil
			}
			if err := protocol.WireSchema().Bind(map[string]any{"S.Envelope": adapterSEnvelope.Binding, "S.Handle": adapterSHandle.Binding, "Item": adapterItem.Binding}, nil).ValidateExpressionRaw(protocol.MustTypeExpression("\"probe.Payload\""), raw); err != nil {
				return err
			}
			var data probeprotocol.Payload
			if err := json.Unmarshal(raw, &data); err != nil {
				return err
			}
			return implementation.Events.Changed(ctx, data)
		}
		if handlers.Request != nil || handlers.Event != nil {
			off, err := runtime.RegisterWire(wire, []string{"changed"}, handlers)
			if err != nil {
				return err
			}
			detach = append(detach, off)
		}
	}
	{
		handlers := runtime.WireHandlers{Observer: environment.Options.Observer, Family: "proof"}
		handlers.Event = func(ctx context.Context, raw json.RawMessage) error {
			implementation := lookup()
			if implementation.Events == nil {
				return nil
			}
			if err := protocol.WireSchema().Bind(map[string]any{"S.Envelope": adapterSEnvelope.Binding, "S.Handle": adapterSHandle.Binding, "Item": adapterItem.Binding}, nil).ValidateExpressionRaw(protocol.MustTypeExpression("\"RichPart\""), raw); err != nil {
				return err
			}
			var data protocol.RichPart
			if err := json.Unmarshal(raw, &data); err != nil {
				return err
			}
			return implementation.Events.PartAdded(ctx, data)
		}
		if handlers.Request != nil || handlers.Event != nil {
			off, err := runtime.RegisterWire(wire, []string{"part.added"}, handlers)
			if err != nil {
				return err
			}
			detach = append(detach, off)
		}
	}
	complete = true
	return nil
}
func normalizeContext[SEnvelope, SHandle, Item any](environment runtime.AdapterContext, adapterSEnvelope runtime.ValueAdapter[SEnvelope], adapterSHandle runtime.ValueAdapter[SHandle], adapterItem runtime.ValueAdapter[Item]) (runtime.AdapterContext, error) {
	if adapterSEnvelope.Export == nil || adapterSEnvelope.Import == nil {
		return environment, fmt.Errorf("SEnvelope: both conversion recipes are required")
	}
	if adapterSHandle.Export == nil || adapterSHandle.Import == nil {
		return environment, fmt.Errorf("SHandle: both conversion recipes are required")
	}
	if adapterItem.Export == nil || adapterItem.Import == nil {
		return environment, fmt.Errorf("Item: both conversion recipes are required")
	}
	if (adapterSEnvelope.NeedsContext || adapterSHandle.NeedsContext || adapterItem.NeedsContext) && environment.ValueEnvironment == nil {
		return environment, fmt.Errorf("a context-dependent adapter requires a value environment")
	}
	return environment, nil
}

// ToWire binds one model factory and returns its owned access endpoint.
func ToWire[SEnvelope runtime.Of[STag], SHandle runtime.Of[STag], Item any, STag any](model protocol.ClientModel[SEnvelope, SHandle, Item], environment runtime.AdapterContext, adapterSEnvelope runtime.ValueAdapter[SEnvelope], adapterSHandle runtime.ValueAdapter[SHandle], adapterItem runtime.ValueAdapter[Item]) (bitwire.Endpoint, error) {
	if model == nil {
		return nil, fmt.Errorf("model factory is required")
	}
	environment, err := normalizeContext[SEnvelope, SHandle, Item](environment, adapterSEnvelope, adapterSHandle, adapterItem)
	if err != nil {
		return nil, err
	}
	identity, err := declarationIdentity[SEnvelope, SHandle, Item](adapterSEnvelope, adapterSHandle, adapterItem)
	if err != nil {
		return nil, err
	}
	options := environment.Options
	families := map[string]string{}
	for name, existing := range options.Families {
		families[name] = existing
	}
	families["4:echo"] = "proof"
	families["7:no_args"] = "proof"
	families["8:classify"] = "proof"
	families["13:classify_rich"] = "proof"
	families["5:parts"] = "proof"
	families["5:relay"] = "proof"
	families["7:changed"] = "proof"
	families["10:part.added"] = "proof"
	options.Families = families
	access, binding, err := runtime.NewWirePair(options)
	if err != nil {
		return nil, err
	}
	complete := false
	defer func() {
		if !complete {
			_ = access.Close(duplex.CodeInternalError, "model construction failed")
		}
	}()
	dispatcher, err := runtime.NewDispatcher(binding, runtime.DispatcherOptions{OwnEndpoint: true})
	if err != nil {
		return nil, err
	}
	if _, err := registerIdentity(dispatcher, identity); err != nil {
		return nil, err
	}
	implementation, err := model(accessServer[SEnvelope, SHandle, Item](binding, environment, adapterSEnvelope, adapterSHandle, adapterItem))
	if err != nil {
		return nil, err
	}
	if err := bindClient[SEnvelope, SHandle, Item](dispatcher, func() protocol.Client[SEnvelope, SHandle, Item] { return implementation }, environment, adapterSEnvelope, adapterSHandle, adapterItem); err != nil {
		return nil, err
	}
	complete = true
	return access, nil
}
func declarationIdentity[SEnvelope, SHandle, Item any](adapterSEnvelope runtime.ValueAdapter[SEnvelope], adapterSHandle runtime.ValueAdapter[SHandle], adapterItem runtime.ValueAdapter[Item]) (runtime.DeclarationIdentity, error) {
	digest, err := protocol.WireSchema().Bind(map[string]any{"S.Envelope": adapterSEnvelope.Binding, "S.Handle": adapterSHandle.Binding, "Item": adapterItem.Binding}, nil).DeclarationDigest()
	if err != nil {
		return runtime.DeclarationIdentity{}, err
	}
	return runtime.DeclarationIdentity{Path: "proof", Digest: digest}, nil
}
func registerIdentity(wire runtime.HandlerRegistry, identity runtime.DeclarationIdentity) (func(), error) {
	handler, err := runtime.IdentityHandler(identity)
	if err != nil {
		return nil, err
	}
	return runtime.HandleWire(wire, []string{runtime.IdentityMethod}, func(ctx context.Context, raw json.RawMessage) (any, error) { return handler(ctx, nil, raw) })
}

// PrepareFromWire registers receivers synchronously, before the wire is attached.
// Complete checks identity and returns a factory that may be bound once. Both steps
// must finish within environment.Options.RequestTimeout. Cleanup detaches this
// interpretation's registrations, including after success, and never closes the wire.
func PrepareFromWire[SEnvelope runtime.Of[STag], SHandle runtime.Of[STag], Item any, STag any](wire bitwire.Endpoint, environment runtime.AdapterContext, adapterSEnvelope runtime.ValueAdapter[SEnvelope], adapterSHandle runtime.ValueAdapter[SHandle], adapterItem runtime.ValueAdapter[Item]) (complete func(context.Context) (protocol.ClientModel[SEnvelope, SHandle, Item], error), cleanup func(), err error) {
	if wire == nil {
		return nil, nil, fmt.Errorf("wire is required")
	}
	environment, err = normalizeContext[SEnvelope, SHandle, Item](environment, adapterSEnvelope, adapterSHandle, adapterItem)
	if err != nil {
		return nil, nil, err
	}
	identity, err := declarationIdentity[SEnvelope, SHandle, Item](adapterSEnvelope, adapterSHandle, adapterItem)
	if err != nil {
		return nil, nil, err
	}
	preparation, err := runtime.PrepareIdentity(wire, identity, environment.Options)
	if err != nil {
		return nil, nil, err
	}
	cleanup = preparation.Close
	var implementation atomic.Pointer[protocol.Server[SEnvelope, SHandle, Item]]
	lookup := func() protocol.Server[SEnvelope, SHandle, Item] {
		if current := implementation.Load(); current != nil {
			return *current
		}
		return protocol.Server[SEnvelope, SHandle, Item]{}
	}
	if err = bindServer[SEnvelope, SHandle, Item](preparation.Wire(), lookup, environment, adapterSEnvelope, adapterSHandle, adapterItem); err != nil {
		cleanup()
		return nil, nil, err
	}
	var checking, bound atomic.Bool
	complete = func(ctx context.Context) (protocol.ClientModel[SEnvelope, SHandle, Item], error) {
		if !checking.CompareAndSwap(false, true) {
			return nil, fmt.Errorf("identity completion is already started")
		}
		if err := preparation.Check(ctx); err != nil {
			cleanup()
			return nil, err
		}
		return func(value protocol.Server[SEnvelope, SHandle, Item]) (protocol.Client[SEnvelope, SHandle, Item], error) {
			if !bound.CompareAndSwap(false, true) {
				return protocol.Client[SEnvelope, SHandle, Item]{}, fmt.Errorf("model factory is already bound")
			}
			if value.Methods == nil {
				cleanup()
				return protocol.Client[SEnvelope, SHandle, Item]{}, fmt.Errorf("Server methods are required")
			}
			implementation.Store(&value)
			if err := preparation.Ready(); err != nil {
				cleanup()
				return protocol.Client[SEnvelope, SHandle, Item]{}, err
			}
			return accessClient[SEnvelope, SHandle, Item](preparation.Wire(), environment, adapterSEnvelope, adapterSHandle, adapterItem), nil
		}, nil
	}
	return complete, cleanup, nil
}

// FromWire checks identity and returns a factory that may be bound once.
// Use PrepareFromWire before attachment when incoming delivery can begin immediately.
func FromWire[SEnvelope runtime.Of[STag], SHandle runtime.Of[STag], Item any, STag any](ctx context.Context, wire bitwire.Endpoint, environment runtime.AdapterContext, adapterSEnvelope runtime.ValueAdapter[SEnvelope], adapterSHandle runtime.ValueAdapter[SHandle], adapterItem runtime.ValueAdapter[Item]) (protocol.ClientModel[SEnvelope, SHandle, Item], error) {
	complete, cleanup, err := PrepareFromWire[SEnvelope, SHandle, Item](wire, environment, adapterSEnvelope, adapterSHandle, adapterItem)
	if err != nil {
		return nil, err
	}
	model, err := complete(ctx)
	if err != nil {
		cleanup()
		return nil, err
	}
	return model, nil
}

// RecordedEvent is the closed union of this side's outgoing event payloads.
type RecordedEvent[SEnvelope, SHandle, Item any] interface {
	recordedEvent(SEnvelope, SHandle, Item)
}

// Recorder records converted messages without retaining or rebinding their live values.
type Recorder[SEnvelope, SHandle, Item any] struct {
	*duplex.RecordedWire
	events   protocol.ServerEvents[SEnvelope, SHandle, Item]
	identity runtime.DeclarationIdentity
	options  runtime.Options
}

func (r *Recorder[SEnvelope, SHandle, Item]) Append(ctx context.Context, event RecordedEvent[SEnvelope, SHandle, Item]) error {
	return fmt.Errorf("this side declares no outgoing events")
}

// Follow checks the subscriber's declaration before registering any replay.
func (r *Recorder[SEnvelope, SHandle, Item]) Follow(ctx context.Context, after uint64, target bitwire.Wire) (*duplex.Follower, error) {
	if err := runtime.CheckIdentity(ctx, func(ctx context.Context, method string, params, result any) error {
		return runtime.CallWire(ctx, target, []string{method}, params, result, runtime.WireCallOptions{RequestTimeout: r.options.RequestTimeout, Observer: r.options.Observer, Propagator: r.options.Propagator})
	}, r.identity); err != nil {
		return nil, err
	}
	return r.RecordedWire.Follow(ctx, after, target)
}

// Record checks a prepared origin before exposing typed event append. Setup
// failure detaches this interpretation and leaves the borrowed target usable.
func Record[SEnvelope runtime.Of[STag], SHandle runtime.Of[STag], Item any, STag any](ctx context.Context, target bitwire.Endpoint, log duplex.WireLog, options duplex.RecordOptions, environment runtime.AdapterContext, adapterSEnvelope runtime.ValueAdapter[SEnvelope], adapterSHandle runtime.ValueAdapter[SHandle], adapterItem runtime.ValueAdapter[Item]) (*Recorder[SEnvelope, SHandle, Item], error) {
	environment, err := normalizeContext[SEnvelope, SHandle, Item](environment, adapterSEnvelope, adapterSHandle, adapterItem)
	if err != nil {
		return nil, err
	}
	identity, err := declarationIdentity[SEnvelope, SHandle, Item](adapterSEnvelope, adapterSHandle, adapterItem)
	if err != nil {
		return nil, err
	}
	preparation, err := runtime.PrepareIdentity(target, identity, environment.Options)
	if err != nil {
		return nil, err
	}
	if err := preparation.Check(ctx); err != nil {
		preparation.Close()
		return nil, err
	}
	if err := preparation.Ready(); err != nil {
		preparation.Close()
		return nil, err
	}
	onClose := options.OnClose
	options.OnClose = func(err error) {
		preparation.Close()
		if onClose != nil {
			onClose(err)
		}
	}
	wire, err := duplex.Record(ctx, preparation.Wire(), log, options)
	if err != nil {
		preparation.Close()
		return nil, err
	}
	return &Recorder[SEnvelope, SHandle, Item]{RecordedWire: wire, events: accessServer[SEnvelope, SHandle, Item](wire, environment, adapterSEnvelope, adapterSHandle, adapterItem).Events, identity: identity, options: environment.Options}, nil
}
