// Code generated by nightseam. DO NOT EDIT.
import type {ValueAdapter} from "@nightseam/runtime";
const examples: Readonly<Record<string, { raw?: string; reason?: string }>> = {
"Batch": { raw: "{\"items\":[{\"kind\":\"none\"}],\"next\":{\"kind\":\"none\"}}", reason: "" },
"Box": { raw: "{\"item\":\"‹item›\"}", reason: "" },
"Choice": { raw: "{\"kind\":\"none\"}", reason: "" },
"Page": { raw: "{\"items\":[\"‹items›\"],\"next\":\"‹next›\"}", reason: "" },
"Result": { raw: "{\"kind\":\"none\"}", reason: "" },
};
/** A fresh documented data witness, validated by the caller's exact value adapter. */
export function example<T>(name: string, adapter: ValueAdapter<T>): T { const value = Object.prototype.hasOwnProperty.call(examples,name) ? examples[name] : undefined; if (!value) throw new Error('unknown example '+name); if (value.reason || adapter.needsContext) throw new Error('example '+name+' unavailable: '+(value.reason || 'an acquiring adapter needs a native witness')); return adapter.import(undefined, JSON.parse(value.raw!)); }
