// Code generated by nightseam. DO NOT EDIT.
import { createValidator, DuplexError, type AnyFamily, type FamilyBinding, type TypeBinding, type Slots, type TypeExpression, type WireFamily } from "@nightseam/runtime";
export type { AnyFamily, FamilyBinding, TypeBinding, Slots, TypeExpression };
import type { ValueAdapter, ValueContext } from "@nightseam/runtime";
import type { WireModelContext } from "@nightseam/runtime";
/** An account: identified, with a unique email and a bounded balance. */
export interface Account {
  "id": string;
  "email": string;
  "balance": number;
  "tags": Array<string>;
  "opened_at": string;
}
/** One message of the nightseam.duplex/1 profile: the members the peer acts on, and nothing else. */
export interface Envelope {
  /** The profile's version, 1. */
  "version": number;
  /** request, response, event or cancel. */
  "kind": string;
  /** What correlates a response or a cancel with its request. */
  "id"?: string;
  /** The method a request names. */
  "method"?: string;
  /** A request's parameters. */
  "params"?: unknown;
  /** A response's result. */
  "result"?: unknown;
  /** A response's error. */
  "error"?: unknown;
  /** The event an event frame names. */
  "event"?: string;
  /** An event's data. */
  "data"?: unknown;
  /** The W3C Trace Context of the frame. */
  "traceparent"?: string;
  /** The vendor state of that trace. */
  "tracestate"?: string;
  /** What a request or an event carries about the call, delivered to the handler beside the payload. */
  "meta"?: Record<string, string>;
}
/** A reference to a channel on the connection that carries the message holding it. */
export interface Handle {
  /** The channel's id on that connection. */
  "channel": number;
}
/** A transfer between two accounts, by their keys. */
export interface Transfer {
  "from": string;
  "to": string;
  "note"?: string;
}
/** The family: its name and the wire types a slot of it draws on. */
export interface Family { readonly name: "ledger"; Account: Account; Envelope: Envelope; Handle: Handle; Transfer: Transfer }
export function adapterAccount(): ValueAdapter<Account> {
  const slots: Slots = {  };
  const binding: TypeBinding = { type: "Account", validate: validateWire, slots };
  const needsContext = false;
  return { binding, needsContext,
    export(context: unknown, value: Account): unknown {
      if (needsContext && context === undefined) throw new DuplexError('scope_closed', 'conversion requires a value context');
      const convert = (owner: unknown): unknown => {
        const converted = value;
        binding.validate(binding.type, converted, '$', slots);
        return converted;
      };
      return convert(context);
    },
    import(context: unknown, raw: unknown): Account {
      if (needsContext && context === undefined) throw new DuplexError('scope_closed', 'conversion requires a value context');
      binding.validate(binding.type, raw, '$', slots);
      const convert = (owner: unknown): Account => {
        const converted = raw as Account;
        return converted;
      };
      return convert(context);
    },
  };
}
export function adapterTransfer(): ValueAdapter<Transfer> {
  const slots: Slots = {  };
  const binding: TypeBinding = { type: "Transfer", validate: validateWire, slots };
  const needsContext = false;
  return { binding, needsContext,
    export(context: unknown, value: Transfer): unknown {
      if (needsContext && context === undefined) throw new DuplexError('scope_closed', 'conversion requires a value context');
      const convert = (owner: unknown): unknown => {
        const converted = value;
        binding.validate(binding.type, converted, '$', slots);
        return converted;
      };
      return convert(context);
    },
    import(context: unknown, raw: unknown): Transfer {
      if (needsContext && context === undefined) throw new DuplexError('scope_closed', 'conversion requires a value context');
      binding.validate(binding.type, raw, '$', slots);
      const convert = (owner: unknown): Transfer => {
        const converted = raw as Transfer;
        return converted;
      };
      return convert(context);
    },
  };
}
export interface ServerMethods {
}
export interface ServerEvents {
}
export interface Server { methods: ServerMethods; events: ServerEvents; }
export interface ClientMethods {
}
export interface ClientEvents {
}
export interface Client { methods: ClientMethods; events: ClientEvents; }
export type ServerModel = (remote: Client) => Server;
export type ClientModel = (remote: Server) => Client;

const contractTypes = {"types":{"Account":{"kind":"entity","key":"id","fields":[{"name":"id","type":"string","required":true},{"name":"email","type":"string","required":true,"unique":true,"pattern":"^[^@]+@[^@]+$"},{"name":"balance","type":"integer","required":true,"min":0,"max":1000000},{"name":"tags","type":{"array":"string"},"required":true,"length":{"max":8}},{"name":"opened_at","type":"timestamp","required":true}]},"Envelope":{"kind":"record","fields":[{"name":"version","type":"integer","required":true},{"name":"kind","type":"string","required":true},{"name":"id","type":"string","required":false},{"name":"method","type":"string","required":false},{"name":"params","type":"json","required":false},{"name":"result","type":"json","required":false},{"name":"error","type":"json","required":false},{"name":"event","type":"string","required":false},{"name":"data","type":"json","required":false},{"name":"traceparent","type":"string","required":false},{"name":"tracestate","type":"string","required":false},{"name":"meta","type":{"map":"string"},"required":false}]},"Handle":{"kind":"record","fields":[{"name":"channel","type":"integer","required":true}]},"Transfer":{"kind":"record","fields":[{"name":"from","type":{"ref":"Account"},"required":true},{"name":"to","type":{"ref":"Account"},"required":true},{"name":"note","type":"string","required":false,"length":{"min":1,"max":140}}]}}} as unknown as WireFamily;
/** Runtime validation applies equally to calls, replies, reverse calls and events; what fills a slot of a parameter is validated by the binding of the family that fills it. */
export const validateWire = createValidator(contractTypes, {  });
/** This family bound: its name and its validator, to fill a family slot in another family's client. */
export const family = { name: "ledger", validate: validateWire } as const;
