// Code generated by nightseam. DO NOT EDIT.
import { DuplexError, callWire, emitWire, registerWire, wirePair, createDispatcher, declarationDigest, familyTypeAdapter, validateDrawnType, jsonAdapter, identityHandler, IDENTITY_METHOD, prepareIdentity, type HandlerRegistry, type WireModelContext, type WireCallOptions } from "@nightseam/runtime";
import { encodePath, type Wire, type Endpoint } from '@nightseam/duplex';
import type { AdapterContext, ValueAdapter, ValueContext } from "@nightseam/runtime";
import type { LiveOwner } from "@nightseam/live";
import { validateWire } from "@example/second-client/types";
import type * as Protocol from "@example/second-client/types";
import type { AnyFamily, FamilyBinding, Slots } from "@example/second-client/types";
import * as conversion from "@example/second-client/types";
export * from "@example/second-client/types";
export { DuplexError };
export type { AdapterContext };
function makeAdapter(context: AdapterContext) {
  const options = { ...context.options };
  const observer = options.observer;
  const propagator = options.propagator;
  const requestTimeoutMs = options.requestTimeoutMs;
  const bindings = {  };
  const slots: Slots = {  };
  const identity = { path: "second", digest: declarationDigest(validateWire, slots) };
  const environment = context.valueEnvironment;
  if ((true) && !environment) throw new DuplexError('scope_closed', 'model adaptation requires an explicit value environment');
  function hasModelHandler(facet: object, name: string): boolean {
    for (let current = facet; current !== null && current !== Object.prototype; current = Object.getPrototypeOf(current)) {
      if (Object.prototype.hasOwnProperty.call(current, name)) return typeof (facet as Record<string, unknown>)[name] === 'function';
    }
    return false;
  }
  function proxyServer(wire: Wire): Protocol.Server {
    return {
      methods: {
      },
      events: {
      },
    };
  }
  function validateServer(implementation: Protocol.Server): void {
    if (!implementation?.methods || !implementation.events) throw new Error('model methods and events are required');
  }
  function bindServer(wire: HandlerRegistry, implementation: () => Protocol.Server): () => void {
    const detach: Array<() => void> = [];
    try {
    } catch (error) { for (const remove of detach.reverse()) remove(); throw error; }
    return () => { for (const remove of detach.reverse()) remove(); };
  }
  function proxyClient(wire: Wire): Protocol.Client {
    return {
      methods: {
      },
      events: {
      },
    };
  }
  function validateClient(implementation: Protocol.Client): void {
    if (!implementation?.methods || !implementation.events) throw new Error('model methods and events are required');
  }
  function bindClient(wire: HandlerRegistry, implementation: () => Protocol.Client): () => void {
    const detach: Array<() => void> = [];
    try {
    } catch (error) { for (const remove of detach.reverse()) remove(); throw error; }
    return () => { for (const remove of detach.reverse()) remove(); };
  }
  return { options, identity, proxyServer, proxyClient, validateServer, validateClient, bindServer, bindClient };
}
/** Exposes one model session at a new local wire origin. */
export function toWire(model: Protocol.ServerModel, context: AdapterContext): Endpoint {
  const adapter = makeAdapter(context);
  const [access, binding] = wirePair({ ...adapter.options, families: { ...adapter.options.families } });
  try {
    const dispatcher = createDispatcher(binding, { ownEndpoint: true });
    registerWire(dispatcher, [IDENTITY_METHOD], { request: identityHandler(adapter.identity) });
    const implementation = model(adapter.proxyClient(binding));
    adapter.validateServer(implementation);
    adapter.bindServer(dispatcher, () => implementation);
    return access;
  } catch (error) { access.close(); throw error; }
}
/** Registers receivers before reading begins; complete checks identity before returning the one-use model factory. Close detaches this interpretation without closing its carrier. */
export function prepareFromWire(wire: Endpoint, context: AdapterContext): { complete(options?: WireCallOptions): Promise<Protocol.ServerModel>; close(): void } {
  const adapter = makeAdapter(context);
  const gate = prepareIdentity(wire, adapter.identity, adapter.options);
  let implementation: Protocol.Client | undefined;
  let completed = false, bound = false, closed = false;
  const detach: Array<() => void> = [];
  const cleanup = () => { if (closed) return; closed = true; implementation = undefined; gate.close(); for (const remove of detach.reverse()) remove(); };
  try {
    detach.push(adapter.bindClient(gate.wire, () => implementation!));
  } catch (error) { cleanup(); throw error; }
  return {
    async complete(options?: WireCallOptions): Promise<Protocol.ServerModel> {
      if (closed) throw new DuplexError('scope_closed', 'model interpretation is closed');
      if (completed) throw new DuplexError('already_bound', 'model interpretation already completed');
      completed = true;
      try { await gate.check(options); } catch (error) { cleanup(); throw error; }
      return remote => {
        if (closed) throw new DuplexError('scope_closed', 'model interpretation is closed');
        if (bound) throw new DuplexError('already_bound', 'model already bound');
        bound = true;
        try {
          adapter.validateClient(remote);
          implementation = remote;
          gate.ready();
          return adapter.proxyServer(gate.wire);
        } catch (error) { cleanup(); throw error; }
      };
    },
    close: cleanup,
  };
}
/** Checks and interprets a wire as the same model factory; the resulting session binds once. */
export async function fromWire(wire: Endpoint, context: AdapterContext): Promise<Protocol.ServerModel> {
  const preparation = prepareFromWire(wire, context);
  try { return await preparation.complete(); } catch (error) { preparation.close(); throw error; }
}
import { record as recordWire, type WireLog, type RecordOptions, type RecordedWire } from '@nightseam/duplex';
import { checkIdentity } from "@nightseam/runtime";
/** The closed union of this side's outgoing native event payloads. */
export type RecordedEvent = never;
export interface Recorder extends RecordedWire { append(event: RecordedEvent, context?: WireModelContext): Promise<void>; }
/** Checks a prepared origin before typed append; failed setup leaves its carrier usable. */
export async function record(target: Endpoint, log: WireLog, options: RecordOptions, context: AdapterContext, setup?: WireCallOptions): Promise<Recorder> {
  const adapter = makeAdapter(context);
  const preparation = prepareIdentity(target, adapter.identity, adapter.options);
  try {
    await preparation.check(setup); preparation.ready();
    const wire = await recordWire(preparation.wire, log, { ...options, onClose(error) { preparation.close(); options.onClose?.(error); } }, setup?.signal);
    const events = adapter.proxyClient(wire).events;
    return {
      ...wire,
      async append(event, context) {
        throw new Error('This side declares no outgoing events.');
      },
      async follow(after, subscriber, signal) {
        await checkIdentity((method, params, options) => callWire(subscriber, [method], params, { ...options, observer: adapter.options.observer, propagator: adapter.options.propagator }), adapter.identity, { signal, timeoutMs: adapter.options.requestTimeoutMs });
        return wire.follow(after, subscriber, signal);
      },
    };
  } catch (error) { preparation.close(); throw error; }
}
