// Code generated by nightseam. DO NOT EDIT.
package albumprotocol

import (
	json "encoding/json"
	carrierprotocol "example.test/generated/api/go/carrier-protocol"
	probeprotocol "example.test/generated/api/go/probe-protocol"
	runtime "github.com/Bitspark/nightseam/runtime/go"
)

// Tag is this family, as a type: what every record and enum of the package returns from Of, and what an entry point of a package generic in a family holds its type arguments to.
type Tag struct{}

// Borrowed: A carrier frame, its S filled by B.
type Borrowed[BEnvelope any] struct {
	Frame carrierprotocol.Frame[BEnvelope] `json:"frame"`
}

func (v Borrowed[BEnvelope]) MarshalJSON() ([]byte, error) {
	data, err := json.Marshal((struct {
		Frame carrierprotocol.Frame[BEnvelope] `json:"frame"`
	})(v))
	if err != nil {
		return nil, err
	}
	if err = schema.Bind(map[string]any{"B.Envelope": runtime.TypeArgument[BEnvelope]()}, nil).ValidateExpressionRaw("Borrowed", data); err != nil {
		return nil, err
	}
	return data, nil
}
func (v *Borrowed[BEnvelope]) UnmarshalJSON(data []byte) error {
	if err := schema.Bind(map[string]any{"B.Envelope": runtime.TypeArgument[BEnvelope]()}, nil).ValidateExpressionRaw("Borrowed", data); err != nil {
		return err
	}
	var decoded (struct {
		Frame carrierprotocol.Frame[BEnvelope] `json:"frame"`
	})
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*v = Borrowed[BEnvelope](decoded)
	return nil
}
func (Borrowed[BEnvelope]) Of() Tag { return Tag{} }
func (Borrowed[BEnvelope]) WireType() runtime.TypeBinding {
	return runtime.TypeBinding{Schema: schema.Bind(map[string]any{"B.Envelope": runtime.TypeArgument[BEnvelope]()}, nil), Type: "Borrowed"}
}

type Both[AEnvelope, BEnvelope any] struct {
	Mine     Mine[AEnvelope]              `json:"mine"`
	Borrowed Borrowed[BEnvelope]          `json:"borrowed"`
	Fixed    Fixed                        `json:"fixed"`
	Params   carrierprotocol.AttachParams `json:"params"`
}

func (v Both[AEnvelope, BEnvelope]) MarshalJSON() ([]byte, error) {
	data, err := json.Marshal((struct {
		Mine     Mine[AEnvelope]              `json:"mine"`
		Borrowed Borrowed[BEnvelope]          `json:"borrowed"`
		Fixed    Fixed                        `json:"fixed"`
		Params   carrierprotocol.AttachParams `json:"params"`
	})(v))
	if err != nil {
		return nil, err
	}
	if err = schema.Bind(map[string]any{"A.Envelope": runtime.TypeArgument[AEnvelope](), "B.Envelope": runtime.TypeArgument[BEnvelope]()}, nil).ValidateExpressionRaw("Both", data); err != nil {
		return nil, err
	}
	return data, nil
}
func (v *Both[AEnvelope, BEnvelope]) UnmarshalJSON(data []byte) error {
	if err := schema.Bind(map[string]any{"A.Envelope": runtime.TypeArgument[AEnvelope](), "B.Envelope": runtime.TypeArgument[BEnvelope]()}, nil).ValidateExpressionRaw("Both", data); err != nil {
		return err
	}
	var decoded (struct {
		Mine     Mine[AEnvelope]              `json:"mine"`
		Borrowed Borrowed[BEnvelope]          `json:"borrowed"`
		Fixed    Fixed                        `json:"fixed"`
		Params   carrierprotocol.AttachParams `json:"params"`
	})
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*v = Both[AEnvelope, BEnvelope](decoded)
	return nil
}
func (Both[AEnvelope, BEnvelope]) Of() Tag { return Tag{} }
func (Both[AEnvelope, BEnvelope]) WireType() runtime.TypeBinding {
	return runtime.TypeBinding{Schema: schema.Bind(map[string]any{"A.Envelope": runtime.TypeArgument[AEnvelope](), "B.Envelope": runtime.TypeArgument[BEnvelope]()}, nil), Type: "Both"}
}

// Envelope: One message of the nightseam.duplex/1 profile: the members the peer acts on, and nothing else.
type Envelope struct {
	Version     int64                               `json:"version"`
	Kind        string                              `json:"kind"`
	ID          runtime.Optional[string]            `json:"id,omitzero"`
	Method      runtime.Optional[string]            `json:"method,omitzero"`
	Params      runtime.Optional[any]               `json:"params,omitzero"`
	Result      runtime.Optional[any]               `json:"result,omitzero"`
	Error       runtime.Optional[any]               `json:"error,omitzero"`
	Event       runtime.Optional[string]            `json:"event,omitzero"`
	Data        runtime.Optional[any]               `json:"data,omitzero"`
	Traceparent runtime.Optional[string]            `json:"traceparent,omitzero"`
	Tracestate  runtime.Optional[string]            `json:"tracestate,omitzero"`
	Meta        runtime.Optional[map[string]string] `json:"meta,omitzero"`
}

func (v Envelope) MarshalJSON() ([]byte, error) {
	type wire Envelope
	data, err := json.Marshal(wire(v))
	if err != nil {
		return nil, err
	}
	if err = schema.ValidateExpressionRaw("Envelope", data); err != nil {
		return nil, err
	}
	return data, nil
}
func (v *Envelope) UnmarshalJSON(data []byte) error {
	if err := schema.ValidateExpressionRaw("Envelope", data); err != nil {
		return err
	}
	type wire Envelope
	var decoded wire
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*v = Envelope(decoded)
	return nil
}
func (Envelope) Of() Tag { return Tag{} }
func (Envelope) WireType() runtime.TypeBinding {
	return runtime.TypeBinding{Schema: schema, Type: "Envelope"}
}

// Fixed: A carrier frame, its S filled by probe.
type Fixed struct {
	Frame carrierprotocol.Frame[probeprotocol.Envelope] `json:"frame"`
}

func (v Fixed) MarshalJSON() ([]byte, error) {
	type wire Fixed
	data, err := json.Marshal(wire(v))
	if err != nil {
		return nil, err
	}
	if err = schema.ValidateExpressionRaw("Fixed", data); err != nil {
		return nil, err
	}
	return data, nil
}
func (v *Fixed) UnmarshalJSON(data []byte) error {
	if err := schema.ValidateExpressionRaw("Fixed", data); err != nil {
		return err
	}
	type wire Fixed
	var decoded wire
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*v = Fixed(decoded)
	return nil
}
func (Fixed) Of() Tag { return Tag{} }
func (Fixed) WireType() runtime.TypeBinding {
	return runtime.TypeBinding{Schema: schema, Type: "Fixed"}
}

// Handle: A reference to a channel on the connection that carries the message holding it.
type Handle struct {
	Channel int64 `json:"channel"`
}

func (v Handle) MarshalJSON() ([]byte, error) {
	type wire Handle
	data, err := json.Marshal(wire(v))
	if err != nil {
		return nil, err
	}
	if err = schema.ValidateExpressionRaw("Handle", data); err != nil {
		return nil, err
	}
	return data, nil
}
func (v *Handle) UnmarshalJSON(data []byte) error {
	if err := schema.ValidateExpressionRaw("Handle", data); err != nil {
		return err
	}
	type wire Handle
	var decoded wire
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*v = Handle(decoded)
	return nil
}
func (Handle) Of() Tag { return Tag{} }
func (Handle) WireType() runtime.TypeBinding {
	return runtime.TypeBinding{Schema: schema, Type: "Handle"}
}

// Mine: One message of A.
type Mine[AEnvelope any] struct {
	Held AEnvelope `json:"held"`
}

func (v Mine[AEnvelope]) MarshalJSON() ([]byte, error) {
	data, err := json.Marshal((struct {
		Held AEnvelope `json:"held"`
	})(v))
	if err != nil {
		return nil, err
	}
	if err = schema.Bind(map[string]any{"A.Envelope": runtime.TypeArgument[AEnvelope]()}, nil).ValidateExpressionRaw("Mine", data); err != nil {
		return nil, err
	}
	return data, nil
}
func (v *Mine[AEnvelope]) UnmarshalJSON(data []byte) error {
	if err := schema.Bind(map[string]any{"A.Envelope": runtime.TypeArgument[AEnvelope]()}, nil).ValidateExpressionRaw("Mine", data); err != nil {
		return err
	}
	var decoded (struct {
		Held AEnvelope `json:"held"`
	})
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*v = Mine[AEnvelope](decoded)
	return nil
}
func (Mine[AEnvelope]) Of() Tag { return Tag{} }
func (Mine[AEnvelope]) WireType() runtime.TypeBinding {
	return runtime.TypeBinding{Schema: schema.Bind(map[string]any{"A.Envelope": runtime.TypeArgument[AEnvelope]()}, nil), Type: "Mine"}
}
