// Code generated by nightseam. DO NOT EDIT.
package secondprotocol

import (
	context "context"
	json "encoding/json"
	fmt "fmt"
	live "github.com/Bitspark/nightseam/live/go"
	runtime "github.com/Bitspark/nightseam/runtime/go"
)

// Tag is this family, as a type: what every record and enum of the package returns from Of, and what an entry point of a package generic in a family holds its type arguments to.
type Tag struct{}

// Envelope: One message of the nightseam.duplex/1 profile: the members the peer acts on, and nothing else.
type Envelope struct {
	Version     int64                               `json:"version"`
	Kind        string                              `json:"kind"`
	ID          runtime.Optional[string]            `json:"id,omitzero"`
	Method      runtime.Optional[string]            `json:"method,omitzero"`
	Params      runtime.Optional[any]               `json:"params,omitzero"`
	Result      runtime.Optional[any]               `json:"result,omitzero"`
	Error       runtime.Optional[any]               `json:"error,omitzero"`
	Event       runtime.Optional[string]            `json:"event,omitzero"`
	Data        runtime.Optional[any]               `json:"data,omitzero"`
	Traceparent runtime.Optional[string]            `json:"traceparent,omitzero"`
	Tracestate  runtime.Optional[string]            `json:"tracestate,omitzero"`
	Meta        runtime.Optional[map[string]string] `json:"meta,omitzero"`
}

func (v Envelope) MarshalJSON() ([]byte, error) {
	type wire Envelope
	data, err := runtime.MarshalJSON(wire(v))
	if err != nil {
		return nil, err
	}
	if err = schema.ValidateExpressionRaw("Envelope", data); err != nil {
		return nil, err
	}
	return data, nil
}
func (v *Envelope) UnmarshalJSON(data []byte) error {
	if err := schema.ValidateExpressionRaw("Envelope", data); err != nil {
		return err
	}
	type wire Envelope
	var decoded wire
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*v = Envelope(decoded)
	return nil
}
func (Envelope) Of() Tag { return Tag{} }
func (Envelope) WireType() runtime.TypeBinding {
	return runtime.TypeBinding{Schema: schema, Type: "Envelope"}
}

// Handle: A reference to a channel on the connection that carries the message holding it.
type Handle struct {
	Channel int64 `json:"channel"`
}

func (v Handle) MarshalJSON() ([]byte, error) {
	type wire Handle
	data, err := runtime.MarshalJSON(wire(v))
	if err != nil {
		return nil, err
	}
	if err = schema.ValidateExpressionRaw("Handle", data); err != nil {
		return nil, err
	}
	return data, nil
}
func (v *Handle) UnmarshalJSON(data []byte) error {
	if err := schema.ValidateExpressionRaw("Handle", data); err != nil {
		return err
	}
	type wire Handle
	var decoded wire
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*v = Handle(decoded)
	return nil
}
func (Handle) Of() Tag { return Tag{} }
func (Handle) WireType() runtime.TypeBinding {
	return runtime.TypeBinding{Schema: schema, Type: "Handle"}
}

type Job struct {
	Run Run `json:"run"`
}

// MarshalJSON refuses: Job carries a callable, and a live value has no encoding apart from the owner its bindings belong to.
func (v Job) MarshalJSON() ([]byte, error) {
	return nil, fmt.Errorf("Job carries a callable; write it with ExportJob, which takes the live owner its bindings are made in")
}

// UnmarshalJSON refuses for the same reason: a reference resolves in a owner or nowhere.
func (v *Job) UnmarshalJSON(data []byte) error {
	return fmt.Errorf("Job carries a callable; read it with ImportJob, which takes the live owner its references resolve in")
}
func (Job) Of() Tag                       { return Tag{} }
func (Job) WireType() runtime.TypeBinding { return runtime.TypeBinding{Schema: schema, Type: "Job"} }

type Progress struct {
	Read Run `json:"read"`
}

// MarshalJSON refuses: Progress carries a callable, and a live value has no encoding apart from the owner its bindings belong to.
func (v Progress) MarshalJSON() ([]byte, error) {
	return nil, fmt.Errorf("Progress carries a callable; write it with ExportProgress, which takes the live owner its bindings are made in")
}

// UnmarshalJSON refuses for the same reason: a reference resolves in a owner or nowhere.
func (v *Progress) UnmarshalJSON(data []byte) error {
	return fmt.Errorf("Progress carries a callable; read it with ImportProgress, which takes the live owner its references resolve in")
}
func (Progress) Of() Tag { return Tag{} }
func (Progress) WireType() runtime.TypeBinding {
	return runtime.TypeBinding{Schema: schema, Type: "Progress"}
}

// ExportJob writes Job as it travels: each callable in it becomes a binding of the owner, and the reference that names it takes its place.
func ExportJob(owner *live.Owner, v Job) (json.RawMessage, error) {
	if owner == nil {
		return nil, fmt.Errorf("Job: a live value is exported into an owner")
	}
	return owner.ExportValue(func(owner *live.Owner) (json.RawMessage, error) {
		wire := map[string]json.RawMessage{}
		var runMember json.RawMessage
		runMemberConverted, err := ExportRun(owner, v.Run)
		if err != nil {
			return nil, err
		}
		runMember = runMemberConverted
		wire["run"] = runMember
		data, err := runtime.MarshalObject([]string{"run"}, wire)
		if err != nil {
			return nil, err
		}
		if err := schema.ValidateExpressionRaw("Job", data); err != nil {
			return nil, err
		}
		return data, nil
	})
}

// ImportJob reads Job as it arrived: each reference in it becomes a typed proxy of the binding it names, so a handler is given native values.
func ImportJob(owner *live.Owner, raw json.RawMessage) (Job, error) {
	var value Job
	if owner == nil {
		return value, fmt.Errorf("Job: a live value is imported into an owner")
	}
	err := owner.ImportValue(func(owner *live.Owner) error {
		converted, err := func() (Job, error) {
			var value Job
			if err := schema.ValidateExpressionRaw("Job", raw); err != nil {
				return value, err
			}
			var wire map[string]json.RawMessage
			if err := json.Unmarshal(raw, &wire); err != nil {
				return value, err
			}
			if member, present := wire["run"]; present {
				var held Run
				heldConverted, err := ImportRun(owner, member)
				if err != nil {
					return value, err
				}
				held = heldConverted
				value.Run = held
			}
			return value, nil
		}()
		value = converted
		return err
	})
	if err != nil {
		var zero Job
		return zero, err
	}
	return value, nil
}

// ExportProgress writes Progress as it travels: each callable in it becomes a binding of the owner, and the reference that names it takes its place.
func ExportProgress(owner *live.Owner, v Progress) (json.RawMessage, error) {
	if owner == nil {
		return nil, fmt.Errorf("Progress: a live value is exported into an owner")
	}
	return owner.ExportValue(func(owner *live.Owner) (json.RawMessage, error) {
		wire := map[string]json.RawMessage{}
		var readMember json.RawMessage
		readMemberConverted, err := ExportRun(owner, v.Read)
		if err != nil {
			return nil, err
		}
		readMember = readMemberConverted
		wire["read"] = readMember
		data, err := runtime.MarshalObject([]string{"read"}, wire)
		if err != nil {
			return nil, err
		}
		if err := schema.ValidateExpressionRaw("Progress", data); err != nil {
			return nil, err
		}
		return data, nil
	})
}

// ImportProgress reads Progress as it arrived: each reference in it becomes a typed proxy of the binding it names, so a handler is given native values.
func ImportProgress(owner *live.Owner, raw json.RawMessage) (Progress, error) {
	var value Progress
	if owner == nil {
		return value, fmt.Errorf("Progress: a live value is imported into an owner")
	}
	err := owner.ImportValue(func(owner *live.Owner) error {
		converted, err := func() (Progress, error) {
			var value Progress
			if err := schema.ValidateExpressionRaw("Progress", raw); err != nil {
				return value, err
			}
			var wire map[string]json.RawMessage
			if err := json.Unmarshal(raw, &wire); err != nil {
				return value, err
			}
			if member, present := wire["read"]; present {
				var held Run
				heldConverted, err := ImportRun(owner, member)
				if err != nil {
					return value, err
				}
				held = heldConverted
				value.Read = held
			}
			return value, nil
		}()
		value = converted
		return err
	})
	if err != nil {
		var zero Progress
		return zero, err
	}
	return value, nil
}

// A value of it is one implementation, called across the seam; each is its own binding, with its own lifetime.
type Run = func(ctx context.Context, params int64) (int64, error)

// ContractRun is the declaration a reference to Run carries. It is nominal: a reference is usable exactly where this callable is expected.
const ContractRun = "second/Run"

// ExportRun makes a binding of a local Run and writes the reference that names it.
func ExportRun(owner *live.Owner, v Run) (json.RawMessage, error) {
	if owner == nil {
		return nil, fmt.Errorf("Run: a live value is exported into an owner")
	}
	if v == nil {
		return nil, fmt.Errorf("Run: no implementation to export")
	}
	return owner.ExportValue(func(owner *live.Owner) (json.RawMessage, error) {
		reference, err := owner.Export(ContractRun, WireDigest(), func(ctx context.Context, request json.RawMessage) (json.RawMessage, error) {
			owner := owner.Child()
			ctx = live.WithOwner(ctx, owner)
			if err := schema.ValidateExpressionRaw(MustTypeExpression("\"integer\""), request); err != nil {
				return nil, err
			}
			argument, err := func() (int64, error) {
				var value int64
				if err := schema.ValidateExpressionRaw(MustTypeExpression("\"integer\""), request); err != nil {
					return value, err
				}
				err := json.Unmarshal(request, &value)
				return value, err
			}()
			if err != nil {
				return nil, err
			}
			result, err := v(ctx, argument)
			if err != nil {
				return nil, err
			}
			data, err := runtime.MarshalJSON(result)
			if err == nil {
				err = schema.ValidateExpressionRaw(MustTypeExpression("\"integer\""), data)
			}
			if err != nil {
				return nil, err
			}
			return data, nil
		})
		if err != nil {
			return nil, err
		}
		return runtime.MarshalJSON(reference)
	})
}

// ImportRun is a Run that calls the binding a reference names.
func ImportRun(owner *live.Owner, raw json.RawMessage) (Run, error) {
	if owner == nil {
		return nil, fmt.Errorf("Run: a live value is imported into an owner")
	}
	reference, err := owner.Scope().Decode(raw)
	if err != nil {
		return nil, err
	}
	invoke, err := owner.Import(reference, ContractRun, WireDigest())
	if err != nil {
		return nil, err
	}
	return func(ctx context.Context, params int64) (int64, error) {
		var zero int64
		request, err := runtime.MarshalJSON(params)
		if err == nil {
			err = schema.ValidateExpressionRaw(MustTypeExpression("\"integer\""), request)
		}
		if err != nil {
			return zero, err
		}
		result, err := invoke(ctx, request)
		if err != nil {
			return zero, err
		}
		if err := schema.ValidateExpressionRaw(MustTypeExpression("\"integer\""), result); err != nil {
			return zero, err
		}
		answer, err := func() (int64, error) {
			var value int64
			if err := schema.ValidateExpressionRaw(MustTypeExpression("\"integer\""), result); err != nil {
				return value, err
			}
			err := json.Unmarshal(result, &value)
			return value, err
		}()
		if err != nil {
			return zero, err
		}
		return answer, nil
	}, nil
}

// AdapterJob composes declaration validation and conversion within the supplied invocation context.
func AdapterJob() runtime.ValueAdapter[Job] {
	binding := runtime.TypeBinding{Schema: schema, Type: "Job"}
	return runtime.ValueAdapter[Job]{
		Binding:      binding,
		NeedsContext: true,
		Export: func(ctx context.Context, value Job) (json.RawMessage, error) {
			if ctx == nil {
				return nil, fmt.Errorf("a live conversion requires an active owner")
			}
			owner, ok := live.OwnerOf(ctx)
			if !ok || owner == nil {
				return nil, fmt.Errorf("a live conversion requires an active owner")
			}
			raw, err := ExportJob(owner, value)
			if err == nil {
				err = binding.Schema.ValidateExpressionRaw(binding.Type, raw)
			}
			return raw, err
		},
		Import: func(ctx context.Context, raw json.RawMessage) (Job, error) {
			var zero Job
			if ctx == nil {
				return zero, fmt.Errorf("a live conversion requires an active owner")
			}
			owner, ok := live.OwnerOf(ctx)
			if !ok || owner == nil {
				return zero, fmt.Errorf("a live conversion requires an active owner")
			}
			if err := binding.Schema.ValidateExpressionRaw(binding.Type, raw); err != nil {
				return zero, err
			}
			return ImportJob(owner, raw)
		},
	}
}

// AdapterProgress composes declaration validation and conversion within the supplied invocation context.
func AdapterProgress() runtime.ValueAdapter[Progress] {
	binding := runtime.TypeBinding{Schema: schema, Type: "Progress"}
	return runtime.ValueAdapter[Progress]{
		Binding:      binding,
		NeedsContext: true,
		Export: func(ctx context.Context, value Progress) (json.RawMessage, error) {
			if ctx == nil {
				return nil, fmt.Errorf("a live conversion requires an active owner")
			}
			owner, ok := live.OwnerOf(ctx)
			if !ok || owner == nil {
				return nil, fmt.Errorf("a live conversion requires an active owner")
			}
			raw, err := ExportProgress(owner, value)
			if err == nil {
				err = binding.Schema.ValidateExpressionRaw(binding.Type, raw)
			}
			return raw, err
		},
		Import: func(ctx context.Context, raw json.RawMessage) (Progress, error) {
			var zero Progress
			if ctx == nil {
				return zero, fmt.Errorf("a live conversion requires an active owner")
			}
			owner, ok := live.OwnerOf(ctx)
			if !ok || owner == nil {
				return zero, fmt.Errorf("a live conversion requires an active owner")
			}
			if err := binding.Schema.ValidateExpressionRaw(binding.Type, raw); err != nil {
				return zero, err
			}
			return ImportProgress(owner, raw)
		},
	}
}

// AdapterRun composes declaration validation and conversion within the supplied invocation context.
func AdapterRun() runtime.ValueAdapter[Run] {
	binding := runtime.TypeBinding{Schema: schema, Type: "Run"}
	return runtime.ValueAdapter[Run]{
		Binding:      binding,
		NeedsContext: true,
		Export: func(ctx context.Context, value Run) (json.RawMessage, error) {
			if ctx == nil {
				return nil, fmt.Errorf("a live conversion requires an active owner")
			}
			owner, ok := live.OwnerOf(ctx)
			if !ok || owner == nil {
				return nil, fmt.Errorf("a live conversion requires an active owner")
			}
			raw, err := ExportRun(owner, value)
			if err == nil {
				err = binding.Schema.ValidateExpressionRaw(binding.Type, raw)
			}
			return raw, err
		},
		Import: func(ctx context.Context, raw json.RawMessage) (Run, error) {
			var zero Run
			if ctx == nil {
				return zero, fmt.Errorf("a live conversion requires an active owner")
			}
			owner, ok := live.OwnerOf(ctx)
			if !ok || owner == nil {
				return zero, fmt.Errorf("a live conversion requires an active owner")
			}
			if err := binding.Schema.ValidateExpressionRaw(binding.Type, raw); err != nil {
				return zero, err
			}
			return ImportRun(owner, raw)
		},
	}
}

type ServerMethods interface {
}
type ServerEvents interface {
}
type Server struct {
	Methods ServerMethods
	Events  ServerEvents
}
type ClientMethods interface {
}
type ClientEvents interface {
}
type Client struct {
	Methods ClientMethods
	Events  ClientEvents
}
type ServerModel func(Client) (Server, error)
type ClientModel func(Server) (Client, error)
