// Code generated by nightseam. DO NOT EDIT.
package carrierbinding

import (
	context "context"
	json "encoding/json"
	errors "errors"
	protocol "example.test/generated/api/go/carrier-protocol"
	probeprotocol "example.test/generated/api/go/probe-protocol"
	fmt "fmt"
	duplex "github.com/Bitspark/nightseam/duplex/go"
	runtime "github.com/Bitspark/nightseam/runtime/go"
	atomic "sync/atomic"
)

type serverMethods[SEnvelope, SHandle any] struct {
	wire        duplex.Wire
	environment runtime.AdapterContext
}
type serverEvents[SEnvelope, SHandle any] struct {
	wire        duplex.Wire
	environment runtime.AdapterContext
}

func accessServer[SEnvelope, SHandle any](wire duplex.Wire, environment runtime.AdapterContext) protocol.Server[SEnvelope, SHandle] {
	return protocol.Server[SEnvelope, SHandle]{Methods: &serverMethods[SEnvelope, SHandle]{wire: wire, environment: environment}, Events: &serverEvents[SEnvelope, SHandle]{wire: wire, environment: environment}}
}
func (c *serverMethods[SEnvelope, SHandle]) Attach(ctx context.Context, params protocol.AttachParams) (protocol.Attachment[SHandle], error) {
	var result protocol.Attachment[SHandle]
	if err := protocol.WireSchema().Bind(map[string]any{"S.Envelope": runtime.TypeArgument[SEnvelope](), "S.Handle": runtime.TypeArgument[SHandle]()}, nil).ValidateValue(protocol.MustTypeExpression("\"AttachParams\""), params); err != nil {
		return result, err
	}
	var raw json.RawMessage
	if err := runtime.CallWire(ctx, c.wire, []string{"attach"}, params, &raw, runtime.WireCallOptions{Observer: c.environment.Options.Observer, Family: "carrier", Propagator: c.environment.Options.Propagator, RequestTimeout: c.environment.Options.RequestTimeout}); err != nil {
		return result, err
	}
	if err := protocol.WireSchema().Bind(map[string]any{"S.Envelope": runtime.TypeArgument[SEnvelope](), "S.Handle": runtime.TypeArgument[SHandle]()}, nil).ValidateExpressionRaw(protocol.MustTypeExpression("\"Attachment\""), raw); err != nil {
		return result, err
	}
	if err := json.Unmarshal(raw, &result); err != nil {
		return result, err
	}
	return result, nil
}
func (c *serverMethods[SEnvelope, SHandle]) Relay(ctx context.Context, params protocol.Frame[SEnvelope]) (probeprotocol.Envelope, error) {
	var result probeprotocol.Envelope
	if err := protocol.WireSchema().Bind(map[string]any{"S.Envelope": runtime.TypeArgument[SEnvelope](), "S.Handle": runtime.TypeArgument[SHandle]()}, nil).ValidateValue(protocol.MustTypeExpression("\"Frame\""), params); err != nil {
		return result, err
	}
	var raw json.RawMessage
	if err := runtime.CallWire(ctx, c.wire, []string{"relay"}, params, &raw, runtime.WireCallOptions{Observer: c.environment.Options.Observer, Family: "carrier", Propagator: c.environment.Options.Propagator, RequestTimeout: c.environment.Options.RequestTimeout}); err != nil {
		return result, err
	}
	if err := protocol.WireSchema().Bind(map[string]any{"S.Envelope": runtime.TypeArgument[SEnvelope](), "S.Handle": runtime.TypeArgument[SHandle]()}, nil).ValidateExpressionRaw(protocol.MustTypeExpression("\"probe.Envelope\""), raw); err != nil {
		return result, err
	}
	if err := json.Unmarshal(raw, &result); err != nil {
		return result, err
	}
	return result, nil
}
func bindServer[SEnvelope, SHandle any](wire duplex.Wire, lookup func() protocol.Server[SEnvelope, SHandle], environment runtime.AdapterContext) error {
	var detach []func()
	complete := false
	defer func() {
		if !complete {
			for _, off := range detach {
				off()
			}
		}
	}()
	{
		handlers := runtime.WireHandlers{Observer: environment.Options.Observer, Family: "carrier"}
		handlers.Request = func(ctx context.Context, raw json.RawMessage) (any, error) {
			implementation := lookup()
			if implementation.Methods == nil {
				return nil, fmt.Errorf("model methods are required")
			}
			if err := protocol.WireSchema().Bind(map[string]any{"S.Envelope": runtime.TypeArgument[SEnvelope](), "S.Handle": runtime.TypeArgument[SHandle]()}, nil).ValidateExpressionRaw(protocol.MustTypeExpression("\"AttachParams\""), raw); err != nil {
				var public *runtime.PublicError
				if errors.As(err, &public) && public.Code == "contract_mismatch" {
					return nil, err
				}
				return nil, &runtime.PublicError{Code: "invalid_params", Message: err.Error()}
			}
			var params protocol.AttachParams
			if err := json.Unmarshal(raw, &params); err != nil {
				var public *runtime.PublicError
				if errors.As(err, &public) && public.Code == "contract_mismatch" {
					return nil, err
				}
				return nil, &runtime.PublicError{Code: "invalid_params", Message: err.Error()}
			}
			result, err := implementation.Methods.Attach(ctx, params)
			if err != nil {
				return nil, err
			}
			if err = protocol.WireSchema().Bind(map[string]any{"S.Envelope": runtime.TypeArgument[SEnvelope](), "S.Handle": runtime.TypeArgument[SHandle]()}, nil).ValidateValue(protocol.MustTypeExpression("\"Attachment\""), result); err != nil {
				return nil, err
			}
			return result, nil
		}
		if handlers.Request != nil || handlers.Event != nil {
			off, err := runtime.RegisterWire(wire, []string{"attach"}, handlers)
			if err != nil {
				return err
			}
			detach = append(detach, off)
		}
	}
	{
		handlers := runtime.WireHandlers{Observer: environment.Options.Observer, Family: "carrier"}
		handlers.Request = func(ctx context.Context, raw json.RawMessage) (any, error) {
			implementation := lookup()
			if implementation.Methods == nil {
				return nil, fmt.Errorf("model methods are required")
			}
			if err := protocol.WireSchema().Bind(map[string]any{"S.Envelope": runtime.TypeArgument[SEnvelope](), "S.Handle": runtime.TypeArgument[SHandle]()}, nil).ValidateExpressionRaw(protocol.MustTypeExpression("\"Frame\""), raw); err != nil {
				var public *runtime.PublicError
				if errors.As(err, &public) && public.Code == "contract_mismatch" {
					return nil, err
				}
				return nil, &runtime.PublicError{Code: "invalid_params", Message: err.Error()}
			}
			var params protocol.Frame[SEnvelope]
			if err := json.Unmarshal(raw, &params); err != nil {
				var public *runtime.PublicError
				if errors.As(err, &public) && public.Code == "contract_mismatch" {
					return nil, err
				}
				return nil, &runtime.PublicError{Code: "invalid_params", Message: err.Error()}
			}
			result, err := implementation.Methods.Relay(ctx, params)
			if err != nil {
				return nil, err
			}
			if err = protocol.WireSchema().Bind(map[string]any{"S.Envelope": runtime.TypeArgument[SEnvelope](), "S.Handle": runtime.TypeArgument[SHandle]()}, nil).ValidateValue(protocol.MustTypeExpression("\"probe.Envelope\""), result); err != nil {
				return nil, err
			}
			return result, nil
		}
		if handlers.Request != nil || handlers.Event != nil {
			off, err := runtime.RegisterWire(wire, []string{"relay"}, handlers)
			if err != nil {
				return err
			}
			detach = append(detach, off)
		}
	}
	complete = true
	return nil
}

type clientMethods[SEnvelope, SHandle any] struct {
	wire        duplex.Wire
	environment runtime.AdapterContext
}
type clientEvents[SEnvelope, SHandle any] struct {
	wire        duplex.Wire
	environment runtime.AdapterContext
}

func accessClient[SEnvelope, SHandle any](wire duplex.Wire, environment runtime.AdapterContext) protocol.Client[SEnvelope, SHandle] {
	return protocol.Client[SEnvelope, SHandle]{Methods: &clientMethods[SEnvelope, SHandle]{wire: wire, environment: environment}, Events: &clientEvents[SEnvelope, SHandle]{wire: wire, environment: environment}}
}
func (c *clientEvents[SEnvelope, SHandle]) FrameRelayed(ctx context.Context, data protocol.Frame[SEnvelope]) error {
	if err := protocol.WireSchema().Bind(map[string]any{"S.Envelope": runtime.TypeArgument[SEnvelope](), "S.Handle": runtime.TypeArgument[SHandle]()}, nil).ValidateValue(protocol.MustTypeExpression("\"Frame\""), data); err != nil {
		return err
	}
	return runtime.EmitWire(ctx, c.wire, []string{"frame.relayed"}, data, runtime.WireEmitOptions{Observer: c.environment.Options.Observer, Family: "carrier", Propagator: c.environment.Options.Propagator})
}
func bindClient[SEnvelope, SHandle any](wire duplex.Wire, lookup func() protocol.Client[SEnvelope, SHandle], environment runtime.AdapterContext) error {
	var detach []func()
	complete := false
	defer func() {
		if !complete {
			for _, off := range detach {
				off()
			}
		}
	}()
	{
		handlers := runtime.WireHandlers{Observer: environment.Options.Observer, Family: "carrier"}
		handlers.Event = func(ctx context.Context, raw json.RawMessage) error {
			implementation := lookup()
			if implementation.Events == nil {
				return nil
			}
			if err := protocol.WireSchema().Bind(map[string]any{"S.Envelope": runtime.TypeArgument[SEnvelope](), "S.Handle": runtime.TypeArgument[SHandle]()}, nil).ValidateExpressionRaw(protocol.MustTypeExpression("\"Frame\""), raw); err != nil {
				return err
			}
			var data protocol.Frame[SEnvelope]
			if err := json.Unmarshal(raw, &data); err != nil {
				return err
			}
			return implementation.Events.FrameRelayed(ctx, data)
		}
		if handlers.Request != nil || handlers.Event != nil {
			off, err := runtime.RegisterWire(wire, []string{"frame.relayed"}, handlers)
			if err != nil {
				return err
			}
			detach = append(detach, off)
		}
	}
	complete = true
	return nil
}
func normalizeContext[SEnvelope, SHandle any](environment runtime.AdapterContext) (runtime.AdapterContext, error) {
	if false && environment.ValueEnvironment == nil {
		return environment, fmt.Errorf("a context-dependent adapter requires a value environment")
	}
	return environment, nil
}

// ToWire binds one model factory and returns its access wire.
func ToWire[SEnvelope runtime.Of[STag], SHandle runtime.Of[STag], STag any](model protocol.ServerModel[SEnvelope, SHandle], environment runtime.AdapterContext) (duplex.Wire, error) {
	if model == nil {
		return nil, fmt.Errorf("model factory is required")
	}
	environment, err := normalizeContext[SEnvelope, SHandle](environment)
	if err != nil {
		return nil, err
	}
	identity, err := declarationIdentity[SEnvelope, SHandle]()
	if err != nil {
		return nil, err
	}
	options := environment.Options
	families := map[string]string{}
	for name, existing := range options.Families {
		families[name] = existing
	}
	families["6:attach"] = "carrier"
	families["5:relay"] = "carrier"
	families["13:frame.relayed"] = "carrier"
	options.Families = families
	access, binding, err := runtime.NewWirePair(options)
	if err != nil {
		return nil, err
	}
	complete := false
	defer func() {
		if !complete {
			_ = access.Close(duplex.CodeInternalError, "model construction failed")
		}
	}()
	if _, err := registerIdentity(binding, identity); err != nil {
		return nil, err
	}
	implementation, err := model(accessClient[SEnvelope, SHandle](binding, environment))
	if err != nil {
		return nil, err
	}
	if implementation.Methods == nil {
		return nil, fmt.Errorf("Server methods are required")
	}
	if err := bindServer[SEnvelope, SHandle](binding, func() protocol.Server[SEnvelope, SHandle] { return implementation }, environment); err != nil {
		return nil, err
	}
	complete = true
	return access, nil
}
func declarationIdentity[SEnvelope, SHandle any]() (runtime.DeclarationIdentity, error) {
	digest, err := protocol.WireSchema().Bind(map[string]any{"S.Envelope": runtime.TypeArgument[SEnvelope](), "S.Handle": runtime.TypeArgument[SHandle]()}, nil).DeclarationDigest()
	if err != nil {
		return runtime.DeclarationIdentity{}, err
	}
	return runtime.DeclarationIdentity{Path: "carrier", Digest: digest}, nil
}
func registerIdentity(wire duplex.Wire, identity runtime.DeclarationIdentity) (func(), error) {
	handler, err := runtime.IdentityHandler(identity)
	if err != nil {
		return nil, err
	}
	return runtime.HandleWire(wire, []string{runtime.IdentityMethod}, func(ctx context.Context, raw json.RawMessage) (any, error) { return handler(ctx, nil, raw) })
}

// PrepareFromWire registers receivers synchronously, before the wire is attached.
// Complete checks identity and returns a factory that may be bound once. Both steps
// must finish within environment.Options.RequestTimeout. Cleanup detaches this
// interpretation's registrations, including after success, and never closes the wire.
func PrepareFromWire[SEnvelope runtime.Of[STag], SHandle runtime.Of[STag], STag any](wire duplex.Wire, environment runtime.AdapterContext) (complete func(context.Context) (protocol.ServerModel[SEnvelope, SHandle], error), cleanup func(), err error) {
	if wire == nil {
		return nil, nil, fmt.Errorf("wire is required")
	}
	environment, err = normalizeContext[SEnvelope, SHandle](environment)
	if err != nil {
		return nil, nil, err
	}
	identity, err := declarationIdentity[SEnvelope, SHandle]()
	if err != nil {
		return nil, nil, err
	}
	preparation, err := runtime.PrepareIdentity(wire, identity, environment.Options)
	if err != nil {
		return nil, nil, err
	}
	cleanup = preparation.Close
	var implementation atomic.Pointer[protocol.Client[SEnvelope, SHandle]]
	lookup := func() protocol.Client[SEnvelope, SHandle] {
		if current := implementation.Load(); current != nil {
			return *current
		}
		return protocol.Client[SEnvelope, SHandle]{}
	}
	if err = bindClient[SEnvelope, SHandle](preparation.Wire(), lookup, environment); err != nil {
		cleanup()
		return nil, nil, err
	}
	var checking, bound atomic.Bool
	complete = func(ctx context.Context) (protocol.ServerModel[SEnvelope, SHandle], error) {
		if !checking.CompareAndSwap(false, true) {
			return nil, fmt.Errorf("identity completion is already started")
		}
		if err := preparation.Check(ctx); err != nil {
			cleanup()
			return nil, err
		}
		return func(value protocol.Client[SEnvelope, SHandle]) (protocol.Server[SEnvelope, SHandle], error) {
			if !bound.CompareAndSwap(false, true) {
				return protocol.Server[SEnvelope, SHandle]{}, fmt.Errorf("model factory is already bound")
			}
			implementation.Store(&value)
			if err := preparation.Ready(); err != nil {
				cleanup()
				return protocol.Server[SEnvelope, SHandle]{}, err
			}
			return accessServer[SEnvelope, SHandle](preparation.Wire(), environment), nil
		}, nil
	}
	return complete, cleanup, nil
}

// FromWire checks identity and returns a factory that may be bound once.
// Use PrepareFromWire before attachment when incoming delivery can begin immediately.
func FromWire[SEnvelope runtime.Of[STag], SHandle runtime.Of[STag], STag any](ctx context.Context, wire duplex.Wire, environment runtime.AdapterContext) (protocol.ServerModel[SEnvelope, SHandle], error) {
	complete, cleanup, err := PrepareFromWire[SEnvelope, SHandle](wire, environment)
	if err != nil {
		return nil, err
	}
	model, err := complete(ctx)
	if err != nil {
		cleanup()
		return nil, err
	}
	return model, nil
}

// RecordedEvent is the closed union of this side's outgoing event payloads.
type RecordedEvent[SEnvelope, SHandle any] interface{ recordedEvent(SEnvelope, SHandle) }
type RecordedFrameRelayed[SEnvelope, SHandle any] struct{ Data protocol.Frame[SEnvelope] }

func (RecordedFrameRelayed[SEnvelope, SHandle]) recordedEvent(SEnvelope, SHandle) {}

// Recorder records converted messages without retaining or rebinding their live values.
type Recorder[SEnvelope, SHandle any] struct {
	*duplex.RecordedWire
	events   protocol.ClientEvents[SEnvelope, SHandle]
	identity runtime.DeclarationIdentity
	options  runtime.Options
}

func (r *Recorder[SEnvelope, SHandle]) Append(ctx context.Context, event RecordedEvent[SEnvelope, SHandle]) error {
	switch value := event.(type) {
	case RecordedFrameRelayed[SEnvelope, SHandle]:
		return r.events.FrameRelayed(ctx, value.Data)
	case *RecordedFrameRelayed[SEnvelope, SHandle]:
		if value == nil {
			return fmt.Errorf("nil recorded event")
		}
		return r.events.FrameRelayed(ctx, value.Data)
	default:
		return fmt.Errorf("unknown or nil recorded event")
	}
}

// Follow checks the subscriber's declaration before registering any replay.
func (r *Recorder[SEnvelope, SHandle]) Follow(ctx context.Context, after uint64, target duplex.Wire) (*duplex.Follower, error) {
	if err := runtime.CheckIdentity(ctx, func(ctx context.Context, method string, params, result any) error {
		return runtime.CallWire(ctx, target, []string{method}, params, result, runtime.WireCallOptions{RequestTimeout: r.options.RequestTimeout, Observer: r.options.Observer, Propagator: r.options.Propagator})
	}, r.identity); err != nil {
		return nil, err
	}
	return r.RecordedWire.Follow(ctx, after, target)
}

// Record checks a prepared origin before exposing typed event append. Setup
// failure detaches this interpretation and leaves the borrowed target usable.
func Record[SEnvelope runtime.Of[STag], SHandle runtime.Of[STag], STag any](ctx context.Context, target duplex.Wire, log duplex.WireLog, options duplex.RecordOptions, environment runtime.AdapterContext) (*Recorder[SEnvelope, SHandle], error) {
	environment, err := normalizeContext[SEnvelope, SHandle](environment)
	if err != nil {
		return nil, err
	}
	identity, err := declarationIdentity[SEnvelope, SHandle]()
	if err != nil {
		return nil, err
	}
	preparation, err := runtime.PrepareIdentity(target, identity, environment.Options)
	if err != nil {
		return nil, err
	}
	if err := preparation.Check(ctx); err != nil {
		preparation.Close()
		return nil, err
	}
	if err := preparation.Ready(); err != nil {
		preparation.Close()
		return nil, err
	}
	onClose := options.OnClose
	options.OnClose = func(err error) {
		preparation.Close()
		if onClose != nil {
			onClose(err)
		}
	}
	wire, err := duplex.Record(ctx, preparation.Wire(), log, options)
	if err != nil {
		preparation.Close()
		return nil, err
	}
	return &Recorder[SEnvelope, SHandle]{RecordedWire: wire, events: accessClient[SEnvelope, SHandle](wire, environment).Events, identity: identity, options: environment.Options}, nil
}
