// Code generated by nightseam. DO NOT EDIT.
package relaybinding

import (
	context "context"
	json "encoding/json"
	protocol "example.test/generated/api/go/relay-protocol"
	fmt "fmt"
	duplex "github.com/Bitspark/nightseam/duplex/go"
	runtime "github.com/Bitspark/nightseam/runtime/go"
	http "net/http"
)

// Remote provides typed calls back to the connected client.
type Remote[SEnvelope, SHandle any] struct{ Peer *runtime.Peer }
type Handler[SEnvelope, SHandle any] interface {
	// Relay: Relays one message of the bound family.
	Relay(ctx context.Context, remote *Remote[SEnvelope, SHandle], params protocol.Carried[SEnvelope, SHandle]) (SEnvelope, error)
}

// install registers the family's methods on the options a peer is made with and labels its names with the family.
func install[SEnvelope, SHandle any](handler Handler[SEnvelope, SHandle], options *runtime.Options) error {
	if handler == nil {
		return fmt.Errorf("handler is required")
	}
	handlers := map[string]runtime.Handler{}
	for name, existing := range options.Handlers {
		handlers[name] = existing
	}
	if _, exists := handlers["relay"]; exists {
		return fmt.Errorf("duplicate handler %s", "relay")
	}
	handlers["relay"] = func(ctx context.Context, peer *runtime.Peer, raw json.RawMessage) (any, error) {
		var params protocol.Carried[SEnvelope, SHandle]
		if err := protocol.WireSchema().Bind(map[string]any{"S.Envelope": runtime.TypeArgument[SEnvelope](), "S.Handle": runtime.TypeArgument[SHandle]()}, nil).ValidateExpressionRaw(protocol.MustTypeExpression("\"Carried\""), raw); err != nil {
			return nil, &runtime.PublicError{Code: "invalid_params", Message: err.Error()}
		}
		if err := json.Unmarshal(raw, &params); err != nil {
			return nil, &runtime.PublicError{Code: "invalid_params", Message: err.Error()}
		}
		result, err := handler.Relay(ctx, &Remote[SEnvelope, SHandle]{Peer: peer}, params)
		if err != nil {
			return nil, err
		}
		if err = protocol.WireSchema().Bind(map[string]any{"S.Envelope": runtime.TypeArgument[SEnvelope](), "S.Handle": runtime.TypeArgument[SHandle]()}, nil).ValidateValue(protocol.MustTypeExpression("\"S.Envelope\""), result); err != nil {
			return nil, err
		}
		return result, nil
	}
	options.Handlers = handlers
	families := map[string]string{}
	for name, existing := range options.Families {
		families[name] = existing
	}
	families["relay"] = "relay"
	options.Families = families
	return nil
}

// NewHandler serves the family at a WebSocket endpoint; it requires explicit authentication and origin policy through options.
func NewHandler[SEnvelope runtime.Of[STag], SHandle runtime.Of[STag], STag any](handler Handler[SEnvelope, SHandle], options runtime.ServerOptions) (http.Handler, error) {
	if err := install[SEnvelope, SHandle](handler, &options.Options); err != nil {
		return nil, err
	}
	return runtime.NewHandler(options)
}

// Serve serves the family over a connection of the seam — a tunnel channel, a pipe, an accepted socket — as the server side of it; the peer is the caller's to close.
func Serve[SEnvelope runtime.Of[STag], SHandle runtime.Of[STag], STag any](ctx context.Context, conn duplex.Conn, options runtime.Options, handler Handler[SEnvelope, SHandle]) (*runtime.Peer, error) {
	if err := install[SEnvelope, SHandle](handler, &options); err != nil {
		return nil, err
	}
	return runtime.NewPeer(ctx, conn, runtime.ServerRole, options)
}
