// Code generated by nightseam. DO NOT EDIT.
package functionsbinding

import (
	context "context"
	json "encoding/json"
	protocol "example.test/generated/api/go/functions-protocol"
	fmt "fmt"
	duplex "github.com/Bitspark/nightseam/duplex/go"
	runtime "github.com/Bitspark/nightseam/runtime/go"
	atomic "sync/atomic"
)

type serverMethods struct {
	wire        duplex.Wire
	environment runtime.AdapterContext
}
type serverEvents struct {
	wire        duplex.Wire
	environment runtime.AdapterContext
}

func accessServer(wire duplex.Wire, environment runtime.AdapterContext) protocol.Server {
	return protocol.Server{Methods: &serverMethods{wire: wire, environment: environment}, Events: &serverEvents{wire: wire, environment: environment}}
}
func bindServer(wire duplex.Wire, lookup func() protocol.Server, environment runtime.AdapterContext) error {
	var detach []func()
	complete := false
	defer func() {
		if !complete {
			for _, off := range detach {
				off()
			}
		}
	}()
	complete = true
	return nil
}

type clientMethods struct {
	wire        duplex.Wire
	environment runtime.AdapterContext
}
type clientEvents struct {
	wire        duplex.Wire
	environment runtime.AdapterContext
}

func accessClient(wire duplex.Wire, environment runtime.AdapterContext) protocol.Client {
	return protocol.Client{Methods: &clientMethods{wire: wire, environment: environment}, Events: &clientEvents{wire: wire, environment: environment}}
}
func bindClient(wire duplex.Wire, lookup func() protocol.Client, environment runtime.AdapterContext) error {
	var detach []func()
	complete := false
	defer func() {
		if !complete {
			for _, off := range detach {
				off()
			}
		}
	}()
	complete = true
	return nil
}
func normalizeContext(environment runtime.AdapterContext) (runtime.AdapterContext, error) {
	if (true) && environment.ValueEnvironment == nil {
		return environment, fmt.Errorf("a context-dependent adapter requires a value environment")
	}
	return environment, nil
}

// ToWire binds one model factory and returns its access wire.
func ToWire(model protocol.ServerModel, environment runtime.AdapterContext) (duplex.Wire, error) {
	if model == nil {
		return nil, fmt.Errorf("model factory is required")
	}
	environment, err := normalizeContext(environment)
	if err != nil {
		return nil, err
	}
	identity, err := declarationIdentity()
	if err != nil {
		return nil, err
	}
	options := environment.Options
	families := map[string]string{}
	for name, existing := range options.Families {
		families[name] = existing
	}
	options.Families = families
	access, binding, err := runtime.NewWirePair(options)
	if err != nil {
		return nil, err
	}
	complete := false
	defer func() {
		if !complete {
			_ = access.Close(duplex.CodeInternalError, "model construction failed")
		}
	}()
	if _, err := registerIdentity(binding, identity); err != nil {
		return nil, err
	}
	implementation, err := model(accessClient(binding, environment))
	if err != nil {
		return nil, err
	}
	if err := bindServer(binding, func() protocol.Server { return implementation }, environment); err != nil {
		return nil, err
	}
	complete = true
	return access, nil
}
func declarationIdentity() (runtime.DeclarationIdentity, error) {
	digest, err := protocol.WireSchema().DeclarationDigest()
	if err != nil {
		return runtime.DeclarationIdentity{}, err
	}
	return runtime.DeclarationIdentity{Path: "functions", Digest: digest}, nil
}
func registerIdentity(wire duplex.Wire, identity runtime.DeclarationIdentity) (func(), error) {
	handler, err := runtime.IdentityHandler(identity)
	if err != nil {
		return nil, err
	}
	return runtime.HandleWire(wire, []string{runtime.IdentityMethod}, func(ctx context.Context, raw json.RawMessage) (any, error) { return handler(ctx, nil, raw) })
}

// PrepareFromWire registers receivers synchronously, before the wire is attached.
// Complete checks identity and returns a factory that may be bound once. Both steps
// must finish within environment.Options.RequestTimeout. Cleanup detaches this
// interpretation's registrations, including after success, and never closes the wire.
func PrepareFromWire(wire duplex.Wire, environment runtime.AdapterContext) (complete func(context.Context) (protocol.ServerModel, error), cleanup func(), err error) {
	if wire == nil {
		return nil, nil, fmt.Errorf("wire is required")
	}
	environment, err = normalizeContext(environment)
	if err != nil {
		return nil, nil, err
	}
	identity, err := declarationIdentity()
	if err != nil {
		return nil, nil, err
	}
	preparation, err := runtime.PrepareIdentity(wire, identity, environment.Options)
	if err != nil {
		return nil, nil, err
	}
	cleanup = preparation.Close
	var implementation atomic.Pointer[protocol.Client]
	lookup := func() protocol.Client {
		if current := implementation.Load(); current != nil {
			return *current
		}
		return protocol.Client{}
	}
	if err = bindClient(preparation.Wire(), lookup, environment); err != nil {
		cleanup()
		return nil, nil, err
	}
	var checking, bound atomic.Bool
	complete = func(ctx context.Context) (protocol.ServerModel, error) {
		if !checking.CompareAndSwap(false, true) {
			return nil, fmt.Errorf("identity completion is already started")
		}
		if err := preparation.Check(ctx); err != nil {
			cleanup()
			return nil, err
		}
		return func(value protocol.Client) (protocol.Server, error) {
			if !bound.CompareAndSwap(false, true) {
				return protocol.Server{}, fmt.Errorf("model factory is already bound")
			}
			implementation.Store(&value)
			if err := preparation.Ready(); err != nil {
				cleanup()
				return protocol.Server{}, err
			}
			return accessServer(preparation.Wire(), environment), nil
		}, nil
	}
	return complete, cleanup, nil
}

// FromWire checks identity and returns a factory that may be bound once.
// Use PrepareFromWire before attachment when incoming delivery can begin immediately.
func FromWire(ctx context.Context, wire duplex.Wire, environment runtime.AdapterContext) (protocol.ServerModel, error) {
	complete, cleanup, err := PrepareFromWire(wire, environment)
	if err != nil {
		return nil, err
	}
	model, err := complete(ctx)
	if err != nil {
		cleanup()
		return nil, err
	}
	return model, nil
}

// RecordedEvent is the closed union of this side's outgoing event payloads.
type RecordedEvent interface{ recordedEvent() }

// Recorder records converted messages without retaining or rebinding their live values.
type Recorder struct {
	*duplex.RecordedWire
	events   protocol.ClientEvents
	identity runtime.DeclarationIdentity
	options  runtime.Options
}

func (r *Recorder) Append(ctx context.Context, event RecordedEvent) error {
	return fmt.Errorf("this side declares no outgoing events")
}

// Follow checks the subscriber's declaration before registering any replay.
func (r *Recorder) Follow(ctx context.Context, after uint64, target duplex.Wire) (*duplex.Follower, error) {
	if err := runtime.CheckIdentity(ctx, func(ctx context.Context, method string, params, result any) error {
		return runtime.CallWire(ctx, target, []string{method}, params, result, runtime.WireCallOptions{RequestTimeout: r.options.RequestTimeout, Observer: r.options.Observer, Propagator: r.options.Propagator})
	}, r.identity); err != nil {
		return nil, err
	}
	return r.RecordedWire.Follow(ctx, after, target)
}

// Record checks a prepared origin before exposing typed event append. Setup
// failure detaches this interpretation and leaves the borrowed target usable.
func Record(ctx context.Context, target duplex.Wire, log duplex.WireLog, options duplex.RecordOptions, environment runtime.AdapterContext) (*Recorder, error) {
	environment, err := normalizeContext(environment)
	if err != nil {
		return nil, err
	}
	identity, err := declarationIdentity()
	if err != nil {
		return nil, err
	}
	preparation, err := runtime.PrepareIdentity(target, identity, environment.Options)
	if err != nil {
		return nil, err
	}
	if err := preparation.Check(ctx); err != nil {
		preparation.Close()
		return nil, err
	}
	if err := preparation.Ready(); err != nil {
		preparation.Close()
		return nil, err
	}
	onClose := options.OnClose
	options.OnClose = func(err error) {
		preparation.Close()
		if onClose != nil {
			onClose(err)
		}
	}
	wire, err := duplex.Record(ctx, preparation.Wire(), log, options)
	if err != nil {
		preparation.Close()
		return nil, err
	}
	return &Recorder{RecordedWire: wire, events: accessClient(wire, environment).Events, identity: identity, options: environment.Options}, nil
}
