// Code generated by nightseam. DO NOT EDIT.
import { DuplexPeer, DuplexError, type PeerOptions, type CallOptions, type EmitOptions, type RequestContext, type EventContext, type FrameConnection, type WebSocketLike } from "@nightseam/runtime";
import { validateWire } from "@example/ledger-client/types";
import type * as Protocol from "@example/ledger-client/types";
export * from "@example/ledger-client/types";
export { DuplexError };
/** Typed handlers for the declaration's server side. */
export interface Handler {
}
/** Client-originated event listeners installed before the connection reads its first frame. */
export interface Events {
}
/** Typed reverse calls and events for one connected client. */
export class Remote {
  readonly peer: DuplexPeer;
  constructor(peer: DuplexPeer) {
    this.peer = peer;
  }
  close(): void { this.peer.close(); }
}
/** Installs the typed binding before a host-configured peer starts reading. An existing live scope is preserved. */
export function install(peer: DuplexPeer, handler: Handler, events: Events = {}): Remote {
  if (!handler) throw new Error('handler is required');
  const remote = new Remote(peer);
  return remote;
}
/** Serves an externally authenticated accepted connection. The returned peer is the caller's to close. */
export async function serve(connection: FrameConnection | WebSocketLike, options: PeerOptions, handler: Handler, events: Events = {}): Promise<DuplexPeer> {
  const peer = new DuplexPeer({ ...{ ...options, families: { ...options.families } }, role: 'server' });
  try { install(peer, handler, events); await peer.attach(connection); return peer; } catch (error) { peer.close(); throw error; }
}
