// Code generated by nightseam. DO NOT EDIT.
package probeprotocol

import (
	json "encoding/json"
	errors "errors"
	runtime "github.com/Bitspark/nightseam/runtime/go"
)

// Tag is this family, as a type: what every record and enum of the package returns from Of, and what an entry point of a package generic in a family holds its type arguments to.
type Tag struct{}

// Envelope: One message of the nightseam.duplex/1 profile: the members the peer acts on, and nothing else.
type Envelope struct {
	Version     int64                               `json:"version"`
	Kind        string                              `json:"kind"`
	ID          runtime.Optional[string]            `json:"id,omitzero"`
	Method      runtime.Optional[string]            `json:"method,omitzero"`
	Params      runtime.Optional[any]               `json:"params,omitzero"`
	Result      runtime.Optional[any]               `json:"result,omitzero"`
	Error       runtime.Optional[any]               `json:"error,omitzero"`
	Event       runtime.Optional[string]            `json:"event,omitzero"`
	Data        runtime.Optional[any]               `json:"data,omitzero"`
	Traceparent runtime.Optional[string]            `json:"traceparent,omitzero"`
	Tracestate  runtime.Optional[string]            `json:"tracestate,omitzero"`
	Meta        runtime.Optional[map[string]string] `json:"meta,omitzero"`
}

func (v Envelope) MarshalJSON() ([]byte, error) {
	type wire Envelope
	data, err := json.Marshal(wire(v))
	if err != nil {
		return nil, err
	}
	if err = ValidateRaw("Envelope", data); err != nil {
		return nil, err
	}
	return data, nil
}
func (v *Envelope) UnmarshalJSON(data []byte) error {
	if err := ValidateRaw("Envelope", data); err != nil {
		return err
	}
	type wire Envelope
	var decoded wire
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*v = Envelope(decoded)
	return nil
}
func (Envelope) Of() Tag { return Tag{} }

// Handle: A reference to a channel on the connection that carries the message holding it.
type Handle struct {
	Channel int64 `json:"channel"`
}

func (v Handle) MarshalJSON() ([]byte, error) {
	type wire Handle
	data, err := json.Marshal(wire(v))
	if err != nil {
		return nil, err
	}
	if err = ValidateRaw("Handle", data); err != nil {
		return nil, err
	}
	return data, nil
}
func (v *Handle) UnmarshalJSON(data []byte) error {
	if err := ValidateRaw("Handle", data); err != nil {
		return err
	}
	type wire Handle
	var decoded wire
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*v = Handle(decoded)
	return nil
}
func (Handle) Of() Tag { return Tag{} }

// Payload: What a probe carries: some text, and how often it has been seen.
type Payload struct {
	Text  string `json:"text"`
	Count int64  `json:"count"`
}

func (v Payload) MarshalJSON() ([]byte, error) {
	type wire Payload
	data, err := json.Marshal(wire(v))
	if err != nil {
		return nil, err
	}
	if err = ValidateRaw("Payload", data); err != nil {
		return nil, err
	}
	return data, nil
}
func (v *Payload) UnmarshalJSON(data []byte) error {
	if err := ValidateRaw("Payload", data); err != nil {
		return err
	}
	type wire Payload
	var decoded wire
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*v = Payload(decoded)
	return nil
}
func (Payload) Of() Tag { return Tag{} }

// The public errors of the family: what a handler returns, as the Code of a *runtime.PublicError, and a caller tells apart with IsError.
const (
	// ErrorDenied: The caller is denied.
	ErrorDenied = "denied"
)

// Errors is every public error code the family declares.
var Errors = []string{ErrorDenied}

// IsError reports whether an error is, or wraps, the family's public error of the code.
func IsError(err error, code string) bool {
	var public *runtime.PublicError
	return errors.As(err, &public) && public.Code == code
}
