// Code generated by nightseam. DO NOT EDIT.
package probeprotocol

import (
	context "context"
	json "encoding/json"
	errors "errors"
	fmt "fmt"
	live "github.com/Bitspark/nightseam/live/go"
	runtime "github.com/Bitspark/nightseam/runtime/go"
)

// Tag is this family, as a type: what every record and enum of the package returns from Of, and what an entry point of a package generic in a family holds its type arguments to.
type Tag struct{}

// Envelope: One message of the nightseam.duplex/1 profile: the members the peer acts on, and nothing else.
type Envelope struct {
	Version     int64                               `json:"version"`
	Kind        string                              `json:"kind"`
	ID          runtime.Optional[string]            `json:"id,omitzero"`
	Method      runtime.Optional[string]            `json:"method,omitzero"`
	Params      runtime.Optional[any]               `json:"params,omitzero"`
	Result      runtime.Optional[any]               `json:"result,omitzero"`
	Error       runtime.Optional[any]               `json:"error,omitzero"`
	Event       runtime.Optional[string]            `json:"event,omitzero"`
	Data        runtime.Optional[any]               `json:"data,omitzero"`
	Traceparent runtime.Optional[string]            `json:"traceparent,omitzero"`
	Tracestate  runtime.Optional[string]            `json:"tracestate,omitzero"`
	Meta        runtime.Optional[map[string]string] `json:"meta,omitzero"`
}

func (v Envelope) MarshalJSON() ([]byte, error) {
	type wire Envelope
	data, err := runtime.MarshalJSON(wire(v))
	if err != nil {
		return nil, err
	}
	if err = schema.ValidateExpressionRaw("Envelope", data); err != nil {
		return nil, err
	}
	return data, nil
}
func (v *Envelope) UnmarshalJSON(data []byte) error {
	if err := schema.ValidateExpressionRaw("Envelope", data); err != nil {
		return err
	}
	type wire Envelope
	var decoded wire
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*v = Envelope(decoded)
	return nil
}
func (Envelope) Of() Tag { return Tag{} }
func (Envelope) WireType() runtime.TypeBinding {
	return runtime.TypeBinding{Schema: schema, Type: "Envelope"}
}

// Handle: A reference to a channel on the connection that carries the message holding it.
type Handle struct {
	Channel int64 `json:"channel"`
}

func (v Handle) MarshalJSON() ([]byte, error) {
	type wire Handle
	data, err := runtime.MarshalJSON(wire(v))
	if err != nil {
		return nil, err
	}
	if err = schema.ValidateExpressionRaw("Handle", data); err != nil {
		return nil, err
	}
	return data, nil
}
func (v *Handle) UnmarshalJSON(data []byte) error {
	if err := schema.ValidateExpressionRaw("Handle", data); err != nil {
		return err
	}
	type wire Handle
	var decoded wire
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*v = Handle(decoded)
	return nil
}
func (Handle) Of() Tag { return Tag{} }
func (Handle) WireType() runtime.TypeBinding {
	return runtime.TypeBinding{Schema: schema, Type: "Handle"}
}

// Payload: What a probe carries: some text, and how often it has been seen.
type Payload struct {
	Text  string `json:"text"`
	Count int64  `json:"count"`
}

func (v Payload) MarshalJSON() ([]byte, error) {
	type wire Payload
	data, err := runtime.MarshalJSON(wire(v))
	if err != nil {
		return nil, err
	}
	if err = schema.ValidateExpressionRaw("Payload", data); err != nil {
		return nil, err
	}
	return data, nil
}
func (v *Payload) UnmarshalJSON(data []byte) error {
	if err := schema.ValidateExpressionRaw("Payload", data); err != nil {
		return err
	}
	type wire Payload
	var decoded wire
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*v = Payload(decoded)
	return nil
}
func (Payload) Of() Tag { return Tag{} }
func (Payload) WireType() runtime.TypeBinding {
	return runtime.TypeBinding{Schema: schema, Type: "Payload"}
}

// Subscription: What watch answers: a record of callables the client calls back, held apart from the call that returned it.
type Subscription struct {
	Stop Stop `json:"stop"`
}

// MarshalJSON refuses: Subscription carries a callable, and a live value has no encoding apart from the owner its bindings belong to.
func (v Subscription) MarshalJSON() ([]byte, error) {
	return nil, fmt.Errorf("Subscription carries a callable; write it with ExportSubscription, which takes the live owner its bindings are made in")
}

// UnmarshalJSON refuses for the same reason: a reference resolves in a owner or nowhere.
func (v *Subscription) UnmarshalJSON(data []byte) error {
	return fmt.Errorf("Subscription carries a callable; read it with ImportSubscription, which takes the live owner its references resolve in")
}
func (Subscription) Of() Tag { return Tag{} }
func (Subscription) WireType() runtime.TypeBinding {
	return runtime.TypeBinding{Schema: schema, Type: "Subscription"}
}

// Watch: A callable supplied as an argument, beside ordinary data.
type Watch struct {
	Label   string  `json:"label"`
	Watcher Watcher `json:"watcher"`
}

// MarshalJSON refuses: Watch carries a callable, and a live value has no encoding apart from the owner its bindings belong to.
func (v Watch) MarshalJSON() ([]byte, error) {
	return nil, fmt.Errorf("Watch carries a callable; write it with ExportWatch, which takes the live owner its bindings are made in")
}

// UnmarshalJSON refuses for the same reason: a reference resolves in a owner or nowhere.
func (v *Watch) UnmarshalJSON(data []byte) error {
	return fmt.Errorf("Watch carries a callable; read it with ImportWatch, which takes the live owner its references resolve in")
}
func (Watch) Of() Tag { return Tag{} }
func (Watch) WireType() runtime.TypeBinding {
	return runtime.TypeBinding{Schema: schema, Type: "Watch"}
}

// Watcher: An interface, which is a record of callable members; each member is its own binding, with its own lifetime.
type Watcher struct {
	Notice Notice `json:"notice"`
}

// MarshalJSON refuses: Watcher carries a callable, and a live value has no encoding apart from the owner its bindings belong to.
func (v Watcher) MarshalJSON() ([]byte, error) {
	return nil, fmt.Errorf("Watcher carries a callable; write it with ExportWatcher, which takes the live owner its bindings are made in")
}

// UnmarshalJSON refuses for the same reason: a reference resolves in a owner or nowhere.
func (v *Watcher) UnmarshalJSON(data []byte) error {
	return fmt.Errorf("Watcher carries a callable; read it with ImportWatcher, which takes the live owner its references resolve in")
}
func (Watcher) Of() Tag { return Tag{} }
func (Watcher) WireType() runtime.TypeBinding {
	return runtime.TypeBinding{Schema: schema, Type: "Watcher"}
}

// Notice: Told about a payload the server saw. The client implements it and hands it over; the server calls it back across the seam.
// A value of it is one implementation, called across the seam; each is its own binding, with its own lifetime.
type Notice = func(ctx context.Context, params Payload) error

// ContractNotice is the declaration a reference to Notice carries. It is nominal: a reference is usable exactly where this callable is expected.
const ContractNotice = "probe/Notice"

// ExportNotice makes a binding of a local Notice and writes the reference that names it.
func ExportNotice(owner *live.Owner, v Notice) (json.RawMessage, error) {
	if owner == nil {
		return nil, fmt.Errorf("Notice: a live value is exported into an owner")
	}
	if v == nil {
		return nil, fmt.Errorf("Notice: no implementation to export")
	}
	return owner.ExportValue(func(owner *live.Owner) (json.RawMessage, error) {
		reference, err := owner.Export(ContractNotice, func(ctx context.Context, request json.RawMessage) (json.RawMessage, error) {
			owner := owner.Child()
			ctx = live.WithOwner(ctx, owner)
			if err := schema.ValidateExpressionRaw(MustTypeExpression("\"Payload\""), request); err != nil {
				return nil, err
			}
			argument, err := func() (Payload, error) {
				var value Payload
				if err := schema.ValidateExpressionRaw(MustTypeExpression("\"Payload\""), request); err != nil {
					return value, err
				}
				err := json.Unmarshal(request, &value)
				return value, err
			}()
			if err != nil {
				return nil, err
			}
			return nil, v(ctx, argument)
		})
		if err != nil {
			return nil, err
		}
		return runtime.MarshalJSON(reference)
	})
}

// ImportNotice is a Notice that calls the binding a reference names.
func ImportNotice(owner *live.Owner, raw json.RawMessage) (Notice, error) {
	if owner == nil {
		return nil, fmt.Errorf("Notice: a live value is imported into an owner")
	}
	reference, err := owner.Scope().Decode(raw)
	if err != nil {
		return nil, err
	}
	invoke, err := owner.Import(reference, ContractNotice)
	if err != nil {
		return nil, err
	}
	return func(ctx context.Context, params Payload) error {
		request, err := runtime.MarshalJSON(params)
		if err == nil {
			err = schema.ValidateExpressionRaw(MustTypeExpression("\"Payload\""), request)
		}
		if err != nil {
			return err
		}
		result, err := invoke(ctx, request)
		if err != nil {
			return err
		}
		_ = result
		return nil
	}, nil
}

// Stop: Asks the server to stop sending notices. Releasing the reference to it is not this, and cancelling the call that returned it is neither.
// A value of it is one implementation, called across the seam; each is its own binding, with its own lifetime.
type Stop = func(ctx context.Context) error

// ContractStop is the declaration a reference to Stop carries. It is nominal: a reference is usable exactly where this callable is expected.
const ContractStop = "probe/Stop"

// ExportStop makes a binding of a local Stop and writes the reference that names it.
func ExportStop(owner *live.Owner, v Stop) (json.RawMessage, error) {
	if owner == nil {
		return nil, fmt.Errorf("Stop: a live value is exported into an owner")
	}
	if v == nil {
		return nil, fmt.Errorf("Stop: no implementation to export")
	}
	return owner.ExportValue(func(owner *live.Owner) (json.RawMessage, error) {
		reference, err := owner.Export(ContractStop, func(ctx context.Context, request json.RawMessage) (json.RawMessage, error) {
			owner := owner.Child()
			ctx = live.WithOwner(ctx, owner)
			return nil, v(ctx)
		})
		if err != nil {
			return nil, err
		}
		return runtime.MarshalJSON(reference)
	})
}

// ImportStop is a Stop that calls the binding a reference names.
func ImportStop(owner *live.Owner, raw json.RawMessage) (Stop, error) {
	if owner == nil {
		return nil, fmt.Errorf("Stop: a live value is imported into an owner")
	}
	reference, err := owner.Scope().Decode(raw)
	if err != nil {
		return nil, err
	}
	invoke, err := owner.Import(reference, ContractStop)
	if err != nil {
		return nil, err
	}
	return func(ctx context.Context) error {
		result, err := invoke(ctx, nil)
		if err != nil {
			return err
		}
		_ = result
		return nil
	}, nil
}

// ExportSubscription writes Subscription as it travels: each callable in it becomes a binding of the owner, and the reference that names it takes its place.
func ExportSubscription(owner *live.Owner, v Subscription) (json.RawMessage, error) {
	if owner == nil {
		return nil, fmt.Errorf("Subscription: a live value is exported into an owner")
	}
	return owner.ExportValue(func(owner *live.Owner) (json.RawMessage, error) {
		wire := map[string]json.RawMessage{}
		var stopMember json.RawMessage
		stopMemberConverted, err := ExportStop(owner, v.Stop)
		if err != nil {
			return nil, err
		}
		stopMember = stopMemberConverted
		wire["stop"] = stopMember
		data, err := runtime.MarshalObject([]string{"stop"}, wire)
		if err != nil {
			return nil, err
		}
		if err := schema.ValidateExpressionRaw("Subscription", data); err != nil {
			return nil, err
		}
		return data, nil
	})
}

// ImportSubscription reads Subscription as it arrived: each reference in it becomes a typed proxy of the binding it names, so a handler is given native values.
func ImportSubscription(owner *live.Owner, raw json.RawMessage) (Subscription, error) {
	var value Subscription
	if owner == nil {
		return value, fmt.Errorf("Subscription: a live value is imported into an owner")
	}
	err := owner.ImportValue(func(owner *live.Owner) error {
		converted, err := func() (Subscription, error) {
			var value Subscription
			if err := schema.ValidateExpressionRaw("Subscription", raw); err != nil {
				return value, err
			}
			var wire map[string]json.RawMessage
			if err := json.Unmarshal(raw, &wire); err != nil {
				return value, err
			}
			if member, present := wire["stop"]; present {
				var held Stop
				heldConverted, err := ImportStop(owner, member)
				if err != nil {
					return value, err
				}
				held = heldConverted
				value.Stop = held
			}
			return value, nil
		}()
		value = converted
		return err
	})
	if err != nil {
		var zero Subscription
		return zero, err
	}
	return value, nil
}

// ExportWatch writes Watch as it travels: each callable in it becomes a binding of the owner, and the reference that names it takes its place.
func ExportWatch(owner *live.Owner, v Watch) (json.RawMessage, error) {
	if owner == nil {
		return nil, fmt.Errorf("Watch: a live value is exported into an owner")
	}
	return owner.ExportValue(func(owner *live.Owner) (json.RawMessage, error) {
		wire := map[string]json.RawMessage{}
		var labelMember json.RawMessage
		labelMemberConverted, err := runtime.MarshalJSON(v.Label)
		if err != nil {
			return nil, err
		}
		labelMember = labelMemberConverted
		wire["label"] = labelMember
		var watcherMember json.RawMessage
		watcherMemberConverted, err := ExportWatcher(owner, v.Watcher)
		if err != nil {
			return nil, err
		}
		watcherMember = watcherMemberConverted
		wire["watcher"] = watcherMember
		data, err := runtime.MarshalObject([]string{"label", "watcher"}, wire)
		if err != nil {
			return nil, err
		}
		if err := schema.ValidateExpressionRaw("Watch", data); err != nil {
			return nil, err
		}
		return data, nil
	})
}

// ImportWatch reads Watch as it arrived: each reference in it becomes a typed proxy of the binding it names, so a handler is given native values.
func ImportWatch(owner *live.Owner, raw json.RawMessage) (Watch, error) {
	var value Watch
	if owner == nil {
		return value, fmt.Errorf("Watch: a live value is imported into an owner")
	}
	err := owner.ImportValue(func(owner *live.Owner) error {
		converted, err := func() (Watch, error) {
			var value Watch
			if err := schema.ValidateExpressionRaw("Watch", raw); err != nil {
				return value, err
			}
			var wire map[string]json.RawMessage
			if err := json.Unmarshal(raw, &wire); err != nil {
				return value, err
			}
			if member, present := wire["label"]; present {
				var held string
				var heldConverted string
				if err := json.Unmarshal(member, &heldConverted); err != nil {
					return value, err
				}
				held = heldConverted
				value.Label = held
			}
			if member, present := wire["watcher"]; present {
				var held Watcher
				heldConverted, err := ImportWatcher(owner, member)
				if err != nil {
					return value, err
				}
				held = heldConverted
				value.Watcher = held
			}
			return value, nil
		}()
		value = converted
		return err
	})
	if err != nil {
		var zero Watch
		return zero, err
	}
	return value, nil
}

// ExportWatcher writes Watcher as it travels: each callable in it becomes a binding of the owner, and the reference that names it takes its place.
func ExportWatcher(owner *live.Owner, v Watcher) (json.RawMessage, error) {
	if owner == nil {
		return nil, fmt.Errorf("Watcher: a live value is exported into an owner")
	}
	return owner.ExportValue(func(owner *live.Owner) (json.RawMessage, error) {
		wire := map[string]json.RawMessage{}
		var noticeMember json.RawMessage
		noticeMemberConverted, err := ExportNotice(owner, v.Notice)
		if err != nil {
			return nil, err
		}
		noticeMember = noticeMemberConverted
		wire["notice"] = noticeMember
		data, err := runtime.MarshalObject([]string{"notice"}, wire)
		if err != nil {
			return nil, err
		}
		if err := schema.ValidateExpressionRaw("Watcher", data); err != nil {
			return nil, err
		}
		return data, nil
	})
}

// ImportWatcher reads Watcher as it arrived: each reference in it becomes a typed proxy of the binding it names, so a handler is given native values.
func ImportWatcher(owner *live.Owner, raw json.RawMessage) (Watcher, error) {
	var value Watcher
	if owner == nil {
		return value, fmt.Errorf("Watcher: a live value is imported into an owner")
	}
	err := owner.ImportValue(func(owner *live.Owner) error {
		converted, err := func() (Watcher, error) {
			var value Watcher
			if err := schema.ValidateExpressionRaw("Watcher", raw); err != nil {
				return value, err
			}
			var wire map[string]json.RawMessage
			if err := json.Unmarshal(raw, &wire); err != nil {
				return value, err
			}
			if member, present := wire["notice"]; present {
				var held Notice
				heldConverted, err := ImportNotice(owner, member)
				if err != nil {
					return value, err
				}
				held = heldConverted
				value.Notice = held
			}
			return value, nil
		}()
		value = converted
		return err
	})
	if err != nil {
		var zero Watcher
		return zero, err
	}
	return value, nil
}

// AdapterNotice composes declaration validation and conversion within the supplied invocation context.
func AdapterNotice() runtime.ValueAdapter[Notice] {
	binding := runtime.TypeBinding{Schema: schema, Type: "Notice"}
	return runtime.ValueAdapter[Notice]{
		Binding:      binding,
		NeedsContext: true,
		Export: func(ctx context.Context, value Notice) (json.RawMessage, error) {
			if ctx == nil {
				return nil, fmt.Errorf("a live conversion requires an active owner")
			}
			owner, ok := live.OwnerOf(ctx)
			if !ok || owner == nil {
				return nil, fmt.Errorf("a live conversion requires an active owner")
			}
			raw, err := ExportNotice(owner, value)
			if err == nil {
				err = binding.Schema.ValidateExpressionRaw(binding.Type, raw)
			}
			return raw, err
		},
		Import: func(ctx context.Context, raw json.RawMessage) (Notice, error) {
			var zero Notice
			if ctx == nil {
				return zero, fmt.Errorf("a live conversion requires an active owner")
			}
			owner, ok := live.OwnerOf(ctx)
			if !ok || owner == nil {
				return zero, fmt.Errorf("a live conversion requires an active owner")
			}
			if err := binding.Schema.ValidateExpressionRaw(binding.Type, raw); err != nil {
				return zero, err
			}
			return ImportNotice(owner, raw)
		},
	}
}

// AdapterPayload composes declaration validation and conversion within the supplied invocation context.
func AdapterPayload() runtime.ValueAdapter[Payload] {
	binding := runtime.TypeBinding{Schema: schema, Type: "Payload"}
	return runtime.ValueAdapter[Payload]{
		Binding:      binding,
		NeedsContext: false,
		Export: func(ctx context.Context, value Payload) (json.RawMessage, error) {
			raw, err := runtime.MarshalJSON(value)
			if err == nil {
				err = binding.Schema.ValidateExpressionRaw(binding.Type, raw)
			}
			return raw, err
		},
		Import: func(ctx context.Context, raw json.RawMessage) (Payload, error) {
			var zero Payload
			if err := binding.Schema.ValidateExpressionRaw(binding.Type, raw); err != nil {
				return zero, err
			}
			return func() (Payload, error) { var value Payload; err := json.Unmarshal(raw, &value); return value, err }()
		},
	}
}

// AdapterStop composes declaration validation and conversion within the supplied invocation context.
func AdapterStop() runtime.ValueAdapter[Stop] {
	binding := runtime.TypeBinding{Schema: schema, Type: "Stop"}
	return runtime.ValueAdapter[Stop]{
		Binding:      binding,
		NeedsContext: true,
		Export: func(ctx context.Context, value Stop) (json.RawMessage, error) {
			if ctx == nil {
				return nil, fmt.Errorf("a live conversion requires an active owner")
			}
			owner, ok := live.OwnerOf(ctx)
			if !ok || owner == nil {
				return nil, fmt.Errorf("a live conversion requires an active owner")
			}
			raw, err := ExportStop(owner, value)
			if err == nil {
				err = binding.Schema.ValidateExpressionRaw(binding.Type, raw)
			}
			return raw, err
		},
		Import: func(ctx context.Context, raw json.RawMessage) (Stop, error) {
			var zero Stop
			if ctx == nil {
				return zero, fmt.Errorf("a live conversion requires an active owner")
			}
			owner, ok := live.OwnerOf(ctx)
			if !ok || owner == nil {
				return zero, fmt.Errorf("a live conversion requires an active owner")
			}
			if err := binding.Schema.ValidateExpressionRaw(binding.Type, raw); err != nil {
				return zero, err
			}
			return ImportStop(owner, raw)
		},
	}
}

// AdapterSubscription composes declaration validation and conversion within the supplied invocation context.
func AdapterSubscription() runtime.ValueAdapter[Subscription] {
	binding := runtime.TypeBinding{Schema: schema, Type: "Subscription"}
	return runtime.ValueAdapter[Subscription]{
		Binding:      binding,
		NeedsContext: true,
		Export: func(ctx context.Context, value Subscription) (json.RawMessage, error) {
			if ctx == nil {
				return nil, fmt.Errorf("a live conversion requires an active owner")
			}
			owner, ok := live.OwnerOf(ctx)
			if !ok || owner == nil {
				return nil, fmt.Errorf("a live conversion requires an active owner")
			}
			raw, err := ExportSubscription(owner, value)
			if err == nil {
				err = binding.Schema.ValidateExpressionRaw(binding.Type, raw)
			}
			return raw, err
		},
		Import: func(ctx context.Context, raw json.RawMessage) (Subscription, error) {
			var zero Subscription
			if ctx == nil {
				return zero, fmt.Errorf("a live conversion requires an active owner")
			}
			owner, ok := live.OwnerOf(ctx)
			if !ok || owner == nil {
				return zero, fmt.Errorf("a live conversion requires an active owner")
			}
			if err := binding.Schema.ValidateExpressionRaw(binding.Type, raw); err != nil {
				return zero, err
			}
			return ImportSubscription(owner, raw)
		},
	}
}

// AdapterWatch composes declaration validation and conversion within the supplied invocation context.
func AdapterWatch() runtime.ValueAdapter[Watch] {
	binding := runtime.TypeBinding{Schema: schema, Type: "Watch"}
	return runtime.ValueAdapter[Watch]{
		Binding:      binding,
		NeedsContext: true,
		Export: func(ctx context.Context, value Watch) (json.RawMessage, error) {
			if ctx == nil {
				return nil, fmt.Errorf("a live conversion requires an active owner")
			}
			owner, ok := live.OwnerOf(ctx)
			if !ok || owner == nil {
				return nil, fmt.Errorf("a live conversion requires an active owner")
			}
			raw, err := ExportWatch(owner, value)
			if err == nil {
				err = binding.Schema.ValidateExpressionRaw(binding.Type, raw)
			}
			return raw, err
		},
		Import: func(ctx context.Context, raw json.RawMessage) (Watch, error) {
			var zero Watch
			if ctx == nil {
				return zero, fmt.Errorf("a live conversion requires an active owner")
			}
			owner, ok := live.OwnerOf(ctx)
			if !ok || owner == nil {
				return zero, fmt.Errorf("a live conversion requires an active owner")
			}
			if err := binding.Schema.ValidateExpressionRaw(binding.Type, raw); err != nil {
				return zero, err
			}
			return ImportWatch(owner, raw)
		},
	}
}

// AdapterWatcher composes declaration validation and conversion within the supplied invocation context.
func AdapterWatcher() runtime.ValueAdapter[Watcher] {
	binding := runtime.TypeBinding{Schema: schema, Type: "Watcher"}
	return runtime.ValueAdapter[Watcher]{
		Binding:      binding,
		NeedsContext: true,
		Export: func(ctx context.Context, value Watcher) (json.RawMessage, error) {
			if ctx == nil {
				return nil, fmt.Errorf("a live conversion requires an active owner")
			}
			owner, ok := live.OwnerOf(ctx)
			if !ok || owner == nil {
				return nil, fmt.Errorf("a live conversion requires an active owner")
			}
			raw, err := ExportWatcher(owner, value)
			if err == nil {
				err = binding.Schema.ValidateExpressionRaw(binding.Type, raw)
			}
			return raw, err
		},
		Import: func(ctx context.Context, raw json.RawMessage) (Watcher, error) {
			var zero Watcher
			if ctx == nil {
				return zero, fmt.Errorf("a live conversion requires an active owner")
			}
			owner, ok := live.OwnerOf(ctx)
			if !ok || owner == nil {
				return zero, fmt.Errorf("a live conversion requires an active owner")
			}
			if err := binding.Schema.ValidateExpressionRaw(binding.Type, raw); err != nil {
				return zero, err
			}
			return ImportWatcher(owner, raw)
		},
	}
}

type ServerMethods interface {
	Echo(ctx context.Context, params Payload) (Payload, error)
	Watch(ctx context.Context, params Watch) (Subscription, error)
}
type ServerEvents interface {
}
type Server struct {
	Methods ServerMethods
	Events  ServerEvents
}
type ClientMethods interface {
	Reverse(ctx context.Context, params Payload) (Payload, error)
}
type ClientEvents interface {
	Changed(ctx context.Context, data Payload) error
}
type Client struct {
	Methods ClientMethods
	Events  ClientEvents
}
type ServerModel func(Client) (Server, error)
type ClientModel func(Server) (Client, error)

// The public errors of the family: what a handler returns, as the Code of a *runtime.PublicError, and a caller tells apart with IsError.
const (
	// ErrorDenied: The caller is denied.
	ErrorDenied = "denied"
)

// Errors is every public error code the family declares.
var Errors = []string{ErrorDenied}

// IsError reports whether an error is, or wraps, the family's public error of the code.
func IsError(err error, code string) bool {
	var public *runtime.PublicError
	return errors.As(err, &public) && public.Code == code
}
