// Code generated by nightseam. DO NOT EDIT.
package albumclient

import (
	context "context"
	json "encoding/json"
	errors "errors"
	protocol "example.test/generated/api/go/album-protocol"
	fmt "fmt"
	duplex "github.com/Bitspark/nightseam/duplex/go"
	runtime "github.com/Bitspark/nightseam/runtime/go"
	atomic "sync/atomic"
)

type serverMethods[AEnvelope, BEnvelope any] struct {
	wire             duplex.Wire
	environment      runtime.AdapterContext
	adapterAEnvelope runtime.ValueAdapter[AEnvelope]
	adapterBEnvelope runtime.ValueAdapter[BEnvelope]
}
type serverEvents[AEnvelope, BEnvelope any] struct {
	wire             duplex.Wire
	environment      runtime.AdapterContext
	adapterAEnvelope runtime.ValueAdapter[AEnvelope]
	adapterBEnvelope runtime.ValueAdapter[BEnvelope]
}

func accessServer[AEnvelope, BEnvelope any](wire duplex.Wire, environment runtime.AdapterContext, adapterAEnvelope runtime.ValueAdapter[AEnvelope], adapterBEnvelope runtime.ValueAdapter[BEnvelope]) protocol.Server[AEnvelope, BEnvelope] {
	return protocol.Server[AEnvelope, BEnvelope]{Methods: &serverMethods[AEnvelope, BEnvelope]{wire: wire, environment: environment, adapterAEnvelope: adapterAEnvelope, adapterBEnvelope: adapterBEnvelope}, Events: &serverEvents[AEnvelope, BEnvelope]{wire: wire, environment: environment, adapterAEnvelope: adapterAEnvelope, adapterBEnvelope: adapterBEnvelope}}
}
func (c *serverMethods[AEnvelope, BEnvelope]) Look(ctx context.Context, params protocol.Mine[AEnvelope]) (protocol.Both[AEnvelope, BEnvelope], error) {
	var result protocol.Both[AEnvelope, BEnvelope]
	if c.adapterAEnvelope.NeedsContext || c.adapterBEnvelope.NeedsContext {
		var err error
		ctx, err = c.environment.ValueEnvironment.Select(ctx)
		if err != nil {
			return result, err
		}
	}
	raw, err := func() (json.RawMessage, error) {
		build := func(ctx context.Context) (json.RawMessage, error) {
			sent, err := func() (json.RawMessage, error) {
				var value json.RawMessage
				convert := func(ctx context.Context) (json.RawMessage, error) {
					convertedConvert0 := func(input AEnvelope) (json.RawMessage, error) {
						converted, err := c.adapterAEnvelope.Export(ctx, input)
						if err != nil {
							return nil, err
						}
						return converted, nil
					}
					converted, err := protocol.ExportMine[AEnvelope](params, convertedConvert0, runtime.TypeBinding{Schema: protocol.WireSchema().Bind(map[string]any{"A.Envelope": c.adapterAEnvelope.Binding, "B.Envelope": c.adapterBEnvelope.Binding}, nil), Type: runtime.MustTypeExpression("\"A.Envelope\"")})
					if err != nil {
						return value, err
					}
					if err := protocol.WireSchema().Bind(map[string]any{"A.Envelope": c.adapterAEnvelope.Binding, "B.Envelope": c.adapterBEnvelope.Binding}, nil).ValidateExpressionRaw(protocol.MustTypeExpression("\"Mine\""), converted); err != nil {
						return value, err
					}
					return converted, nil
				}
				if c.adapterAEnvelope.NeedsContext {
					return c.environment.ValueEnvironment.Export(ctx, convert)
				}
				return convert(ctx)
			}()
			return sent, err
		}
		publish := func(sent json.RawMessage) (json.RawMessage, error) {
			var raw json.RawMessage
			err := runtime.CallWire(ctx, c.wire, []string{"look"}, sent, &raw, runtime.WireCallOptions{Observer: c.environment.Options.Observer, Family: "album", Propagator: c.environment.Options.Propagator, RequestTimeout: c.environment.Options.RequestTimeout})
			return raw, err
		}
		if c.adapterAEnvelope.NeedsContext {
			return c.environment.ValueEnvironment.Publish(ctx, build, publish)
		}
		sent, err := build(ctx)
		if err != nil {
			return nil, err
		}
		return publish(sent)
	}()
	if err != nil {
		return result, err
	}
	received, err := func() (protocol.Both[AEnvelope, BEnvelope], error) {
		var value protocol.Both[AEnvelope, BEnvelope]
		convert := func(ctx context.Context) (protocol.Both[AEnvelope, BEnvelope], error) {
			if err := protocol.WireSchema().Bind(map[string]any{"A.Envelope": c.adapterAEnvelope.Binding, "B.Envelope": c.adapterBEnvelope.Binding}, nil).ValidateExpressionRaw(protocol.MustTypeExpression("\"Both\""), raw); err != nil {
				return value, err
			}
			convertedConvert0 := func(input json.RawMessage) (AEnvelope, error) {
				var zero AEnvelope
				converted, err := c.adapterAEnvelope.Import(ctx, input)
				if err != nil {
					return zero, err
				}
				return converted, nil
			}
			convertedConvert1 := func(input json.RawMessage) (BEnvelope, error) {
				var zero BEnvelope
				converted, err := c.adapterBEnvelope.Import(ctx, input)
				if err != nil {
					return zero, err
				}
				return converted, nil
			}
			converted, err := protocol.ImportBoth[AEnvelope, BEnvelope](raw, convertedConvert0, runtime.TypeBinding{Schema: protocol.WireSchema().Bind(map[string]any{"A.Envelope": c.adapterAEnvelope.Binding, "B.Envelope": c.adapterBEnvelope.Binding}, nil), Type: runtime.MustTypeExpression("\"A.Envelope\"")}, convertedConvert1, runtime.TypeBinding{Schema: protocol.WireSchema().Bind(map[string]any{"A.Envelope": c.adapterAEnvelope.Binding, "B.Envelope": c.adapterBEnvelope.Binding}, nil), Type: runtime.MustTypeExpression("\"B.Envelope\"")})
			if err != nil {
				return value, err
			}
			return converted, nil
		}
		if c.adapterAEnvelope.NeedsContext || c.adapterBEnvelope.NeedsContext {
			err := c.environment.ValueEnvironment.Import(ctx, func(ctx context.Context) error {
				converted, err := convert(ctx)
				if err == nil {
					value = converted
				}
				return err
			})
			if err != nil {
				var zero protocol.Both[AEnvelope, BEnvelope]
				return zero, err
			}
			return value, nil
		}
		return convert(ctx)
	}()
	return received, err
}
func bindServer[AEnvelope, BEnvelope any](wire runtime.HandlerRegistry, lookup func() protocol.Server[AEnvelope, BEnvelope], environment runtime.AdapterContext, adapterAEnvelope runtime.ValueAdapter[AEnvelope], adapterBEnvelope runtime.ValueAdapter[BEnvelope]) error {
	var detach []func()
	complete := false
	defer func() {
		if !complete {
			for _, off := range detach {
				off()
			}
		}
	}()
	{
		handlers := runtime.WireHandlers{Observer: environment.Options.Observer, Family: "album"}
		handlers.Request = func(ctx context.Context, raw json.RawMessage) (any, error) {
			implementation := lookup()
			if implementation.Methods == nil {
				return nil, fmt.Errorf("model methods are required")
			}
			if adapterAEnvelope.NeedsContext || adapterBEnvelope.NeedsContext {
				var err error
				ctx, err = environment.ValueEnvironment.Child(ctx)
				if err != nil {
					return nil, err
				}
			}
			params, err := func() (protocol.Mine[AEnvelope], error) {
				var value protocol.Mine[AEnvelope]
				convert := func(ctx context.Context) (protocol.Mine[AEnvelope], error) {
					if err := protocol.WireSchema().Bind(map[string]any{"A.Envelope": adapterAEnvelope.Binding, "B.Envelope": adapterBEnvelope.Binding}, nil).ValidateExpressionRaw(protocol.MustTypeExpression("\"Mine\""), raw); err != nil {
						return value, err
					}
					convertedConvert0 := func(input json.RawMessage) (AEnvelope, error) {
						var zero AEnvelope
						converted, err := adapterAEnvelope.Import(ctx, input)
						if err != nil {
							return zero, err
						}
						return converted, nil
					}
					converted, err := protocol.ImportMine[AEnvelope](raw, convertedConvert0, runtime.TypeBinding{Schema: protocol.WireSchema().Bind(map[string]any{"A.Envelope": adapterAEnvelope.Binding, "B.Envelope": adapterBEnvelope.Binding}, nil), Type: runtime.MustTypeExpression("\"A.Envelope\"")})
					if err != nil {
						return value, err
					}
					return converted, nil
				}
				if adapterAEnvelope.NeedsContext {
					err := environment.ValueEnvironment.Import(ctx, func(ctx context.Context) error {
						converted, err := convert(ctx)
						if err == nil {
							value = converted
						}
						return err
					})
					if err != nil {
						var zero protocol.Mine[AEnvelope]
						return zero, err
					}
					return value, nil
				}
				return convert(ctx)
			}()
			if err != nil {
				var public *runtime.PublicError
				if errors.As(err, &public) && public.Code == "contract_mismatch" {
					return nil, err
				}
				return nil, &runtime.PublicError{Code: "invalid_params", Message: err.Error()}
			}
			result, err := implementation.Methods.Look(ctx, params)
			if err != nil {
				return nil, err
			}
			sent, err := func() (json.RawMessage, error) {
				var value json.RawMessage
				convert := func(ctx context.Context) (json.RawMessage, error) {
					convertedConvert0 := func(input AEnvelope) (json.RawMessage, error) {
						converted, err := adapterAEnvelope.Export(ctx, input)
						if err != nil {
							return nil, err
						}
						return converted, nil
					}
					convertedConvert1 := func(input BEnvelope) (json.RawMessage, error) {
						converted, err := adapterBEnvelope.Export(ctx, input)
						if err != nil {
							return nil, err
						}
						return converted, nil
					}
					converted, err := protocol.ExportBoth[AEnvelope, BEnvelope](result, convertedConvert0, runtime.TypeBinding{Schema: protocol.WireSchema().Bind(map[string]any{"A.Envelope": adapterAEnvelope.Binding, "B.Envelope": adapterBEnvelope.Binding}, nil), Type: runtime.MustTypeExpression("\"A.Envelope\"")}, convertedConvert1, runtime.TypeBinding{Schema: protocol.WireSchema().Bind(map[string]any{"A.Envelope": adapterAEnvelope.Binding, "B.Envelope": adapterBEnvelope.Binding}, nil), Type: runtime.MustTypeExpression("\"B.Envelope\"")})
					if err != nil {
						return value, err
					}
					if err := protocol.WireSchema().Bind(map[string]any{"A.Envelope": adapterAEnvelope.Binding, "B.Envelope": adapterBEnvelope.Binding}, nil).ValidateExpressionRaw(protocol.MustTypeExpression("\"Both\""), converted); err != nil {
						return value, err
					}
					return converted, nil
				}
				if adapterAEnvelope.NeedsContext || adapterBEnvelope.NeedsContext {
					return environment.ValueEnvironment.Export(ctx, convert)
				}
				return convert(ctx)
			}()
			return sent, err
		}
		if handlers.Request != nil || handlers.Event != nil {
			off, err := runtime.RegisterWire(wire, []string{"look"}, handlers)
			if err != nil {
				return err
			}
			detach = append(detach, off)
		}
	}
	complete = true
	return nil
}

type clientMethods[AEnvelope, BEnvelope any] struct {
	wire             duplex.Wire
	environment      runtime.AdapterContext
	adapterAEnvelope runtime.ValueAdapter[AEnvelope]
	adapterBEnvelope runtime.ValueAdapter[BEnvelope]
}
type clientEvents[AEnvelope, BEnvelope any] struct {
	wire             duplex.Wire
	environment      runtime.AdapterContext
	adapterAEnvelope runtime.ValueAdapter[AEnvelope]
	adapterBEnvelope runtime.ValueAdapter[BEnvelope]
}

func accessClient[AEnvelope, BEnvelope any](wire duplex.Wire, environment runtime.AdapterContext, adapterAEnvelope runtime.ValueAdapter[AEnvelope], adapterBEnvelope runtime.ValueAdapter[BEnvelope]) protocol.Client[AEnvelope, BEnvelope] {
	return protocol.Client[AEnvelope, BEnvelope]{Methods: &clientMethods[AEnvelope, BEnvelope]{wire: wire, environment: environment, adapterAEnvelope: adapterAEnvelope, adapterBEnvelope: adapterBEnvelope}, Events: &clientEvents[AEnvelope, BEnvelope]{wire: wire, environment: environment, adapterAEnvelope: adapterAEnvelope, adapterBEnvelope: adapterBEnvelope}}
}
func bindClient[AEnvelope, BEnvelope any](wire runtime.HandlerRegistry, lookup func() protocol.Client[AEnvelope, BEnvelope], environment runtime.AdapterContext, adapterAEnvelope runtime.ValueAdapter[AEnvelope], adapterBEnvelope runtime.ValueAdapter[BEnvelope]) error {
	var detach []func()
	complete := false
	defer func() {
		if !complete {
			for _, off := range detach {
				off()
			}
		}
	}()
	complete = true
	return nil
}
func normalizeContext[AEnvelope, BEnvelope any](environment runtime.AdapterContext, adapterAEnvelope runtime.ValueAdapter[AEnvelope], adapterBEnvelope runtime.ValueAdapter[BEnvelope]) (runtime.AdapterContext, error) {
	if adapterAEnvelope.Export == nil || adapterAEnvelope.Import == nil {
		return environment, fmt.Errorf("AEnvelope: both conversion recipes are required")
	}
	if adapterBEnvelope.Export == nil || adapterBEnvelope.Import == nil {
		return environment, fmt.Errorf("BEnvelope: both conversion recipes are required")
	}
	if (adapterAEnvelope.NeedsContext || adapterBEnvelope.NeedsContext) && environment.ValueEnvironment == nil {
		return environment, fmt.Errorf("a context-dependent adapter requires a value environment")
	}
	return environment, nil
}

// ToWire binds one model factory and returns its owned access endpoint.
func ToWire[AEnvelope runtime.Of[ATag], BEnvelope runtime.Of[BTag], ATag, BTag any](model protocol.ClientModel[AEnvelope, BEnvelope], environment runtime.AdapterContext, adapterAEnvelope runtime.ValueAdapter[AEnvelope], adapterBEnvelope runtime.ValueAdapter[BEnvelope]) (duplex.Endpoint, error) {
	if model == nil {
		return nil, fmt.Errorf("model factory is required")
	}
	environment, err := normalizeContext[AEnvelope, BEnvelope](environment, adapterAEnvelope, adapterBEnvelope)
	if err != nil {
		return nil, err
	}
	identity, err := declarationIdentity[AEnvelope, BEnvelope](adapterAEnvelope, adapterBEnvelope)
	if err != nil {
		return nil, err
	}
	options := environment.Options
	families := map[string]string{}
	for name, existing := range options.Families {
		families[name] = existing
	}
	families["4:look"] = "album"
	options.Families = families
	access, binding, err := runtime.NewWirePair(options)
	if err != nil {
		return nil, err
	}
	complete := false
	defer func() {
		if !complete {
			_ = access.Close(duplex.CodeInternalError, "model construction failed")
		}
	}()
	dispatcher, err := runtime.NewDispatcher(binding)
	if err != nil {
		return nil, err
	}
	if _, err := registerIdentity(dispatcher, identity); err != nil {
		return nil, err
	}
	implementation, err := model(accessServer[AEnvelope, BEnvelope](binding, environment, adapterAEnvelope, adapterBEnvelope))
	if err != nil {
		return nil, err
	}
	if err := bindClient[AEnvelope, BEnvelope](dispatcher, func() protocol.Client[AEnvelope, BEnvelope] { return implementation }, environment, adapterAEnvelope, adapterBEnvelope); err != nil {
		return nil, err
	}
	complete = true
	return access, nil
}
func declarationIdentity[AEnvelope, BEnvelope any](adapterAEnvelope runtime.ValueAdapter[AEnvelope], adapterBEnvelope runtime.ValueAdapter[BEnvelope]) (runtime.DeclarationIdentity, error) {
	digest, err := protocol.WireSchema().Bind(map[string]any{"A.Envelope": adapterAEnvelope.Binding, "B.Envelope": adapterBEnvelope.Binding}, nil).DeclarationDigest()
	if err != nil {
		return runtime.DeclarationIdentity{}, err
	}
	return runtime.DeclarationIdentity{Path: "album", Digest: digest}, nil
}
func registerIdentity(wire runtime.HandlerRegistry, identity runtime.DeclarationIdentity) (func(), error) {
	handler, err := runtime.IdentityHandler(identity)
	if err != nil {
		return nil, err
	}
	return runtime.HandleWire(wire, []string{runtime.IdentityMethod}, func(ctx context.Context, raw json.RawMessage) (any, error) { return handler(ctx, nil, raw) })
}

// PrepareFromWire registers receivers synchronously, before the wire is attached.
// Complete checks identity and returns a factory that may be bound once. Both steps
// must finish within environment.Options.RequestTimeout. Cleanup detaches this
// interpretation's registrations, including after success, and never closes the wire.
func PrepareFromWire[AEnvelope runtime.Of[ATag], BEnvelope runtime.Of[BTag], ATag, BTag any](wire duplex.Endpoint, environment runtime.AdapterContext, adapterAEnvelope runtime.ValueAdapter[AEnvelope], adapterBEnvelope runtime.ValueAdapter[BEnvelope]) (complete func(context.Context) (protocol.ClientModel[AEnvelope, BEnvelope], error), cleanup func(), err error) {
	if wire == nil {
		return nil, nil, fmt.Errorf("wire is required")
	}
	environment, err = normalizeContext[AEnvelope, BEnvelope](environment, adapterAEnvelope, adapterBEnvelope)
	if err != nil {
		return nil, nil, err
	}
	identity, err := declarationIdentity[AEnvelope, BEnvelope](adapterAEnvelope, adapterBEnvelope)
	if err != nil {
		return nil, nil, err
	}
	preparation, err := runtime.PrepareIdentity(wire, identity, environment.Options)
	if err != nil {
		return nil, nil, err
	}
	cleanup = preparation.Close
	var implementation atomic.Pointer[protocol.Server[AEnvelope, BEnvelope]]
	lookup := func() protocol.Server[AEnvelope, BEnvelope] {
		if current := implementation.Load(); current != nil {
			return *current
		}
		return protocol.Server[AEnvelope, BEnvelope]{}
	}
	if err = bindServer[AEnvelope, BEnvelope](preparation.Wire(), lookup, environment, adapterAEnvelope, adapterBEnvelope); err != nil {
		cleanup()
		return nil, nil, err
	}
	var checking, bound atomic.Bool
	complete = func(ctx context.Context) (protocol.ClientModel[AEnvelope, BEnvelope], error) {
		if !checking.CompareAndSwap(false, true) {
			return nil, fmt.Errorf("identity completion is already started")
		}
		if err := preparation.Check(ctx); err != nil {
			cleanup()
			return nil, err
		}
		return func(value protocol.Server[AEnvelope, BEnvelope]) (protocol.Client[AEnvelope, BEnvelope], error) {
			if !bound.CompareAndSwap(false, true) {
				return protocol.Client[AEnvelope, BEnvelope]{}, fmt.Errorf("model factory is already bound")
			}
			if value.Methods == nil {
				cleanup()
				return protocol.Client[AEnvelope, BEnvelope]{}, fmt.Errorf("Server methods are required")
			}
			implementation.Store(&value)
			if err := preparation.Ready(); err != nil {
				cleanup()
				return protocol.Client[AEnvelope, BEnvelope]{}, err
			}
			return accessClient[AEnvelope, BEnvelope](preparation.Wire(), environment, adapterAEnvelope, adapterBEnvelope), nil
		}, nil
	}
	return complete, cleanup, nil
}

// FromWire checks identity and returns a factory that may be bound once.
// Use PrepareFromWire before attachment when incoming delivery can begin immediately.
func FromWire[AEnvelope runtime.Of[ATag], BEnvelope runtime.Of[BTag], ATag, BTag any](ctx context.Context, wire duplex.Endpoint, environment runtime.AdapterContext, adapterAEnvelope runtime.ValueAdapter[AEnvelope], adapterBEnvelope runtime.ValueAdapter[BEnvelope]) (protocol.ClientModel[AEnvelope, BEnvelope], error) {
	complete, cleanup, err := PrepareFromWire[AEnvelope, BEnvelope](wire, environment, adapterAEnvelope, adapterBEnvelope)
	if err != nil {
		return nil, err
	}
	model, err := complete(ctx)
	if err != nil {
		cleanup()
		return nil, err
	}
	return model, nil
}

// RecordedEvent is the closed union of this side's outgoing event payloads.
type RecordedEvent[AEnvelope, BEnvelope any] interface{ recordedEvent(AEnvelope, BEnvelope) }

// Recorder records converted messages without retaining or rebinding their live values.
type Recorder[AEnvelope, BEnvelope any] struct {
	*duplex.RecordedWire
	events   protocol.ServerEvents[AEnvelope, BEnvelope]
	identity runtime.DeclarationIdentity
	options  runtime.Options
}

func (r *Recorder[AEnvelope, BEnvelope]) Append(ctx context.Context, event RecordedEvent[AEnvelope, BEnvelope]) error {
	return fmt.Errorf("this side declares no outgoing events")
}

// Follow checks the subscriber's declaration before registering any replay.
func (r *Recorder[AEnvelope, BEnvelope]) Follow(ctx context.Context, after uint64, target duplex.Wire) (*duplex.Follower, error) {
	if err := runtime.CheckIdentity(ctx, func(ctx context.Context, method string, params, result any) error {
		return runtime.CallWire(ctx, target, []string{method}, params, result, runtime.WireCallOptions{RequestTimeout: r.options.RequestTimeout, Observer: r.options.Observer, Propagator: r.options.Propagator})
	}, r.identity); err != nil {
		return nil, err
	}
	return r.RecordedWire.Follow(ctx, after, target)
}

// Record checks a prepared origin before exposing typed event append. Setup
// failure detaches this interpretation and leaves the borrowed target usable.
func Record[AEnvelope runtime.Of[ATag], BEnvelope runtime.Of[BTag], ATag, BTag any](ctx context.Context, target duplex.Endpoint, log duplex.WireLog, options duplex.RecordOptions, environment runtime.AdapterContext, adapterAEnvelope runtime.ValueAdapter[AEnvelope], adapterBEnvelope runtime.ValueAdapter[BEnvelope]) (*Recorder[AEnvelope, BEnvelope], error) {
	environment, err := normalizeContext[AEnvelope, BEnvelope](environment, adapterAEnvelope, adapterBEnvelope)
	if err != nil {
		return nil, err
	}
	identity, err := declarationIdentity[AEnvelope, BEnvelope](adapterAEnvelope, adapterBEnvelope)
	if err != nil {
		return nil, err
	}
	preparation, err := runtime.PrepareIdentity(target, identity, environment.Options)
	if err != nil {
		return nil, err
	}
	if err := preparation.Check(ctx); err != nil {
		preparation.Close()
		return nil, err
	}
	if err := preparation.Ready(); err != nil {
		preparation.Close()
		return nil, err
	}
	onClose := options.OnClose
	options.OnClose = func(err error) {
		preparation.Close()
		if onClose != nil {
			onClose(err)
		}
	}
	wire, err := duplex.Record(ctx, preparation.Wire(), log, options)
	if err != nil {
		preparation.Close()
		return nil, err
	}
	return &Recorder[AEnvelope, BEnvelope]{RecordedWire: wire, events: accessServer[AEnvelope, BEnvelope](wire, environment, adapterAEnvelope, adapterBEnvelope).Events, identity: identity, options: environment.Options}, nil
}
