// Code generated by nightseam. DO NOT EDIT.
import { DuplexPeer, DuplexError, type PeerOptions, type CallOptions, type EmitOptions, type RequestContext, type EventContext, type FrameConnection, type WebSocketLike } from "@nightseam/runtime";
import { validateWire } from "@example/pair-client/types";
import type * as Protocol from "@example/pair-client/types";
import type { AnyFamily, FamilyBinding, TypeBinding, Slots } from "@example/pair-client/types";
import type * as probe from "@example/probe-client";
export * from "@example/pair-client/types";
export { DuplexError };
/** Typed handlers for the declaration's server side. */
export interface Handler<S extends AnyFamily = AnyFamily, T extends AnyFamily = AnyFamily> {
  named(params: Protocol.Named, remote: Remote<S, T>, context: RequestContext): Protocol.Named | Promise<Protocol.Named>;
  relay(params: T["Envelope"], remote: Remote<S, T>, context: RequestContext): Protocol.Both<S, T> | Promise<Protocol.Both<S, T>>;
}
/** Client-originated event listeners installed before the connection reads its first frame. */
export interface Events<S extends AnyFamily = AnyFamily, T extends AnyFamily = AnyFamily> {
}
/** Typed reverse calls and events for one connected client. */
export class Remote<S extends AnyFamily = AnyFamily, T extends AnyFamily = AnyFamily> {
  readonly peer: DuplexPeer;
  readonly s: FamilyBinding<S>;
  readonly t: FamilyBinding<T>;
  readonly slots: Slots;
  constructor(peer: DuplexPeer, s: FamilyBinding<S>, t: FamilyBinding<T>) {
    this.peer = peer;
    this.s = s;
    this.t = t;
    this.slots = { "S": s, "T": t };
  }
  close(): void { this.peer.close(); }
  async emitEchoed(data: Protocol.Echo<T>, options?: EmitOptions): Promise<void> { validateWire("Echo", data, '$', this.slots); await this.peer.emit("echoed", data, options); }
}
/** Installs the typed binding before a host-configured peer starts reading. An existing live scope is preserved. */
export function install<S extends AnyFamily = AnyFamily, T extends AnyFamily = AnyFamily>(peer: DuplexPeer, s: FamilyBinding<S>, t: FamilyBinding<T>, handler: Handler<S, T>, events: Events<S, T> = {}): Remote<S, T> {
  if (!handler) throw new Error('handler is required');
  if (typeof handler.named !== 'function') throw new Error("handler for named is required");
  if (typeof handler.relay !== 'function') throw new Error("handler for relay is required");
  const remote = new Remote<S, T>(peer, s, t);
  peer.handle("named", async (params, context) => { try { validateWire("Named", params, '$', remote.slots); } catch(error) { if (error instanceof DuplexError && error.code === 'contract_mismatch') throw error; throw new DuplexError('invalid_params', String(error)); } const result = await handler.named(params as Protocol.Named, remote, context); validateWire("Named", result, '$', remote.slots); return result; });
  peer.handle("relay", async (params, context) => { try { validateWire("T.Envelope", params, '$', remote.slots); } catch(error) { if (error instanceof DuplexError && error.code === 'contract_mismatch') throw error; throw new DuplexError('invalid_params', String(error)); } const result = await handler.relay(params as T["Envelope"], remote, context); validateWire("Both", result, '$', remote.slots); return result; });
  return remote;
}
/** Serves an externally authenticated accepted connection. The returned peer is the caller's to close. */
export async function serve<S extends AnyFamily = AnyFamily, T extends AnyFamily = AnyFamily>(connection: FrameConnection | WebSocketLike, s: FamilyBinding<S>, t: FamilyBinding<T>, options: PeerOptions, handler: Handler<S, T>, events: Events<S, T> = {}): Promise<DuplexPeer> {
  const peer = new DuplexPeer({ ...{ ...options, families: { ...options.families, "named": "pair", "relay": "pair", "echoed": "pair" } }, role: 'server' });
  try { install<S, T>(peer, s, t, handler, events); await peer.attach(connection); return peer; } catch (error) { peer.close(); throw error; }
}
