// Code generated by nightseam. DO NOT EDIT.
package workerprotocol

import (
	context "context"
	json "encoding/json"
	errors "errors"
	fmt "fmt"
	live "github.com/Bitspark/nightseam/live/go"
	runtime "github.com/Bitspark/nightseam/runtime/go"
)

// Tag is this family, as a type: what every record and enum of the package returns from Of, and what an entry point of a package generic in a family holds its type arguments to.
type Tag struct{}

// Envelope: One message of the nightseam.duplex/1 profile: the members the peer acts on, and nothing else.
type Envelope struct {
	Version     int64                               `json:"version"`
	Kind        string                              `json:"kind"`
	ID          runtime.Optional[string]            `json:"id,omitzero"`
	Method      runtime.Optional[string]            `json:"method,omitzero"`
	Params      runtime.Optional[any]               `json:"params,omitzero"`
	Result      runtime.Optional[any]               `json:"result,omitzero"`
	Error       runtime.Optional[any]               `json:"error,omitzero"`
	Event       runtime.Optional[string]            `json:"event,omitzero"`
	Data        runtime.Optional[any]               `json:"data,omitzero"`
	Traceparent runtime.Optional[string]            `json:"traceparent,omitzero"`
	Tracestate  runtime.Optional[string]            `json:"tracestate,omitzero"`
	Meta        runtime.Optional[map[string]string] `json:"meta,omitzero"`
}

func (v Envelope) MarshalJSON() ([]byte, error) {
	type wire Envelope
	data, err := runtime.MarshalJSON(wire(v))
	if err != nil {
		return nil, err
	}
	if err = schema.ValidateExpressionRaw("Envelope", data); err != nil {
		return nil, err
	}
	return data, nil
}
func (v *Envelope) UnmarshalJSON(data []byte) error {
	if err := schema.ValidateExpressionRaw("Envelope", data); err != nil {
		return err
	}
	type wire Envelope
	var decoded wire
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*v = Envelope(decoded)
	return nil
}
func (Envelope) Of() Tag { return Tag{} }
func (Envelope) WireType() runtime.TypeBinding {
	return runtime.TypeBinding{Schema: schema, Type: "Envelope"}
}

// Handle: A reference to a channel on the connection that carries the message holding it.
type Handle struct {
	Channel int64 `json:"channel"`
}

func (v Handle) MarshalJSON() ([]byte, error) {
	type wire Handle
	data, err := runtime.MarshalJSON(wire(v))
	if err != nil {
		return nil, err
	}
	if err = schema.ValidateExpressionRaw("Handle", data); err != nil {
		return nil, err
	}
	return data, nil
}
func (v *Handle) UnmarshalJSON(data []byte) error {
	if err := schema.ValidateExpressionRaw("Handle", data); err != nil {
		return err
	}
	type wire Handle
	var decoded wire
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*v = Handle(decoded)
	return nil
}
func (Handle) Of() Tag { return Tag{} }
func (Handle) WireType() runtime.TypeBinding {
	return runtime.TypeBinding{Schema: schema, Type: "Handle"}
}

// Job: What start answers: a record whose members are separately released.
type Job struct {
	Ticket string                   `json:"ticket"`
	Cancel Cancel                   `json:"cancel"`
	Rename runtime.Optional[Rename] `json:"rename,omitzero"`
}

// MarshalJSON refuses: Job carries a callable, and a live value has no encoding apart from the owner its bindings belong to.
func (v Job) MarshalJSON() ([]byte, error) {
	return nil, fmt.Errorf("Job carries a callable; write it with ExportJob, which takes the live owner its bindings are made in")
}

// UnmarshalJSON refuses for the same reason: a reference resolves in a owner or nowhere.
func (v *Job) UnmarshalJSON(data []byte) error {
	return fmt.Errorf("Job carries a callable; read it with ImportJob, which takes the live owner its references resolve in")
}
func (Job) Of() Tag                       { return Tag{} }
func (Job) WireType() runtime.TypeBinding { return runtime.TypeBinding{Schema: schema, Type: "Job"} }

type OutcomeKind string

const (
	OutcomeKindFinished OutcomeKind = "finished"
	OutcomeKindRunning  OutcomeKind = "running"
)

type Outcome struct {
	Finished *struct{}
	Running  *Job
}

func (v Outcome) Kind() OutcomeKind {
	var kind OutcomeKind
	selected := 0
	if v.Finished != nil {
		selected++
		kind = OutcomeKindFinished
	}
	if v.Running != nil {
		selected++
		kind = OutcomeKindRunning
	}
	if selected != 1 {
		return ""
	}
	return kind
}

// MarshalJSON refuses: Outcome carries a callable, and a live value has no encoding apart from the owner its bindings belong to.
func (v Outcome) MarshalJSON() ([]byte, error) {
	return nil, fmt.Errorf("Outcome carries a callable; write it with ExportOutcome, which takes the live owner its bindings are made in")
}

// UnmarshalJSON refuses for the same reason: a reference resolves in a owner or nowhere.
func (v *Outcome) UnmarshalJSON(data []byte) error {
	return fmt.Errorf("Outcome carries a callable; read it with ImportOutcome, which takes the live owner its references resolve in")
}
func (Outcome) WireType() runtime.TypeBinding {
	return runtime.TypeBinding{Schema: schema, Type: "Outcome"}
}

// Percent: How far along a job is, from 0 to 100.
type Percent = int64

// ProgressSink: An interface, which is a record of callable members; each member is its own binding.
type ProgressSink struct {
	Report Report `json:"report"`
}

// MarshalJSON refuses: ProgressSink carries a callable, and a live value has no encoding apart from the owner its bindings belong to.
func (v ProgressSink) MarshalJSON() ([]byte, error) {
	return nil, fmt.Errorf("ProgressSink carries a callable; write it with ExportProgressSink, which takes the live owner its bindings are made in")
}

// UnmarshalJSON refuses for the same reason: a reference resolves in a owner or nowhere.
func (v *ProgressSink) UnmarshalJSON(data []byte) error {
	return fmt.Errorf("ProgressSink carries a callable; read it with ImportProgressSink, which takes the live owner its references resolve in")
}
func (ProgressSink) Of() Tag { return Tag{} }
func (ProgressSink) WireType() runtime.TypeBinding {
	return runtime.TypeBinding{Schema: schema, Type: "ProgressSink"}
}

// Sinks: Callables in a container.
type Sinks = map[string]ProgressSink

// Start: A callable supplied as an argument, beside data.
type Start struct {
	Ticket   Ticket                     `json:"ticket"`
	Progress ProgressSink               `json:"progress"`
	Watchers runtime.Optional[Watchers] `json:"watchers,omitzero"`
}

// MarshalJSON refuses: Start carries a callable, and a live value has no encoding apart from the owner its bindings belong to.
func (v Start) MarshalJSON() ([]byte, error) {
	return nil, fmt.Errorf("Start carries a callable; write it with ExportStart, which takes the live owner its bindings are made in")
}

// UnmarshalJSON refuses for the same reason: a reference resolves in a owner or nowhere.
func (v *Start) UnmarshalJSON(data []byte) error {
	return fmt.Errorf("Start carries a callable; read it with ImportStart, which takes the live owner its references resolve in")
}
func (Start) Of() Tag { return Tag{} }
func (Start) WireType() runtime.TypeBinding {
	return runtime.TypeBinding{Schema: schema, Type: "Start"}
}

type Supervise struct {
	Sinks Sinks `json:"sinks"`
}

// MarshalJSON refuses: Supervise carries a callable, and a live value has no encoding apart from the owner its bindings belong to.
func (v Supervise) MarshalJSON() ([]byte, error) {
	return nil, fmt.Errorf("Supervise carries a callable; write it with ExportSupervise, which takes the live owner its bindings are made in")
}

// UnmarshalJSON refuses for the same reason: a reference resolves in a owner or nowhere.
func (v *Supervise) UnmarshalJSON(data []byte) error {
	return fmt.Errorf("Supervise carries a callable; read it with ImportSupervise, which takes the live owner its references resolve in")
}
func (Supervise) Of() Tag { return Tag{} }
func (Supervise) WireType() runtime.TypeBinding {
	return runtime.TypeBinding{Schema: schema, Type: "Supervise"}
}

// Ticket: A job as the application records it; its key is data and identifies a row, never a binding.
type Ticket struct {
	ID    string `json:"id"`
	Label string `json:"label"`
}

func (v Ticket) MarshalJSON() ([]byte, error) {
	type wire Ticket
	data, err := runtime.MarshalJSON(wire(v))
	if err != nil {
		return nil, err
	}
	if err = schema.ValidateExpressionRaw("Ticket", data); err != nil {
		return nil, err
	}
	return data, nil
}
func (v *Ticket) UnmarshalJSON(data []byte) error {
	if err := schema.ValidateExpressionRaw("Ticket", data); err != nil {
		return err
	}
	type wire Ticket
	var decoded wire
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*v = Ticket(decoded)
	return nil
}
func (Ticket) Of() Tag { return Tag{} }
func (Ticket) WireType() runtime.TypeBinding {
	return runtime.TypeBinding{Schema: schema, Type: "Ticket"}
}

// Watchers: Callables in a list, each of which may be null.
type Watchers = []runtime.Nullable[Report]

// Cancel: Asks the job to stop. Releasing a reference to it is not this, and cancelling the call that returned it is neither.
// A value of it is one implementation, called across the seam; each is its own binding, with its own lifetime.
type Cancel = func(ctx context.Context) error

// ContractCancel is the declaration a reference to Cancel carries. It is nominal: a reference is usable exactly where this callable is expected.
const ContractCancel = "worker/Cancel"

// ExportCancel makes a binding of a local Cancel and writes the reference that names it.
func ExportCancel(owner *live.Owner, v Cancel) (json.RawMessage, error) {
	if owner == nil {
		return nil, fmt.Errorf("Cancel: a live value is exported into an owner")
	}
	if v == nil {
		return nil, fmt.Errorf("Cancel: no implementation to export")
	}
	return owner.ExportValue(func(owner *live.Owner) (json.RawMessage, error) {
		reference, err := owner.Export(ContractCancel, func(ctx context.Context, request json.RawMessage) (json.RawMessage, error) {
			owner := owner.Child()
			ctx = live.WithOwner(ctx, owner)
			return nil, v(ctx)
		})
		if err != nil {
			return nil, err
		}
		return runtime.MarshalJSON(reference)
	})
}

// ImportCancel is a Cancel that calls the binding a reference names.
func ImportCancel(owner *live.Owner, raw json.RawMessage) (Cancel, error) {
	if owner == nil {
		return nil, fmt.Errorf("Cancel: a live value is imported into an owner")
	}
	reference, err := owner.Scope().Decode(raw)
	if err != nil {
		return nil, err
	}
	invoke, err := owner.Import(reference, ContractCancel)
	if err != nil {
		return nil, err
	}
	scope := owner.Scope()
	return func(ctx context.Context) error {
		owner := scope.Owner()
		if supplied, ok := live.OwnerOf(ctx); ok {
			if supplied.Scope() != owner.Scope() {
				return &runtime.PublicError{Code: live.ErrorReferenceForeign, Message: "the owner belongs to another connection"}
			}
			owner = supplied
		}
		result, err := invoke(ctx, nil)
		if err != nil {
			return err
		}
		_ = result
		return nil
	}, nil
}

// ExportJob writes Job as it travels: each callable in it becomes a binding of the owner, and the reference that names it takes its place.
func ExportJob(owner *live.Owner, v Job) (json.RawMessage, error) {
	if owner == nil {
		return nil, fmt.Errorf("Job: a live value is exported into an owner")
	}
	return owner.ExportValue(func(owner *live.Owner) (json.RawMessage, error) {
		wire := map[string]json.RawMessage{}
		var ticketMember json.RawMessage
		ticketMemberConverted, err := runtime.MarshalJSON(v.Ticket)
		if err != nil {
			return nil, err
		}
		ticketMember = ticketMemberConverted
		wire["ticket"] = ticketMember
		var cancelMember json.RawMessage
		cancelMemberConverted, err := ExportCancel(owner, v.Cancel)
		if err != nil {
			return nil, err
		}
		cancelMember = cancelMemberConverted
		wire["cancel"] = cancelMember
		if v.Rename.Present {
			var member json.RawMessage
			memberConverted, err := ExportRename(owner, v.Rename.Value)
			if err != nil {
				return nil, err
			}
			member = memberConverted
			wire["rename"] = member
		}
		data, err := runtime.MarshalObject([]string{"ticket", "cancel", "rename"}, wire)
		if err != nil {
			return nil, err
		}
		if err := schema.ValidateExpressionRaw("Job", data); err != nil {
			return nil, err
		}
		return data, nil
	})
}

// ImportJob reads Job as it arrived: each reference in it becomes a typed proxy of the binding it names, so a handler is given native values.
func ImportJob(owner *live.Owner, raw json.RawMessage) (Job, error) {
	var value Job
	if owner == nil {
		return value, fmt.Errorf("Job: a live value is imported into an owner")
	}
	err := owner.ImportValue(func(owner *live.Owner) error {
		converted, err := func() (Job, error) {
			var value Job
			if err := schema.ValidateExpressionRaw("Job", raw); err != nil {
				return value, err
			}
			var wire map[string]json.RawMessage
			if err := json.Unmarshal(raw, &wire); err != nil {
				return value, err
			}
			if member, present := wire["ticket"]; present {
				var held string
				var heldConverted string
				if err := json.Unmarshal(member, &heldConverted); err != nil {
					return value, err
				}
				held = heldConverted
				value.Ticket = held
			}
			if member, present := wire["cancel"]; present {
				var held Cancel
				heldConverted, err := ImportCancel(owner, member)
				if err != nil {
					return value, err
				}
				held = heldConverted
				value.Cancel = held
			}
			if member, present := wire["rename"]; present && string(member) != "undefined" {
				var held Rename
				heldConverted, err := ImportRename(owner, member)
				if err != nil {
					return value, err
				}
				held = heldConverted
				value.Rename = runtime.Some(held)
			}
			return value, nil
		}()
		value = converted
		return err
	})
	if err != nil {
		var zero Job
		return zero, err
	}
	return value, nil
}

// ExportOutcome writes Outcome as it travels: each callable in it becomes a binding of the owner, and the reference that names it takes its place.
func ExportOutcome(owner *live.Owner, v Outcome) (json.RawMessage, error) {
	if owner == nil {
		return nil, fmt.Errorf("Outcome: a live value is exported into an owner")
	}
	return owner.ExportValue(func(owner *live.Owner) (json.RawMessage, error) {
		wire := map[string]json.RawMessage{}
		tag, err := runtime.MarshalJSON(string(v.Kind()))
		if err != nil {
			return nil, err
		}
		wire["state"] = tag
		switch v.Kind() {
		case OutcomeKindFinished:
		case OutcomeKindRunning:
			payload, err := ExportJob(owner, *v.Running)
			if err != nil {
				return nil, err
			}
			wire["value"] = payload
		default:
			return nil, fmt.Errorf("Outcome: no variant is selected")
		}
		data, err := runtime.MarshalObject([]string{"state", "value"}, wire)
		if err != nil {
			return nil, err
		}
		if err := schema.ValidateExpressionRaw("Outcome", data); err != nil {
			return nil, err
		}
		return data, nil
	})
}

// ImportOutcome reads Outcome as it arrived: each reference in it becomes a typed proxy of the binding it names, so a handler is given native values.
func ImportOutcome(owner *live.Owner, raw json.RawMessage) (Outcome, error) {
	var value Outcome
	if owner == nil {
		return value, fmt.Errorf("Outcome: a live value is imported into an owner")
	}
	err := owner.ImportValue(func(owner *live.Owner) error {
		converted, err := func() (Outcome, error) {
			var value Outcome
			if err := schema.ValidateExpressionRaw("Outcome", raw); err != nil {
				return value, err
			}
			var wire map[string]json.RawMessage
			if err := json.Unmarshal(raw, &wire); err != nil {
				return value, err
			}
			var tag string
			if err := json.Unmarshal(wire["state"], &tag); err != nil {
				return value, err
			}
			switch OutcomeKind(tag) {
			case OutcomeKindFinished:
				value.Finished = &struct{}{}
			case OutcomeKindRunning:
				payload, err := ImportJob(owner, wire["value"])
				if err != nil {
					return value, err
				}
				value.Running = &payload
			default:
				return value, fmt.Errorf("Outcome: unknown variant %q", tag)
			}
			return value, nil
		}()
		value = converted
		return err
	})
	if err != nil {
		var zero Outcome
		return zero, err
	}
	return value, nil
}

// ExportProgressSink writes ProgressSink as it travels: each callable in it becomes a binding of the owner, and the reference that names it takes its place.
func ExportProgressSink(owner *live.Owner, v ProgressSink) (json.RawMessage, error) {
	if owner == nil {
		return nil, fmt.Errorf("ProgressSink: a live value is exported into an owner")
	}
	return owner.ExportValue(func(owner *live.Owner) (json.RawMessage, error) {
		wire := map[string]json.RawMessage{}
		var reportMember json.RawMessage
		reportMemberConverted, err := ExportReport(owner, v.Report)
		if err != nil {
			return nil, err
		}
		reportMember = reportMemberConverted
		wire["report"] = reportMember
		data, err := runtime.MarshalObject([]string{"report"}, wire)
		if err != nil {
			return nil, err
		}
		if err := schema.ValidateExpressionRaw("ProgressSink", data); err != nil {
			return nil, err
		}
		return data, nil
	})
}

// ImportProgressSink reads ProgressSink as it arrived: each reference in it becomes a typed proxy of the binding it names, so a handler is given native values.
func ImportProgressSink(owner *live.Owner, raw json.RawMessage) (ProgressSink, error) {
	var value ProgressSink
	if owner == nil {
		return value, fmt.Errorf("ProgressSink: a live value is imported into an owner")
	}
	err := owner.ImportValue(func(owner *live.Owner) error {
		converted, err := func() (ProgressSink, error) {
			var value ProgressSink
			if err := schema.ValidateExpressionRaw("ProgressSink", raw); err != nil {
				return value, err
			}
			var wire map[string]json.RawMessage
			if err := json.Unmarshal(raw, &wire); err != nil {
				return value, err
			}
			if member, present := wire["report"]; present {
				var held Report
				heldConverted, err := ImportReport(owner, member)
				if err != nil {
					return value, err
				}
				held = heldConverted
				value.Report = held
			}
			return value, nil
		}()
		value = converted
		return err
	})
	if err != nil {
		var zero ProgressSink
		return zero, err
	}
	return value, nil
}

// Rename: Renames the job and answers what it is now called.
// A value of it is one implementation, called across the seam; each is its own binding, with its own lifetime.
type Rename = func(ctx context.Context, params Ticket) (Ticket, error)

// ContractRename is the declaration a reference to Rename carries. It is nominal: a reference is usable exactly where this callable is expected.
const ContractRename = "worker/Rename"

// ExportRename makes a binding of a local Rename and writes the reference that names it.
func ExportRename(owner *live.Owner, v Rename) (json.RawMessage, error) {
	if owner == nil {
		return nil, fmt.Errorf("Rename: a live value is exported into an owner")
	}
	if v == nil {
		return nil, fmt.Errorf("Rename: no implementation to export")
	}
	return owner.ExportValue(func(owner *live.Owner) (json.RawMessage, error) {
		reference, err := owner.Export(ContractRename, func(ctx context.Context, request json.RawMessage) (json.RawMessage, error) {
			owner := owner.Child()
			ctx = live.WithOwner(ctx, owner)
			if err := schema.ValidateExpressionRaw(MustTypeExpression("\"Ticket\""), request); err != nil {
				return nil, err
			}
			argument, err := func() (Ticket, error) {
				var value Ticket
				err := owner.ImportValue(func(owner *live.Owner) error {
					converted, err := func() (Ticket, error) {
						var zero Ticket
						if err := schema.ValidateExpressionRaw(MustTypeExpression("\"Ticket\""), request); err != nil {
							return zero, err
						}
						var converted Ticket
						if err := json.Unmarshal(request, &converted); err != nil {
							return zero, err
						}
						return converted, nil
					}()
					value = converted
					return err
				})
				if err != nil {
					var zero Ticket
					return zero, err
				}
				return value, nil
			}()
			if err != nil {
				return nil, err
			}
			result, err := v(ctx, argument)
			if err != nil {
				return nil, err
			}
			data, err := owner.ExportValue(func(owner *live.Owner) (json.RawMessage, error) {
				var zero json.RawMessage
				converted, err := runtime.MarshalJSON(result)
				if err != nil {
					return zero, err
				}
				if err := schema.ValidateExpressionRaw(MustTypeExpression("\"Ticket\""), converted); err != nil {
					return zero, err
				}
				return converted, nil
			})
			if err != nil {
				return nil, err
			}
			return data, nil
		})
		if err != nil {
			return nil, err
		}
		return runtime.MarshalJSON(reference)
	})
}

// ImportRename is a Rename that calls the binding a reference names.
func ImportRename(owner *live.Owner, raw json.RawMessage) (Rename, error) {
	if owner == nil {
		return nil, fmt.Errorf("Rename: a live value is imported into an owner")
	}
	reference, err := owner.Scope().Decode(raw)
	if err != nil {
		return nil, err
	}
	invoke, err := owner.Import(reference, ContractRename)
	if err != nil {
		return nil, err
	}
	scope := owner.Scope()
	return func(ctx context.Context, params Ticket) (Ticket, error) {
		owner := scope.Owner()
		var zero Ticket
		if supplied, ok := live.OwnerOf(ctx); ok {
			if supplied.Scope() != owner.Scope() {
				return zero, &runtime.PublicError{Code: live.ErrorReferenceForeign, Message: "the owner belongs to another connection"}
			}
			owner = supplied
		}
		request, err := owner.ExportValue(func(owner *live.Owner) (json.RawMessage, error) {
			var zero json.RawMessage
			converted, err := runtime.MarshalJSON(params)
			if err != nil {
				return zero, err
			}
			if err := schema.ValidateExpressionRaw(MustTypeExpression("\"Ticket\""), converted); err != nil {
				return zero, err
			}
			return converted, nil
		})
		if err != nil {
			return zero, err
		}
		result, err := invoke(ctx, request)
		if err != nil {
			return zero, err
		}
		if err := schema.ValidateExpressionRaw(MustTypeExpression("\"Ticket\""), result); err != nil {
			return zero, err
		}
		answer, err := func() (Ticket, error) {
			var value Ticket
			err := owner.ImportValue(func(owner *live.Owner) error {
				converted, err := func() (Ticket, error) {
					var zero Ticket
					if err := schema.ValidateExpressionRaw(MustTypeExpression("\"Ticket\""), result); err != nil {
						return zero, err
					}
					var converted Ticket
					if err := json.Unmarshal(result, &converted); err != nil {
						return zero, err
					}
					return converted, nil
				}()
				value = converted
				return err
			})
			if err != nil {
				var zero Ticket
				return zero, err
			}
			return value, nil
		}()
		if err != nil {
			return zero, err
		}
		return answer, nil
	}, nil
}

// Report: Told how far along the job is.
// A value of it is one implementation, called across the seam; each is its own binding, with its own lifetime.
type Report = func(ctx context.Context, params Percent) error

// ContractReport is the declaration a reference to Report carries. It is nominal: a reference is usable exactly where this callable is expected.
const ContractReport = "worker/Report"

// ExportReport makes a binding of a local Report and writes the reference that names it.
func ExportReport(owner *live.Owner, v Report) (json.RawMessage, error) {
	if owner == nil {
		return nil, fmt.Errorf("Report: a live value is exported into an owner")
	}
	if v == nil {
		return nil, fmt.Errorf("Report: no implementation to export")
	}
	return owner.ExportValue(func(owner *live.Owner) (json.RawMessage, error) {
		reference, err := owner.Export(ContractReport, func(ctx context.Context, request json.RawMessage) (json.RawMessage, error) {
			owner := owner.Child()
			ctx = live.WithOwner(ctx, owner)
			if err := schema.ValidateExpressionRaw(MustTypeExpression("\"Percent\""), request); err != nil {
				return nil, err
			}
			argument, err := func() (Percent, error) {
				var value Percent
				err := owner.ImportValue(func(owner *live.Owner) error {
					converted, err := func() (Percent, error) {
						var zero Percent
						if err := schema.ValidateExpressionRaw(MustTypeExpression("\"Percent\""), request); err != nil {
							return zero, err
						}
						var converted Percent
						if err := json.Unmarshal(request, &converted); err != nil {
							return zero, err
						}
						return converted, nil
					}()
					value = converted
					return err
				})
				if err != nil {
					var zero Percent
					return zero, err
				}
				return value, nil
			}()
			if err != nil {
				return nil, err
			}
			return nil, v(ctx, argument)
		})
		if err != nil {
			return nil, err
		}
		return runtime.MarshalJSON(reference)
	})
}

// ImportReport is a Report that calls the binding a reference names.
func ImportReport(owner *live.Owner, raw json.RawMessage) (Report, error) {
	if owner == nil {
		return nil, fmt.Errorf("Report: a live value is imported into an owner")
	}
	reference, err := owner.Scope().Decode(raw)
	if err != nil {
		return nil, err
	}
	invoke, err := owner.Import(reference, ContractReport)
	if err != nil {
		return nil, err
	}
	scope := owner.Scope()
	return func(ctx context.Context, params Percent) error {
		owner := scope.Owner()
		if supplied, ok := live.OwnerOf(ctx); ok {
			if supplied.Scope() != owner.Scope() {
				return &runtime.PublicError{Code: live.ErrorReferenceForeign, Message: "the owner belongs to another connection"}
			}
			owner = supplied
		}
		request, err := owner.ExportValue(func(owner *live.Owner) (json.RawMessage, error) {
			var zero json.RawMessage
			converted, err := runtime.MarshalJSON(params)
			if err != nil {
				return zero, err
			}
			if err := schema.ValidateExpressionRaw(MustTypeExpression("\"Percent\""), converted); err != nil {
				return zero, err
			}
			return converted, nil
		})
		if err != nil {
			return err
		}
		result, err := invoke(ctx, request)
		if err != nil {
			return err
		}
		_ = result
		return nil
	}, nil
}

// ExportSinks writes Sinks as it travels: each callable in it becomes a binding of the owner, and the reference that names it takes its place.
func ExportSinks(owner *live.Owner, v Sinks) (json.RawMessage, error) {
	if owner == nil {
		return nil, fmt.Errorf("Sinks: a live value is exported into an owner")
	}
	return owner.ExportValue(func(owner *live.Owner) (json.RawMessage, error) {
		convertedMembers := make(map[string]json.RawMessage, len(v))
		for key, item := range v {
			element, err := ExportProgressSink(owner, item)
			if err != nil {
				return nil, err
			}
			convertedMembers[key] = element
		}
		converted, err := runtime.MarshalJSON(convertedMembers)
		if err != nil {
			return nil, err
		}
		return converted, nil
	})
}

// ImportSinks reads Sinks as it arrived: each reference in it becomes a typed proxy of the binding it names, so a handler is given native values.
func ImportSinks(owner *live.Owner, raw json.RawMessage) (Sinks, error) {
	var value Sinks
	if owner == nil {
		return value, fmt.Errorf("Sinks: a live value is imported into an owner")
	}
	err := owner.ImportValue(func(owner *live.Owner) error {
		converted, err := func() (Sinks, error) {
			var value Sinks
			var convertedRaw map[string]json.RawMessage
			if err := json.Unmarshal(raw, &convertedRaw); err != nil {
				return value, err
			}
			converted := make(map[string]ProgressSink, len(convertedRaw))
			for key, item := range convertedRaw {
				element, err := ImportProgressSink(owner, item)
				if err != nil {
					return value, err
				}
				converted[key] = element
			}
			value = converted
			return value, nil
		}()
		value = converted
		return err
	})
	if err != nil {
		var zero Sinks
		return zero, err
	}
	return value, nil
}

// ExportStart writes Start as it travels: each callable in it becomes a binding of the owner, and the reference that names it takes its place.
func ExportStart(owner *live.Owner, v Start) (json.RawMessage, error) {
	if owner == nil {
		return nil, fmt.Errorf("Start: a live value is exported into an owner")
	}
	return owner.ExportValue(func(owner *live.Owner) (json.RawMessage, error) {
		wire := map[string]json.RawMessage{}
		var ticketMember json.RawMessage
		ticketMemberConverted, err := runtime.MarshalJSON(v.Ticket)
		if err != nil {
			return nil, err
		}
		ticketMember = ticketMemberConverted
		wire["ticket"] = ticketMember
		var progressMember json.RawMessage
		progressMemberConverted, err := ExportProgressSink(owner, v.Progress)
		if err != nil {
			return nil, err
		}
		progressMember = progressMemberConverted
		wire["progress"] = progressMember
		if v.Watchers.Present {
			var member json.RawMessage
			memberConverted, err := ExportWatchers(owner, v.Watchers.Value)
			if err != nil {
				return nil, err
			}
			member = memberConverted
			wire["watchers"] = member
		}
		data, err := runtime.MarshalObject([]string{"ticket", "progress", "watchers"}, wire)
		if err != nil {
			return nil, err
		}
		if err := schema.ValidateExpressionRaw("Start", data); err != nil {
			return nil, err
		}
		return data, nil
	})
}

// ImportStart reads Start as it arrived: each reference in it becomes a typed proxy of the binding it names, so a handler is given native values.
func ImportStart(owner *live.Owner, raw json.RawMessage) (Start, error) {
	var value Start
	if owner == nil {
		return value, fmt.Errorf("Start: a live value is imported into an owner")
	}
	err := owner.ImportValue(func(owner *live.Owner) error {
		converted, err := func() (Start, error) {
			var value Start
			if err := schema.ValidateExpressionRaw("Start", raw); err != nil {
				return value, err
			}
			var wire map[string]json.RawMessage
			if err := json.Unmarshal(raw, &wire); err != nil {
				return value, err
			}
			if member, present := wire["ticket"]; present {
				var held Ticket
				var heldConverted Ticket
				if err := json.Unmarshal(member, &heldConverted); err != nil {
					return value, err
				}
				held = heldConverted
				value.Ticket = held
			}
			if member, present := wire["progress"]; present {
				var held ProgressSink
				heldConverted, err := ImportProgressSink(owner, member)
				if err != nil {
					return value, err
				}
				held = heldConverted
				value.Progress = held
			}
			if member, present := wire["watchers"]; present && string(member) != "undefined" {
				var held Watchers
				heldConverted, err := ImportWatchers(owner, member)
				if err != nil {
					return value, err
				}
				held = heldConverted
				value.Watchers = runtime.Some(held)
			}
			return value, nil
		}()
		value = converted
		return err
	})
	if err != nil {
		var zero Start
		return zero, err
	}
	return value, nil
}

// ExportSupervise writes Supervise as it travels: each callable in it becomes a binding of the owner, and the reference that names it takes its place.
func ExportSupervise(owner *live.Owner, v Supervise) (json.RawMessage, error) {
	if owner == nil {
		return nil, fmt.Errorf("Supervise: a live value is exported into an owner")
	}
	return owner.ExportValue(func(owner *live.Owner) (json.RawMessage, error) {
		wire := map[string]json.RawMessage{}
		var sinksMember json.RawMessage
		sinksMemberConverted, err := ExportSinks(owner, v.Sinks)
		if err != nil {
			return nil, err
		}
		sinksMember = sinksMemberConverted
		wire["sinks"] = sinksMember
		data, err := runtime.MarshalObject([]string{"sinks"}, wire)
		if err != nil {
			return nil, err
		}
		if err := schema.ValidateExpressionRaw("Supervise", data); err != nil {
			return nil, err
		}
		return data, nil
	})
}

// ImportSupervise reads Supervise as it arrived: each reference in it becomes a typed proxy of the binding it names, so a handler is given native values.
func ImportSupervise(owner *live.Owner, raw json.RawMessage) (Supervise, error) {
	var value Supervise
	if owner == nil {
		return value, fmt.Errorf("Supervise: a live value is imported into an owner")
	}
	err := owner.ImportValue(func(owner *live.Owner) error {
		converted, err := func() (Supervise, error) {
			var value Supervise
			if err := schema.ValidateExpressionRaw("Supervise", raw); err != nil {
				return value, err
			}
			var wire map[string]json.RawMessage
			if err := json.Unmarshal(raw, &wire); err != nil {
				return value, err
			}
			if member, present := wire["sinks"]; present {
				var held Sinks
				heldConverted, err := ImportSinks(owner, member)
				if err != nil {
					return value, err
				}
				held = heldConverted
				value.Sinks = held
			}
			return value, nil
		}()
		value = converted
		return err
	})
	if err != nil {
		var zero Supervise
		return zero, err
	}
	return value, nil
}

// ExportWatchers writes Watchers as it travels: each callable in it becomes a binding of the owner, and the reference that names it takes its place.
func ExportWatchers(owner *live.Owner, v Watchers) (json.RawMessage, error) {
	if owner == nil {
		return nil, fmt.Errorf("Watchers: a live value is exported into an owner")
	}
	return owner.ExportValue(func(owner *live.Owner) (json.RawMessage, error) {
		convertedItems := make([]json.RawMessage, 0, len(v))
		for _, item := range v {
			var element json.RawMessage
			if item.Null {
				element = json.RawMessage("null")
			} else {
				elementHeld, err := ExportReport(owner, item.Value)
				if err != nil {
					return nil, err
				}
				element = elementHeld
			}
			convertedItems = append(convertedItems, element)
		}
		converted, err := runtime.MarshalJSON(convertedItems)
		if err != nil {
			return nil, err
		}
		return converted, nil
	})
}

// ImportWatchers reads Watchers as it arrived: each reference in it becomes a typed proxy of the binding it names, so a handler is given native values.
func ImportWatchers(owner *live.Owner, raw json.RawMessage) (Watchers, error) {
	var value Watchers
	if owner == nil {
		return value, fmt.Errorf("Watchers: a live value is imported into an owner")
	}
	err := owner.ImportValue(func(owner *live.Owner) error {
		converted, err := func() (Watchers, error) {
			var value Watchers
			var convertedRaw []json.RawMessage
			if err := json.Unmarshal(raw, &convertedRaw); err != nil {
				return value, err
			}
			converted := make([]runtime.Nullable[Report], 0, len(convertedRaw))
			for _, item := range convertedRaw {
				var element runtime.Nullable[Report]
				if string(item) == "null" {
					element = runtime.Null[Report]()
				} else {
					elementHeld, err := ImportReport(owner, item)
					if err != nil {
						return value, err
					}
					element = runtime.NonNull(elementHeld)
				}
				converted = append(converted, element)
			}
			value = converted
			return value, nil
		}()
		value = converted
		return err
	})
	if err != nil {
		var zero Watchers
		return zero, err
	}
	return value, nil
}

// The public errors of the family: what a handler returns, as the Code of a *runtime.PublicError, and a caller tells apart with IsError.
const (
	// ErrorDenied: The caller is denied.
	ErrorDenied = "denied"
	// ErrorGone: The job is no longer there.
	ErrorGone = "gone"
)

// Errors is every public error code the family declares.
var Errors = []string{ErrorDenied, ErrorGone}

// IsError reports whether an error is, or wraps, the family's public error of the code.
func IsError(err error, code string) bool {
	var public *runtime.PublicError
	return errors.As(err, &public) && public.Code == code
}
