// Code generated by nightseam. DO NOT EDIT.
package relayprotocol

import (
	context "context"
	json "encoding/json"
	runtime "github.com/Bitspark/nightseam/runtime/go"
)

// Tag is this family, as a type: what every record and enum of the package returns from Of, and what an entry point of a package generic in a family holds its type arguments to.
type Tag struct{}

// Carried: A message of the bound family, held as data. The parameter says the family has a live tier; what is drawn through it is data, which is why relaying one needs no live runtime of its own.
type Carried[SEnvelope, SHandle any] struct {
	Message SEnvelope                 `json:"message"`
	Back    runtime.Nullable[SHandle] `json:"back"`
}

func (v Carried[SEnvelope, SHandle]) MarshalJSON() ([]byte, error) {
	data, err := runtime.MarshalJSON((struct {
		Message SEnvelope                 `json:"message"`
		Back    runtime.Nullable[SHandle] `json:"back"`
	})(v))
	if err != nil {
		return nil, err
	}
	if err = schema.Bind(map[string]any{"S.Envelope": runtime.TypeArgument[SEnvelope](), "S.Handle": runtime.TypeArgument[SHandle]()}, nil).ValidateExpressionRaw("Carried", data); err != nil {
		return nil, err
	}
	return data, nil
}
func (v *Carried[SEnvelope, SHandle]) UnmarshalJSON(data []byte) error {
	if err := schema.Bind(map[string]any{"S.Envelope": runtime.TypeArgument[SEnvelope](), "S.Handle": runtime.TypeArgument[SHandle]()}, nil).ValidateExpressionRaw("Carried", data); err != nil {
		return err
	}
	var decoded (struct {
		Message SEnvelope                 `json:"message"`
		Back    runtime.Nullable[SHandle] `json:"back"`
	})
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*v = Carried[SEnvelope, SHandle](decoded)
	return nil
}
func (Carried[SEnvelope, SHandle]) Of() Tag { return Tag{} }
func (Carried[SEnvelope, SHandle]) WireType() runtime.TypeBinding {
	return runtime.TypeBinding{Schema: schema.Bind(map[string]any{"S.Envelope": runtime.TypeArgument[SEnvelope](), "S.Handle": runtime.TypeArgument[SHandle]()}, nil), Type: "Carried"}
}

// Envelope: One message of the nightseam.duplex/1 profile: the members the peer acts on, and nothing else.
type Envelope struct {
	Version     int64                               `json:"version"`
	Kind        string                              `json:"kind"`
	ID          runtime.Optional[string]            `json:"id,omitzero"`
	Method      runtime.Optional[string]            `json:"method,omitzero"`
	Params      runtime.Optional[any]               `json:"params,omitzero"`
	Result      runtime.Optional[any]               `json:"result,omitzero"`
	Error       runtime.Optional[any]               `json:"error,omitzero"`
	Event       runtime.Optional[string]            `json:"event,omitzero"`
	Data        runtime.Optional[any]               `json:"data,omitzero"`
	Traceparent runtime.Optional[string]            `json:"traceparent,omitzero"`
	Tracestate  runtime.Optional[string]            `json:"tracestate,omitzero"`
	Meta        runtime.Optional[map[string]string] `json:"meta,omitzero"`
}

func (v Envelope) MarshalJSON() ([]byte, error) {
	type wire Envelope
	data, err := runtime.MarshalJSON(wire(v))
	if err != nil {
		return nil, err
	}
	if err = schema.ValidateExpressionRaw("Envelope", data); err != nil {
		return nil, err
	}
	return data, nil
}
func (v *Envelope) UnmarshalJSON(data []byte) error {
	if err := schema.ValidateExpressionRaw("Envelope", data); err != nil {
		return err
	}
	type wire Envelope
	var decoded wire
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*v = Envelope(decoded)
	return nil
}
func (Envelope) Of() Tag { return Tag{} }
func (Envelope) WireType() runtime.TypeBinding {
	return runtime.TypeBinding{Schema: schema, Type: "Envelope"}
}

// Handle: A reference to a channel on the connection that carries the message holding it.
type Handle struct {
	Channel int64 `json:"channel"`
}

func (v Handle) MarshalJSON() ([]byte, error) {
	type wire Handle
	data, err := runtime.MarshalJSON(wire(v))
	if err != nil {
		return nil, err
	}
	if err = schema.ValidateExpressionRaw("Handle", data); err != nil {
		return nil, err
	}
	return data, nil
}
func (v *Handle) UnmarshalJSON(data []byte) error {
	if err := schema.ValidateExpressionRaw("Handle", data); err != nil {
		return err
	}
	type wire Handle
	var decoded wire
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*v = Handle(decoded)
	return nil
}
func (Handle) Of() Tag { return Tag{} }
func (Handle) WireType() runtime.TypeBinding {
	return runtime.TypeBinding{Schema: schema, Type: "Handle"}
}

// ExportCarried writes Carried using the supplied conversion for each type argument.
func ExportCarried[SEnvelope, SHandle any](v Carried[SEnvelope, SHandle], convertSEnvelope func(SEnvelope) (json.RawMessage, error), typeSEnvelope runtime.TypeBinding, convertSHandle func(SHandle) (json.RawMessage, error), typeSHandle runtime.TypeBinding) (json.RawMessage, error) {
	wire := map[string]json.RawMessage{}
	var messageMember json.RawMessage
	messageMemberConverted, err := convertSEnvelope(v.Message)
	if err != nil {
		return nil, err
	}
	messageMember = messageMemberConverted
	wire["message"] = messageMember
	var backMember json.RawMessage
	var backMemberConverted json.RawMessage
	if v.Back.Null {
		backMemberConverted = json.RawMessage("null")
	} else {
		backMemberConvertedHeld, err := convertSHandle(v.Back.Value)
		if err != nil {
			return nil, err
		}
		backMemberConverted = backMemberConvertedHeld
	}
	backMember = backMemberConverted
	wire["back"] = backMember
	data, err := runtime.MarshalObject([]string{"message", "back"}, wire)
	if err != nil {
		return nil, err
	}
	if err := schema.Bind(map[string]any{"S.Envelope": typeSEnvelope, "S.Handle": typeSHandle}, nil).ValidateExpressionRaw("Carried", data); err != nil {
		return nil, err
	}
	return data, nil
}

// ImportCarried reads Carried using the supplied conversion for each type argument.
func ImportCarried[SEnvelope, SHandle any](raw json.RawMessage, convertSEnvelope func(json.RawMessage) (SEnvelope, error), typeSEnvelope runtime.TypeBinding, convertSHandle func(json.RawMessage) (SHandle, error), typeSHandle runtime.TypeBinding) (Carried[SEnvelope, SHandle], error) {
	var value Carried[SEnvelope, SHandle]
	if err := schema.Bind(map[string]any{"S.Envelope": typeSEnvelope, "S.Handle": typeSHandle}, nil).ValidateExpressionRaw("Carried", raw); err != nil {
		return value, err
	}
	var wire map[string]json.RawMessage
	if err := json.Unmarshal(raw, &wire); err != nil {
		return value, err
	}
	if member, present := wire["message"]; present {
		var held SEnvelope
		heldConverted, err := convertSEnvelope(member)
		if err != nil {
			return value, err
		}
		held = heldConverted
		value.Message = held
	}
	if member, present := wire["back"]; present {
		var held runtime.Nullable[SHandle]
		var heldConverted runtime.Nullable[SHandle]
		if string(member) == "null" {
			heldConverted = runtime.Null[SHandle]()
		} else {
			heldConvertedHeld, err := convertSHandle(member)
			if err != nil {
				return value, err
			}
			heldConverted = runtime.NonNull(heldConvertedHeld)
		}
		held = heldConverted
		value.Back = held
	}
	return value, nil
}

// AdapterCarried composes declaration validation and conversion within the supplied invocation context.
func AdapterCarried[SEnvelope, SHandle any](adapterSEnvelope runtime.ValueAdapter[SEnvelope], adapterSHandle runtime.ValueAdapter[SHandle]) runtime.ValueAdapter[Carried[SEnvelope, SHandle]] {
	typeSEnvelope := adapterSEnvelope.Binding
	typeSHandle := adapterSHandle.Binding
	binding := runtime.TypeBinding{Schema: schema.Bind(map[string]any{"S.Envelope": typeSEnvelope, "S.Handle": typeSHandle}, nil), Type: "Carried"}
	return runtime.ValueAdapter[Carried[SEnvelope, SHandle]]{
		Binding:      binding,
		NeedsContext: adapterSEnvelope.NeedsContext || adapterSHandle.NeedsContext,
		Export: func(ctx context.Context, value Carried[SEnvelope, SHandle]) (json.RawMessage, error) {
			raw, err := ExportCarried[SEnvelope, SHandle](value, func(value SEnvelope) (json.RawMessage, error) { return adapterSEnvelope.Export(ctx, value) }, typeSEnvelope, func(value SHandle) (json.RawMessage, error) { return adapterSHandle.Export(ctx, value) }, typeSHandle)
			if err == nil {
				err = binding.Schema.ValidateExpressionRaw(binding.Type, raw)
			}
			return raw, err
		},
		Import: func(ctx context.Context, raw json.RawMessage) (Carried[SEnvelope, SHandle], error) {
			var zero Carried[SEnvelope, SHandle]
			if err := binding.Schema.ValidateExpressionRaw(binding.Type, raw); err != nil {
				return zero, err
			}
			return ImportCarried[SEnvelope, SHandle](raw, func(value json.RawMessage) (SEnvelope, error) { return adapterSEnvelope.Import(ctx, value) }, typeSEnvelope, func(value json.RawMessage) (SHandle, error) { return adapterSHandle.Import(ctx, value) }, typeSHandle)
		},
	}
}

type ServerMethods[SEnvelope, SHandle any] interface {
	Relay(ctx context.Context, params Carried[SEnvelope, SHandle]) (SEnvelope, error)
}
type ServerEvents[SEnvelope, SHandle any] interface {
}
type Server[SEnvelope, SHandle any] struct {
	Methods ServerMethods[SEnvelope, SHandle]
	Events  ServerEvents[SEnvelope, SHandle]
}
type ClientMethods[SEnvelope, SHandle any] interface {
}
type ClientEvents[SEnvelope, SHandle any] interface {
}
type Client[SEnvelope, SHandle any] struct {
	Methods ClientMethods[SEnvelope, SHandle]
	Events  ClientEvents[SEnvelope, SHandle]
}
type ServerModel[SEnvelope, SHandle any] func(Client[SEnvelope, SHandle]) (Server[SEnvelope, SHandle], error)
type ClientModel[SEnvelope, SHandle any] func(Server[SEnvelope, SHandle]) (Client[SEnvelope, SHandle], error)
