// Code generated by nightseam. DO NOT EDIT.
package relayprotocol

import (
	json "encoding/json"
	runtime "github.com/Bitspark/nightseam/runtime/go"
)

// Tag is this family, as a type: what every record and enum of the package returns from Of, and what an entry point of a package generic in a family holds its type arguments to.
type Tag struct{}

// Carried: A message of the bound family, held as data. The parameter says the family has a live tier; what is drawn through it is data, which is why relaying one needs no live runtime of its own.
type Carried[SEnvelope, SHandle any] struct {
	Message SEnvelope                 `json:"message"`
	Back    runtime.Nullable[SHandle] `json:"back"`
}

func (v Carried[SEnvelope, SHandle]) MarshalJSON() ([]byte, error) {
	data, err := runtime.MarshalJSON((struct {
		Message SEnvelope                 `json:"message"`
		Back    runtime.Nullable[SHandle] `json:"back"`
	})(v))
	if err != nil {
		return nil, err
	}
	if err = schema.Bind(map[string]any{"S.Envelope": runtime.TypeArgument[SEnvelope](), "S.Handle": runtime.TypeArgument[SHandle]()}, nil).ValidateExpressionRaw("Carried", data); err != nil {
		return nil, err
	}
	return data, nil
}
func (v *Carried[SEnvelope, SHandle]) UnmarshalJSON(data []byte) error {
	if err := schema.Bind(map[string]any{"S.Envelope": runtime.TypeArgument[SEnvelope](), "S.Handle": runtime.TypeArgument[SHandle]()}, nil).ValidateExpressionRaw("Carried", data); err != nil {
		return err
	}
	var decoded (struct {
		Message SEnvelope                 `json:"message"`
		Back    runtime.Nullable[SHandle] `json:"back"`
	})
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*v = Carried[SEnvelope, SHandle](decoded)
	return nil
}
func (Carried[SEnvelope, SHandle]) Of() Tag { return Tag{} }
func (Carried[SEnvelope, SHandle]) WireType() runtime.TypeBinding {
	return runtime.TypeBinding{Schema: schema.Bind(map[string]any{"S.Envelope": runtime.TypeArgument[SEnvelope](), "S.Handle": runtime.TypeArgument[SHandle]()}, nil), Type: "Carried"}
}

// Envelope: One message of the nightseam.duplex/1 profile: the members the peer acts on, and nothing else.
type Envelope struct {
	Version     int64                               `json:"version"`
	Kind        string                              `json:"kind"`
	ID          runtime.Optional[string]            `json:"id,omitzero"`
	Method      runtime.Optional[string]            `json:"method,omitzero"`
	Params      runtime.Optional[any]               `json:"params,omitzero"`
	Result      runtime.Optional[any]               `json:"result,omitzero"`
	Error       runtime.Optional[any]               `json:"error,omitzero"`
	Event       runtime.Optional[string]            `json:"event,omitzero"`
	Data        runtime.Optional[any]               `json:"data,omitzero"`
	Traceparent runtime.Optional[string]            `json:"traceparent,omitzero"`
	Tracestate  runtime.Optional[string]            `json:"tracestate,omitzero"`
	Meta        runtime.Optional[map[string]string] `json:"meta,omitzero"`
}

func (v Envelope) MarshalJSON() ([]byte, error) {
	type wire Envelope
	data, err := runtime.MarshalJSON(wire(v))
	if err != nil {
		return nil, err
	}
	if err = schema.ValidateExpressionRaw("Envelope", data); err != nil {
		return nil, err
	}
	return data, nil
}
func (v *Envelope) UnmarshalJSON(data []byte) error {
	if err := schema.ValidateExpressionRaw("Envelope", data); err != nil {
		return err
	}
	type wire Envelope
	var decoded wire
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*v = Envelope(decoded)
	return nil
}
func (Envelope) Of() Tag { return Tag{} }
func (Envelope) WireType() runtime.TypeBinding {
	return runtime.TypeBinding{Schema: schema, Type: "Envelope"}
}

// Handle: A reference to a channel on the connection that carries the message holding it.
type Handle struct {
	Channel int64 `json:"channel"`
}

func (v Handle) MarshalJSON() ([]byte, error) {
	type wire Handle
	data, err := runtime.MarshalJSON(wire(v))
	if err != nil {
		return nil, err
	}
	if err = schema.ValidateExpressionRaw("Handle", data); err != nil {
		return nil, err
	}
	return data, nil
}
func (v *Handle) UnmarshalJSON(data []byte) error {
	if err := schema.ValidateExpressionRaw("Handle", data); err != nil {
		return err
	}
	type wire Handle
	var decoded wire
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*v = Handle(decoded)
	return nil
}
func (Handle) Of() Tag { return Tag{} }
func (Handle) WireType() runtime.TypeBinding {
	return runtime.TypeBinding{Schema: schema, Type: "Handle"}
}
