// Code generated by nightseam. DO NOT EDIT.
import { DuplexError, callWire, emitWire, registerWire, wirePair, type WireModelContext } from "@nightseam/runtime";
import { encodePath, type Wire } from '@nightseam/duplex';
import type { AdapterContext, ValueAdapter, ValueContext } from "@nightseam/runtime";
import { validateWire } from './types.ts';
import type * as Protocol from './types.ts';
import type { AnyFamily, FamilyBinding, Slots } from './types.ts';
import * as conversion from './types.ts';
import type * as probe from "@example/probe-client";
export * from './types.ts';
export { DuplexError };
export type { AdapterContext };
function makeAdapter<S extends AnyFamily = AnyFamily, T extends AnyFamily = AnyFamily>(context: AdapterContext, s: FamilyBinding<S>, t: FamilyBinding<T>) {
  const observer = context.options?.observer;
  const propagator = context.options?.propagator;
  const requestTimeoutMs = context.options?.requestTimeoutMs;
  const bindings = { s, t };
  const slots: Slots = { "S": s, "T": t };
  function hasModelHandler(facet: object, name: string): boolean {
    for (let current = facet; current !== null && current !== Object.prototype; current = Object.getPrototypeOf(current)) {
      if (Object.prototype.hasOwnProperty.call(current, name)) return typeof (facet as Record<string, unknown>)[name] === 'function';
    }
    return false;
  }
  function proxyServer(wire: Wire): Protocol.Server<S, T> {
    return {
      methods: {
        async named(params, context) {
          const options = { context, signal: context?.signal, timeoutMs: context?.timeoutMs ?? requestTimeoutMs, meta: context?.outgoingMeta, observer, propagator, family: "pair" };
          validateWire("Named", params, '$', slots);
          const result = await callWire<Protocol.Named>(wire, ["named"], params, options);
          validateWire("Named", result, '$', slots);
          return result;
        },
        async relay(params, context) {
          const options = { context, signal: context?.signal, timeoutMs: context?.timeoutMs ?? requestTimeoutMs, meta: context?.outgoingMeta, observer, propagator, family: "pair" };
          validateWire("T.Envelope", params, '$', slots);
          const result = await callWire<Protocol.Both<S, T>>(wire, ["relay"], params, options);
          validateWire("Both", result, '$', slots);
          return result;
        },
      },
      events: {
      },
    };
  }
  function bindServer(wire: Wire, implementation: Protocol.Server<S, T>): void {
    if (!implementation?.methods || !implementation.events) throw new Error('model methods and events are required');
    if (!hasModelHandler(implementation.methods, "named")) throw new Error("handler for named is required");
    if (!hasModelHandler(implementation.methods, "relay")) throw new Error("handler for relay is required");
    const detach: Array<() => void> = [];
    try {
      detach.push(registerWire(wire, ["named"], {
        observer, family: "pair",
        request: async (raw, context) => {
          try { validateWire("Named", raw, '$', slots); } catch (error) { throw new DuplexError('invalid_params', String(error)); }
          const params = raw as Protocol.Named;
          const result = await implementation.methods.named(params as Protocol.Named, context);
          return (() => { const converted = result; validateWire("Named", converted, '$', slots); return converted; })();
        },
      }));
      detach.push(registerWire(wire, ["relay"], {
        observer, family: "pair",
        request: async (raw, context) => {
          try { validateWire("T.Envelope", raw, '$', slots); } catch (error) { throw new DuplexError('invalid_params', String(error)); }
          const params = raw as T["Envelope"];
          const result = await implementation.methods.relay(params as T["Envelope"], context);
          return (() => { const converted = result; validateWire("Both", converted, '$', slots); return converted; })();
        },
      }));
    } catch (error) { for (const remove of detach.reverse()) remove(); throw error; }
  }
  function proxyClient(wire: Wire): Protocol.Client<S, T> {
    return {
      methods: {
      },
      events: {
        async echoed(data, context) {
          const options = { context, meta: context?.outgoingMeta, observer, propagator, family: "pair" };
          validateWire("Echo", data, '$', slots);
          emitWire(wire, ["echoed"], data, options);
        },
      },
    };
  }
  function bindClient(wire: Wire, implementation: Protocol.Client<S, T>): void {
    if (!implementation?.methods || !implementation.events) throw new Error('model methods and events are required');
    if (!hasModelHandler(implementation.events, "echoed")) throw new Error("event handler for echoed is required");
    const detach: Array<() => void> = [];
    try {
      detach.push(registerWire(wire, ["echoed"], {
        observer, family: "pair",
        event: async (raw, context) => {
          try { validateWire("Echo", raw, '$', slots); } catch (error) { wire.close(); throw error; }
          await implementation.events.echoed(raw as Protocol.Echo<T>, context);
        },
      }));
    } catch (error) { for (const remove of detach.reverse()) remove(); throw error; }
  }
  return { proxyServer, proxyClient, bindServer, bindClient };
}
/** Exposes one model session at a new local wire origin. */
export function toWire<S extends AnyFamily = AnyFamily, T extends AnyFamily = AnyFamily>(model: Protocol.ClientModel<S, T>, context: AdapterContext, s: FamilyBinding<S>, t: FamilyBinding<T>): Wire {
  const adapter = makeAdapter<S, T>(context, s, t);
  const [access, binding] = wirePair({ ...context.options, families: { ...context.options?.families, [encodePath(["named"])]: "pair", [encodePath(["relay"])]: "pair", [encodePath(["echoed"])]: "pair" } });
  try { const implementation = model(adapter.proxyServer(binding)); adapter.bindClient(binding, implementation); return access; } catch (error) { access.close(); throw error; }
}
/** Interprets a wire as the same model factory; the resulting session binds once. */
export async function fromWire<S extends AnyFamily = AnyFamily, T extends AnyFamily = AnyFamily>(wire: Wire, context: AdapterContext, s: FamilyBinding<S>, t: FamilyBinding<T>): Promise<Protocol.ClientModel<S, T>> {
  const adapter = makeAdapter<S, T>(context, s, t);
  let bound = false;
  return remote => {
    if (bound) throw new DuplexError('already_bound', 'model already bound');
    bound = true;
    adapter.bindServer(wire, remote);
    return adapter.proxyClient(wire);
  };
}
