// Code generated by nightseam. DO NOT EDIT.
package celltest

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	errors "errors"
	adapter "example.test/generated/api/go/cell-binding"
	protocol "example.test/generated/api/go/cell-protocol"
	fmt "fmt"
	bitwire "github.com/Bitspark/bitwire/wire/go"
	duplex "github.com/Bitspark/nightseam/duplex/go"
	runtime "github.com/Bitspark/nightseam/runtime/go"
	reflect "reflect"
	sync "sync"
)

type Presentation func(context.Context, bitwire.Endpoint) (bitwire.Endpoint, func(), error)
type Options struct {
	Context       runtime.AdapterContext
	RemoteContext runtime.AdapterContext
	Presentation  Presentation
	Inputs        map[string]any
	Equal         func(string, any, any) error
}

func once(f func()) func() { var once sync.Once; return func() { once.Do(f) } }

// Local keeps the bounded asynchronous wire created by ToWire.
func Local(_ context.Context, wire bitwire.Endpoint) (bitwire.Endpoint, func(), error) {
	return wire, func() {}, nil
}

// Mounted selects a nonempty origin from a mount without allocating a carrier.
func Mounted(_ context.Context, wire bitwire.Endpoint) (bitwire.Endpoint, func(), error) {
	root := duplex.Mount(map[string]bitwire.Endpoint{"family": wire})
	dispatcher, err := runtime.NewDispatcher(root)
	if err != nil {
		_ = root.Close(1000, "")
		return nil, nil, err
	}
	return dispatcher.Select([]string{"family"}), once(func() { _ = dispatcher.Close(1000, ""); _ = root.Close(1000, "") }), nil
}

// Forwarded introduces one local forwarding hop.
func Forwarded(_ context.Context, wire bitwire.Endpoint) (bitwire.Endpoint, func(), error) {
	left, right, err := runtime.NewWirePair(runtime.Options{})
	if err != nil {
		return nil, nil, err
	}
	detach, err := runtime.ForwardWire(right, wire)
	if err != nil {
		_ = left.Close(1000, "")
		return nil, nil, err
	}
	return left, once(func() { detach(); _ = left.Close(1000, "") }), nil
}

// Pipe carries real serialized frames between two prepared peers.
func Pipe(ctx context.Context, wire bitwire.Endpoint) (bitwire.Endpoint, func(), error) {
	left, right := duplex.Pipe(1 << 20)
	var detach func()
	server, err := runtime.NewPeer(ctx, right, runtime.ServerRole, runtime.Options{Prepare: func(peer *runtime.Peer) error {
		var err error
		detach, err = runtime.ForwardWire(peer.Wire(), wire)
		return err
	}})
	if err != nil {
		_ = left.Close(context.Background(), 1000, "")
		_ = right.Close(context.Background(), 1000, "")
		return nil, nil, err
	}
	client, err := runtime.NewPeer(ctx, left, runtime.ClientRole, runtime.Options{})
	if err != nil {
		if detach != nil {
			detach()
		}
		_ = server.Close()
		_ = left.Close(context.Background(), 1000, "")
		return nil, nil, err
	}
	return client.Wire(), once(func() { detach(); _ = client.Close(); _ = server.Close() }), nil
}

func compare(method string, expected, actual any, expectedErr, actualErr error, equal func(string, any, any) error) error {
	if expectedErr != nil || actualErr != nil {
		if expectedErr == nil || actualErr == nil {
			return fmt.Errorf("%s: direct error %v, round-trip error %v", method, expectedErr, actualErr)
		}
		code := func(err error) string {
			var public *runtime.PublicError
			if errors.As(err, &public) {
				return public.Code
			}
			return "internal"
		}
		if code(expectedErr) != code(actualErr) {
			return fmt.Errorf("%s: direct error %v, round-trip error %v", method, expectedErr, actualErr)
		}
		var expectedPublic, actualPublic *runtime.PublicError
		if errors.As(expectedErr, &expectedPublic) && errors.As(actualErr, &actualPublic) {
			return compare(method+".error", expectedPublic, actualPublic, nil, nil, nil)
		}
		return nil
	}
	if equal != nil {
		return equal(method, expected, actual)
	}
	a, err := runtime.MarshalJSON(expected)
	if err != nil {
		return fmt.Errorf("%s: result needs an Equal observer: %w", method, err)
	}
	b, err := runtime.MarshalJSON(actual)
	if err != nil {
		return fmt.Errorf("%s: round-trip result needs an Equal observer: %w", method, err)
	}
	var x, y any
	da, db := json.NewDecoder(bytes.NewReader(a)), json.NewDecoder(bytes.NewReader(b))
	da.UseNumber()
	db.UseNumber()
	if err = da.Decode(&x); err != nil {
		return err
	}
	if err = db.Decode(&y); err != nil {
		return err
	}
	if !reflect.DeepEqual(x, y) {
		return fmt.Errorf("%s: direct and round-trip results differ: %s / %s", method, a, b)
	}
	return nil
}

// Pair presents one fresh model over a frame pipe by default. The returned factory is bound once.
func Pair[T any](ctx context.Context, model protocol.ServerModel[T], options Options, adapterT runtime.ValueAdapter[T]) (protocol.ServerModel[T], func(), error) {
	wire, err := adapter.ToWire[T](model, options.Context, adapterT)
	if err != nil {
		return nil, nil, err
	}
	present := options.Presentation
	if present == nil {
		present = Pipe
	}
	view, detach, err := present(ctx, wire)
	if err != nil {
		if detach != nil {
			detach()
		}
		_ = wire.Close(1000, "")
		return nil, nil, err
	}
	close := once(func() {
		if detach != nil {
			detach()
		}
		_ = wire.Close(1000, "")
	})
	complete, unbind, err := adapter.PrepareFromWire[T](view, options.RemoteContext, adapterT)
	if err != nil {
		close()
		return nil, nil, err
	}
	stop := once(func() { unbind(); close() })
	paired, err := complete(ctx)
	if err != nil {
		stop()
		return nil, nil, err
	}
	return paired, stop, nil
}

type candidate struct {
	raw    string
	reason string
}

var examples = map[string]candidate{
	"Put": {raw: "{\"value\":\"‹value›\"}", reason: ""},
}

// Example validates the document's candidate against T; incompatible generic witnesses fail explicitly.
func Example[T any](name string) (T, error) {
	var zero T
	c, ok := examples[name]
	if !ok {
		return zero, fmt.Errorf("unknown example %s", name)
	}
	if c.reason != "" {
		return zero, fmt.Errorf("example %s unavailable: %s", name, c.reason)
	}
	return runtime.JSONAdapter[T]().Import(context.Background(), json.RawMessage(c.raw))
}

// Smoke calls every method and compares two freshly constructed equivalent models.
// Inputs supplies native witnesses by wire method name; Equal supplies live observational equivalence.
type observingMethods[T any] struct {
	inner protocol.ServerMethods[T]
	check func(string, any) error
}

func (o observingMethods[T]) Get(ctx context.Context) (T, error) {
	if err := o.check("get", nil); err != nil {
		var zero T
		return zero, err
	}
	return o.inner.Get(ctx)
}
func (o observingMethods[T]) Replace(ctx context.Context, params protocol.Put[T]) (int64, error) {
	if err := o.check("replace", params); err != nil {
		var zero int64
		return zero, err
	}
	return o.inner.Replace(ctx, params)
}
func Smoke[T any](ctx context.Context, model protocol.ServerModel[T], opposite protocol.Client[T], options Options, adapterT runtime.ValueAdapter[T]) error {
	if model == nil {
		return fmt.Errorf("model factory is required")
	}
	var mutex sync.Mutex
	inputs := map[string]any{}
	seen := map[string]uint64{}
	var inputError error
	_ = inputError
	check := func(method string, actual any) error {
		mutex.Lock()
		seen[method]++
		expected, tracked := inputs[method]
		delete(inputs, method)
		mutex.Unlock()
		if !tracked {
			return nil
		}
		err := compare(method+".request", expected, actual, nil, nil, options.Equal)
		if err != nil {
			mutex.Lock()
			inputError = err
			mutex.Unlock()
		}
		return err
	}
	observed := func(remote protocol.Client[T]) (protocol.Server[T], error) {
		value, err := model(remote)
		if err == nil {
			if value.Methods == nil {
				return value, fmt.Errorf("model methods are required")
			}
			value.Methods = observingMethods[T]{inner: value.Methods, check: check}
		}
		return value, err
	}
	paired, stop, err := Pair[T](ctx, observed, options, adapterT)
	if err != nil {
		return err
	}
	defer stop()
	remote, err := paired(opposite)
	if err != nil {
		return err
	}
	direct, err := model(opposite)
	if err != nil {
		return err
	}
	_ = remote
	_ = direct
	{
		if options.Equal == nil && (adapterT.NeedsContext) {
			return fmt.Errorf("get: requires an Equal observer for live values")
		}
		mutex.Lock()
		inputs["get"] = nil
		before := seen["get"]
		mutex.Unlock()
		actual, actualErr := remote.Methods.Get(ctx)
		mutex.Lock()
		observedError := inputError
		called := seen["get"] > before
		mutex.Unlock()
		if observedError != nil {
			return observedError
		}
		if !called {
			return fmt.Errorf("get: model was not reached: %v", actualErr)
		}
		expected, expectedErr := direct.Methods.Get(ctx)
		if err := compare("get", expected, actual, expectedErr, actualErr, options.Equal); err != nil {
			return err
		}
	}
	{
		var input protocol.Put[T]
		if supplied, ok := options.Inputs["replace"]; ok {
			var valid bool
			input, valid = supplied.(protocol.Put[T])
			if !valid {
				return fmt.Errorf("input replace has the wrong native type")
			}
		} else {
			if adapterT.NeedsContext {
				return fmt.Errorf("input replace needs a caller-supplied native value")
			}
			if err := json.Unmarshal([]byte("{\"value\":\"‹value›\"}"), &input); err != nil {
				return fmt.Errorf("input replace unavailable for this instantiation: %w", err)
			}
		}
		if options.Equal == nil && (adapterT.NeedsContext) {
			return fmt.Errorf("replace: requires an Equal observer for live values")
		}
		mutex.Lock()
		inputs["replace"] = input
		before := seen["replace"]
		mutex.Unlock()
		actual, actualErr := remote.Methods.Replace(ctx, input)
		mutex.Lock()
		observedError := inputError
		called := seen["replace"] > before
		mutex.Unlock()
		if observedError != nil {
			return observedError
		}
		if !called {
			return fmt.Errorf("replace: model was not reached: %v", actualErr)
		}
		expected, expectedErr := direct.Methods.Replace(ctx, input)
		if err := compare("replace", expected, actual, expectedErr, actualErr, options.Equal); err != nil {
			return err
		}
	}
	return nil
}
