// Code generated by nightseam. DO NOT EDIT.
import { DuplexPeer, DuplexError, type PeerOptions, type CallOptions, type EmitOptions, type RequestContext, type EventContext, type FrameConnection, type WebSocketLike } from "@nightseam/runtime";
import { validateWire } from "@example/codex-client/types";
import type * as Protocol from "@example/codex-client/types";
export * from "@example/codex-client/types";
export { DuplexError };
/** Typed handlers for the declaration's server side. */
export interface Handler {
  echo(params: Protocol.Payload, remote: Remote, context: RequestContext): Protocol.Payload | Promise<Protocol.Payload>;
  noArgs(params: Record<string, never>, remote: Remote, context: RequestContext): string | Promise<string>;
}
/** Client-originated event listeners installed before the connection reads its first frame. */
export interface Events {
}
/** Typed reverse calls and events for one connected client. */
export class Remote {
  readonly peer: DuplexPeer;
  constructor(peer: DuplexPeer) {
    this.peer = peer;
  }
  close(): void { this.peer.close(); }
  async reverse(params: Protocol.Payload, options?: CallOptions): Promise<Protocol.Payload> { validateWire("Payload", params); const result = await this.peer.call<Protocol.Payload>("reverse", params, options); validateWire("Payload", result); return result; }
  async emitChanged(data: Protocol.Payload, options?: EmitOptions): Promise<void> { validateWire("Payload", data); await this.peer.emit("changed", data, options); }
}
/** Installs the typed binding before a host-configured peer starts reading. An existing live scope is preserved. */
export function install(peer: DuplexPeer, handler: Handler, events: Events = {}): Remote {
  if (!handler) throw new Error('handler is required');
  if (typeof handler.echo !== 'function') throw new Error("handler for echo is required");
  if (typeof handler.noArgs !== 'function') throw new Error("handler for no_args is required");
  const remote = new Remote(peer);
  peer.handle("echo", async (params, context) => { try { validateWire("Payload", params); } catch(error) { throw new DuplexError('invalid_params', String(error)); } const result = await handler.echo(params as Protocol.Payload, remote, context); validateWire("Payload", result); return result; });
  peer.handle("no_args", async (params, context) => { try { validateWire({ empty: true }, params); } catch(error) { throw new DuplexError('invalid_params', String(error)); } const result = await handler.noArgs(params as Record<string, never>, remote, context); validateWire("string", result); return result; });
  return remote;
}
/** Serves an externally authenticated accepted connection. The returned peer is the caller's to close. */
export async function serve(connection: FrameConnection | WebSocketLike, options: PeerOptions, handler: Handler, events: Events = {}): Promise<DuplexPeer> {
  const peer = new DuplexPeer({ ...{ ...options, families: { ...options.families, "echo": "codex", "no_args": "codex", "reverse": "codex", "changed": "codex" } }, role: 'server' });
  try { install(peer, handler, events); await peer.attach(connection); return peer; } catch (error) { peer.close(); throw error; }
}
