package main

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// The authority profile over generated Go↔TypeScript sockets (#356): the
// real exchange with the tables' keys and proofs, a guarded generated
// model in each language serving the other, expiry at use through a clock
// the test moves, emissions per recipient, reverse calls and supplied
// callables — the routes the synthetic witness of #355 ran, now under the
// profile. The fixture is the worker family of the witness, generated by
// the public generator; the program under testdata/auth-profile is what
// runs.
func TestAuthProfile(t *testing.T) {
	root := repositoryRoot(t)
	tsc := fixture(t, root, "go", "node", "tsc")
	directory := t.TempDir()
	copyFixtureTree(t, "testdata/auth-profile/api/contracts", filepath.Join(directory, "api/contracts"))
	if out, errs, err := run(t, directory, "generate"); err != nil {
		t.Fatalf("AUTH-PROFILE generation: %v\n%s\n%s", err, out, errs)
	}
	fixtureModuleWithProfile(t, directory, root)
	for _, component := range []string{"runtime", "duplex", "live", "auth"} {
		copyFixtureTree(t, filepath.Join(root, component, "ts"), filepath.Join(directory, component, "ts"))
	}
	table, err := os.ReadFile(filepath.Join(root, "conformance", "tables", "auth-exposure.json"))
	if err != nil {
		t.Fatal(err)
	}
	writeFixture(t, directory, "auth-exposure.json", table)
	copyProgram(t, "testdata/auth-profile", directory, ".go")
	copyProgram(t, "testdata/auth-profile", directory, ".ts")
	writeFixture(t, directory, "runtime-loader.mjs", []byte(profileLoader(root)))
	writeFixture(t, directory, "package.json", []byte(`{"type":"module"}`))
	paths := fixtureTypeScriptPaths(t, directory)
	paths["@nightseam/auth"] = []string{"./auth/ts/src/index.ts"}
	for _, module := range []string{"grant", "connection", "exposure", "over"} {
		paths["@nightseam/auth/"+module] = []string{"./auth/ts/src/" + module + ".ts"}
	}
	installed := filepath.ToSlash(filepath.Join(root, "auth", "ts", "node_modules"))
	paths["@bitspark/archon"] = []string{installed + "/@bitspark/archon/dist/src/index.d.ts"}
	paths["@bitspark/archon-sdk"] = []string{installed + "/@bitspark/archon-sdk/dist/src/index.d.ts"}
	paths["@noble/hashes/sha2.js"] = []string{installed + "/@noble/hashes/sha2.d.ts"}
	config, err := json.Marshal(map[string]any{
		"compilerOptions": map[string]any{"target": "ES2022", "module": "NodeNext", "moduleResolution": "NodeNext", "strict": true, "skipLibCheck": true, "noEmit": true, "allowImportingTsExtensions": true, "paths": paths, "typeRoots": []string{filepath.Join(root, "node_modules/@types")}, "types": []string{"node"}},
		"include":         []string{"api/ts/**/*.ts", "profile.ts"},
	})
	if err != nil {
		t.Fatal(err)
	}
	writeFixture(t, directory, "tsconfig.json", config)
	runFixture(t, directory, "node", tsc, "--project", "tsconfig.json")
	runFixture(t, directory, "go", "test", "-count=1", "-v", ".")
}

// fixtureModuleWithProfile is fixtureModule with the nested auth module
// beside the root: required at its development version and replaced with
// this checkout's, its identity layer's requirements and sums carried over.
func fixtureModuleWithProfile(t *testing.T, directory, root string) {
	t.Helper()
	fixtureModule(t, directory, root)
	authModule, err := os.ReadFile(filepath.Join(root, "auth", "go", "go.mod"))
	if err != nil {
		t.Fatal(err)
	}
	var requires []string
	for line := range strings.Lines(strings.ReplaceAll(string(authModule), "\r\n", "\n")) {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "github.com/Bitspark/archon/") || strings.HasPrefix(line, "filippo.io/") {
			requires = append(requires, "\t"+strings.TrimSuffix(line, " // indirect"))
		}
	}
	manifest, err := os.ReadFile(filepath.Join(directory, "go.mod"))
	if err != nil {
		t.Fatal(err)
	}
	// The nested module requires the root module at the released number, so
	// the fixture must too: minimal version selection would raise its v0.0.0
	// to that, and a read-only build refuses to rewrite the manifest. The
	// replace makes either this checkout.
	released := requirement(t, authModule, "github.com/Bitspark/nightseam")
	extended := strings.Replace(string(manifest), "require github.com/Bitspark/nightseam v0.0.0", "require github.com/Bitspark/nightseam "+released, 1)
	extended += "\nrequire (\n" + strings.Join(requires, "\n") + "\n\tgithub.com/Bitspark/nightseam/auth/go v0.0.0\n)\n\nreplace github.com/Bitspark/nightseam/auth/go => " + filepath.ToSlash(filepath.Join(root, "auth", "go")) + "\n"
	writeFixture(t, directory, "go.mod", []byte(extended))
	rootSum, err := os.ReadFile(filepath.Join(root, "go.sum"))
	if err != nil {
		t.Fatal(err)
	}
	authSum, err := os.ReadFile(filepath.Join(root, "auth", "go", "go.sum"))
	if err != nil {
		t.Fatal(err)
	}
	writeFixture(t, directory, "go.sum", append(append([]byte{}, rootSum...), authSum...))
}

// requirement is the version a go.mod requires a module at.
func requirement(t *testing.T, manifest []byte, module string) string {
	t.Helper()
	for line := range strings.Lines(strings.ReplaceAll(string(manifest), "\r\n", "\n")) {
		if version, ok := strings.CutPrefix(strings.TrimSpace(line), module+" "); ok {
			return strings.TrimSpace(strings.TrimSuffix(strings.TrimSpace(version), "// indirect"))
		}
	}
	t.Fatalf("%s is not required", module)
	return ""
}

// profileLoader is the runtime loader with the profile's package and its
// identity layer resolvable: the copied sources for @nightseam/auth and its
// entry points, and the installed packages of this checkout — absolute
// paths, made file URLs where the loader runs — for what it depends on.
func profileLoader(root string) string {
	installed := filepath.ToSlash(filepath.Join(root, "auth", "ts", "node_modules"))
	return `import { pathToFileURL } from 'node:url';
export async function resolve(specifier,context,next){
  const map={'@nightseam/runtime':'./runtime/ts/src/index.ts','@nightseam/duplex':'./duplex/ts/src/index.ts','@nightseam/tunnel':'./tunnel/ts/src/index.ts','@nightseam/live':'./live/ts/src/index.ts',
    '@nightseam/auth':'./auth/ts/src/index.ts','@nightseam/auth/grant':'./auth/ts/src/grant.ts','@nightseam/auth/connection':'./auth/ts/src/connection.ts','@nightseam/auth/exposure':'./auth/ts/src/exposure.ts','@nightseam/auth/over':'./auth/ts/src/over.ts'};
  const installed={'@bitspark/archon':'` + installed + `/@bitspark/archon/dist/src/index.js','@bitspark/archon-sdk':'` + installed + `/@bitspark/archon-sdk/dist/src/index.js','@noble/hashes/sha2.js':'` + installed + `/@noble/hashes/sha2.js'};
  const name=specifier.slice('@example/'.length);
  const generated=name.endsWith('/types')?'./api/ts/'+name.slice(0,-6)+'/src/types.ts':'./api/ts/'+name+'/src/index.ts';
  const entry=map[specifier]??(specifier.startsWith('@example/')?generated:undefined);
  if(entry)return {url:new URL(entry,import.meta.url).href,shortCircuit:true};
  if(installed[specifier])return {url:pathToFileURL(installed[specifier]).href,shortCircuit:true};
  return next(specifier,context);
}
`
}
