package main

import (
	"encoding/json"
	"path/filepath"
	"testing"
)

// AUTH-SEAM (#355): an ordinary consumer guards the generated access surface
// with a synthetic connection context — over sockets, local pairs, tunnel
// channels, mounts, both generic forms and a replayed log — held to the
// exposure packet's construction and decision rules, in Go and against a
// TypeScript client. The fixture is generated by the public generator; the
// program under testdata/auth-seam is the witness.
func TestAuthSeam(t *testing.T) {
	root := repositoryRoot(t)
	tsc := fixture(t, root, "go", "node", "tsc")
	directory := t.TempDir()
	copyFixtureTree(t, "testdata/auth-seam/api/contracts", filepath.Join(directory, "api/contracts"))
	if out, errs, err := run(t, directory, "generate"); err != nil {
		t.Fatalf("AUTH-SEAM generation: %v\n%s\n%s", err, out, errs)
	}
	fixtureModule(t, directory, root)
	for _, component := range []string{"runtime", "duplex", "live"} {
		copyFixtureTree(t, filepath.Join(root, component, "ts"), filepath.Join(directory, component, "ts"))
	}
	copyProgram(t, "testdata/auth-seam", directory, ".go")
	copyProgram(t, "testdata/auth-seam", directory, ".ts")
	writeFixture(t, directory, "runtime-loader.mjs", []byte(runtimeLoader))
	writeFixture(t, directory, "package.json", []byte(`{"type":"module"}`))
	config, err := json.Marshal(map[string]any{
		"compilerOptions": map[string]any{"target": "ES2022", "module": "NodeNext", "moduleResolution": "NodeNext", "strict": true, "skipLibCheck": true, "noEmit": true, "allowImportingTsExtensions": true, "paths": fixtureTypeScriptPaths(t, directory), "typeRoots": []string{filepath.Join(root, "node_modules/@types")}, "types": []string{"node"}},
		"include":         []string{"api/ts/**/*.ts", "seam.ts"},
	})
	if err != nil {
		t.Fatal(err)
	}
	writeFixture(t, directory, "tsconfig.json", config)
	runFixture(t, directory, "node", tsc, "--project", "tsconfig.json")
	runFixture(t, directory, "go", "test", "-count=1", "-v", ".")
}
