// Code generated by nightseam. DO NOT EDIT.
import { DuplexError, callWire, emitWire, registerWire, wirePair, createDispatcher, declarationDigest, familyTypeAdapter, validateDrawnType, jsonAdapter, identityHandler, IDENTITY_METHOD, prepareIdentity, type HandlerRegistry, type WireModelContext, type WireCallOptions } from "@nightseam/runtime";
import { encodePath, type Wire, type Endpoint } from '@nightseam/duplex';
import type { AdapterContext, ValueAdapter, ValueContext } from "@nightseam/runtime";
import type { LiveOwner } from "@nightseam/live";
import { validateWire } from './types.ts';
import type * as Protocol from './types.ts';
import type { AnyFamily, FamilyBinding, Slots } from './types.ts';
import * as conversion from './types.ts';
export * from './types.ts';
export { DuplexError };
export type { AdapterContext };
function makeAdapter(context: AdapterContext) {
  const options = { ...context.options };
  const observer = options.observer;
  const propagator = options.propagator;
  const requestTimeoutMs = options.requestTimeoutMs;
  const bindings = {  };
  const slots: Slots = {  };
  const identity = { path: "probe", digest: declarationDigest(validateWire, slots) };
  const environment = context.valueEnvironment;
  if ((true) && !environment) throw new DuplexError('scope_closed', 'model adaptation requires an explicit value environment');
  function hasModelHandler(facet: object, name: string): boolean {
    for (let current = facet; current !== null && current !== Object.prototype; current = Object.getPrototypeOf(current)) {
      if (Object.prototype.hasOwnProperty.call(current, name)) return typeof (facet as Record<string, unknown>)[name] === 'function';
    }
    return false;
  }
  function proxyServer(wire: Wire): Protocol.Server {
    return {
      methods: {
        async echo(params, context) {
          const options = { context, signal: context?.signal, timeoutMs: context?.timeoutMs ?? requestTimeoutMs, meta: context?.outgoingMeta, observer, propagator, family: "probe" };
          validateWire("Payload", params);
          const result = await callWire<Protocol.Payload>(wire, ["echo"], params, options);
          validateWire("Payload", result);
          return result;
        },
        async watch(params, context) {
          const options = { context, signal: context?.signal, timeoutMs: context?.timeoutMs ?? requestTimeoutMs, meta: context?.outgoingMeta, observer, propagator, family: "probe" };
          const owner = (true || true) ? environment!.select((context as {valueContext?: unknown} | undefined)?.valueContext) : undefined;
          const result = await environment!.publish(owner, owner => environment!.export(owner, (owner) => { const converted = conversion.exportWatchUnchecked(owner as LiveOwner, (params) as Protocol.Watch); validateWire("Watch", converted); return converted; }), sent => callWire(wire, ["watch"], sent, options));
          validateWire("Subscription", result);
          return environment!.import(owner, (owner) => conversion.importSubscriptionUnchecked(owner as LiveOwner, result));
        },
      },
      events: {
      },
    };
  }
  function validateServer(implementation: Protocol.Server): void {
    if (!implementation?.methods || !implementation.events) throw new Error('model methods and events are required');
    if (!hasModelHandler(implementation.methods, "echo")) throw new Error("handler for echo is required");
    if (!hasModelHandler(implementation.methods, "watch")) throw new Error("handler for watch is required");
  }
  function bindServer(wire: HandlerRegistry, implementation: () => Protocol.Server): () => void {
    const detach: Array<() => void> = [];
    try {
      detach.push(registerWire(wire, ["echo"], {
        observer, family: "probe",
        request: async (raw, context) => {
          const target = implementation();
          try { validateWire("Payload", raw); } catch (error) { if (error instanceof DuplexError && error.code === 'contract_mismatch') throw error; throw new DuplexError('invalid_params', String(error)); }
          const params = raw as Protocol.Payload;
          const result = await target.methods.echo(params as Protocol.Payload, context);
          return (() => { const converted = result; validateWire("Payload", converted); return converted; })();
        },
      }));
      detach.push(registerWire(wire, ["watch"], {
        observer, family: "probe",
        request: async (raw, context) => {
          const target = implementation();
          try { validateWire("Watch", raw); } catch (error) { if (error instanceof DuplexError && error.code === 'contract_mismatch') throw error; throw new DuplexError('invalid_params', String(error)); }
          const owner = (true || true) ? environment!.child(undefined) : undefined; const ownedContext = Object.create(context) as WireModelContext & { valueContext: unknown }; if (owner !== undefined) Object.defineProperty(ownedContext, 'valueContext', { value: owner, enumerable: true });
          const params = environment!.import(owner, (owner) => conversion.importWatchUnchecked(owner as LiveOwner, raw));
          const result = await target.methods.watch(params as Protocol.Watch, ownedContext);
          return environment!.export(owner, (owner) => { const converted = conversion.exportSubscriptionUnchecked(owner as LiveOwner, (result) as Protocol.Subscription); validateWire("Subscription", converted); return converted; });
        },
      }));
    } catch (error) { for (const remove of detach.reverse()) remove(); throw error; }
    return () => { for (const remove of detach.reverse()) remove(); };
  }
  function proxyClient(wire: Wire): Protocol.Client {
    return {
      methods: {
        async reverse(params, context) {
          const options = { context, signal: context?.signal, timeoutMs: context?.timeoutMs ?? requestTimeoutMs, meta: context?.outgoingMeta, observer, propagator, family: "probe" };
          validateWire("Payload", params);
          const result = await callWire<Protocol.Payload>(wire, ["reverse"], params, options);
          validateWire("Payload", result);
          return result;
        },
      },
      events: {
        async changed(data, context) {
          const options = { context, meta: context?.outgoingMeta, observer, propagator, family: "probe" };
          validateWire("Payload", data);
          emitWire(wire, ["changed"], data, options);
        },
      },
    };
  }
  function validateClient(implementation: Protocol.Client): void {
    if (!implementation?.methods || !implementation.events) throw new Error('model methods and events are required');
    if (!hasModelHandler(implementation.methods, "reverse")) throw new Error("handler for reverse is required");
    if (!hasModelHandler(implementation.events, "changed")) throw new Error("event handler for changed is required");
  }
  function bindClient(wire: HandlerRegistry, implementation: () => Protocol.Client): () => void {
    const detach: Array<() => void> = [];
    try {
      detach.push(registerWire(wire, ["reverse"], {
        observer, family: "probe",
        request: async (raw, context) => {
          const target = implementation();
          try { validateWire("Payload", raw); } catch (error) { if (error instanceof DuplexError && error.code === 'contract_mismatch') throw error; throw new DuplexError('invalid_params', String(error)); }
          const params = raw as Protocol.Payload;
          const result = await target.methods.reverse(params as Protocol.Payload, context);
          return (() => { const converted = result; validateWire("Payload", converted); return converted; })();
        },
      }));
      detach.push(registerWire(wire, ["changed"], {
        observer, family: "probe",
        event: async (raw, context) => {
          const target = implementation();
          try { validateWire("Payload", raw); } catch (error) { wire.close(); throw error; }
          await target.events.changed(raw as Protocol.Payload, context);
        },
      }));
    } catch (error) { for (const remove of detach.reverse()) remove(); throw error; }
    return () => { for (const remove of detach.reverse()) remove(); };
  }
  return { options, identity, proxyServer, proxyClient, validateServer, validateClient, bindServer, bindClient };
}
/** Exposes one model session at a new local wire origin. */
export function toWire(model: Protocol.ClientModel, context: AdapterContext): Endpoint {
  const adapter = makeAdapter(context);
  const [access, binding] = wirePair({ ...adapter.options, families: { ...adapter.options.families, [encodePath(["echo"])]: "probe", [encodePath(["watch"])]: "probe", [encodePath(["reverse"])]: "probe", [encodePath(["changed"])]: "probe" } });
  try {
    const dispatcher = createDispatcher(binding, { ownEndpoint: true });
    registerWire(dispatcher, [IDENTITY_METHOD], { request: identityHandler(adapter.identity) });
    const implementation = model(adapter.proxyServer(binding));
    adapter.validateClient(implementation);
    adapter.bindClient(dispatcher, () => implementation);
    return access;
  } catch (error) { access.close(); throw error; }
}
/** Registers receivers before reading begins; complete checks identity before returning the one-use model factory. Close detaches this interpretation without closing its carrier. */
export function prepareFromWire(wire: Endpoint, context: AdapterContext): { complete(options?: WireCallOptions): Promise<Protocol.ClientModel>; close(): void } {
  const adapter = makeAdapter(context);
  const gate = prepareIdentity(wire, adapter.identity, adapter.options);
  let implementation: Protocol.Server | undefined;
  let completed = false, bound = false, closed = false;
  const detach: Array<() => void> = [];
  const cleanup = () => { if (closed) return; closed = true; implementation = undefined; gate.close(); for (const remove of detach.reverse()) remove(); };
  try {
    detach.push(adapter.bindServer(gate.wire, () => implementation!));
  } catch (error) { cleanup(); throw error; }
  return {
    async complete(options?: WireCallOptions): Promise<Protocol.ClientModel> {
      if (closed) throw new DuplexError('scope_closed', 'model interpretation is closed');
      if (completed) throw new DuplexError('already_bound', 'model interpretation already completed');
      completed = true;
      try { await gate.check(options); } catch (error) { cleanup(); throw error; }
      return remote => {
        if (closed) throw new DuplexError('scope_closed', 'model interpretation is closed');
        if (bound) throw new DuplexError('already_bound', 'model already bound');
        bound = true;
        try {
          adapter.validateServer(remote);
          implementation = remote;
          gate.ready();
          return adapter.proxyClient(gate.wire);
        } catch (error) { cleanup(); throw error; }
      };
    },
    close: cleanup,
  };
}
/** Checks and interprets a wire as the same model factory; the resulting session binds once. */
export async function fromWire(wire: Endpoint, context: AdapterContext): Promise<Protocol.ClientModel> {
  const preparation = prepareFromWire(wire, context);
  try { return await preparation.complete(); } catch (error) { preparation.close(); throw error; }
}
import { record as recordWire, type WireLog, type RecordOptions, type RecordedWire } from '@nightseam/duplex';
import { checkIdentity } from "@nightseam/runtime";
/** The closed union of this side's outgoing native event payloads. */
export type RecordedEvent = never;
export interface Recorder extends RecordedWire { append(event: RecordedEvent, context?: WireModelContext): Promise<void>; }
/** Checks a prepared origin before typed append; failed setup leaves its carrier usable. */
export async function record(target: Endpoint, log: WireLog, options: RecordOptions, context: AdapterContext, setup?: WireCallOptions): Promise<Recorder> {
  const adapter = makeAdapter(context);
  const preparation = prepareIdentity(target, adapter.identity, adapter.options);
  try {
    await preparation.check(setup); preparation.ready();
    const wire = await recordWire(preparation.wire, log, { ...options, onClose(error) { preparation.close(); options.onClose?.(error); } }, setup?.signal);
    const events = adapter.proxyServer(wire).events;
    return {
      ...wire,
      async append(event, context) {
        throw new Error('This side declares no outgoing events.');
      },
      async follow(after, subscriber, signal) {
        await checkIdentity((method, params, options) => callWire(subscriber, [method], params, { ...options, observer: adapter.options.observer, propagator: adapter.options.propagator }), adapter.identity, { signal, timeoutMs: adapter.options.requestTimeoutMs });
        return wire.follow(after, subscriber, signal);
      },
    };
  } catch (error) { preparation.close(); throw error; }
}
export const errors = { denied: "denied" } as const;
export type ErrorCode = (typeof errors)[keyof typeof errors];
