// Code generated by nightseam. DO NOT EDIT.
import { createValidator, type AnyFamily, type FamilyBinding, type TypeBinding, type Slots, type TypeExpression, type WireFamily } from "@nightseam/runtime";
export type { AnyFamily, FamilyBinding, TypeBinding, Slots, TypeExpression };
import type { LiveOwner } from "@nightseam/live";
import { DuplexError } from "@nightseam/runtime";
/** One message of the nightseam.duplex/1 profile: the members the peer acts on, and nothing else. */
export interface Envelope {
  /** The profile's version, 1. */
  "version": number;
  /** request, response, event or cancel. */
  "kind": string;
  /** What correlates a response or a cancel with its request. */
  "id"?: string;
  /** The method a request names. */
  "method"?: string;
  /** A request's parameters. */
  "params"?: unknown;
  /** A response's result. */
  "result"?: unknown;
  /** A response's error. */
  "error"?: unknown;
  /** The event an event frame names. */
  "event"?: string;
  /** An event's data. */
  "data"?: unknown;
  /** The W3C Trace Context of the frame. */
  "traceparent"?: string;
  /** The vendor state of that trace. */
  "tracestate"?: string;
  /** What a request or an event carries about the call, delivered to the handler beside the payload. */
  "meta"?: Record<string, string>;
}
/** A reference to a channel on the connection that carries the message holding it. */
export interface Handle {
  /** The channel's id on that connection. */
  "channel": number;
}
/** Told about a payload the server saw. The client implements it and hands it over; the server calls it back across the seam. */
/** A value of it is one implementation, called across the seam; each is its own binding, with its own lifetime. */
export type Notice = (request: Payload, options?: { signal?: AbortSignal; owner?: LiveOwner }) => Promise<void>;
/** What a probe carries: some text, and how often it has been seen. */
export interface Payload {
  /** The text of the payload. */
  "text": string;
  /** How often the payload has been seen. */
  "count": number;
}
/** Asks the server to stop sending notices. Releasing the reference to it is not this, and cancelling the call that returned it is neither. */
/** A value of it is one implementation, called across the seam; each is its own binding, with its own lifetime. */
export type Stop = (options?: { signal?: AbortSignal; owner?: LiveOwner }) => Promise<void>;
/** What watch answers: a record of callables the client calls back, held apart from the call that returned it. */
export interface Subscription {
  /** Ends the subscription. */
  "stop": Stop;
}
/** A callable supplied as an argument, beside ordinary data. */
export interface Watch {
  /** What to call this subscription; data, and carried as data. */
  "label": string;
  /** The interface the server calls back. */
  "watcher": Watcher;
}
/** An interface, which is a record of callable members; each member is its own binding, with its own lifetime. */
export interface Watcher {
  /** Called once for every payload the server sees while the subscription lasts. */
  "notice": Notice;
}
/** The family: its name and the wire types a slot of it draws on. */
export interface Family { readonly name: "probe"; Envelope: Envelope; Handle: Handle; Notice: Notice; Payload: Payload; Stop: Stop; Subscription: Subscription; Watch: Watch; Watcher: Watcher }
/** The declaration a reference to Notice carries. It is nominal: a reference is usable exactly where this callable is expected. */
export const contractNotice = "probe/Notice";
/** Makes a binding of a local Notice and answers the reference that names it. */
export function exportNotice(owner: LiveOwner, value: Notice): unknown {
  return owner.exportValue((owner) => {
    const parent = owner;
    const reference = owner.export(contractNotice, async (request, options) => {
      const owner = parent.child();
      const context = { ...options, owner };
      validateWire("Payload", request);
      const argument = request as Payload;
      await value(argument, context);
      return undefined;
    });
    return reference.toJSON();
  });
}
/** A Notice that calls the binding a reference names. */
export function importNotice(owner: LiveOwner, raw: unknown): Notice {
  const invoke = owner.import(owner.scope.decode(raw), contractNotice);
  const scope = owner.scope;
  return async (request: Payload, options?: { signal?: AbortSignal; owner?: LiveOwner }) => {
    const owner = options?.owner ?? scope.owner();
    if (owner.scope !== scope) throw new DuplexError('reference_foreign', 'the owner belongs to another connection');
    const sent = owner.exportValue((owner) => { const converted = request; validateWire("Payload", converted); return converted; });
    await invoke(sent, options);
    return;
  };
}
/** The declaration a reference to Stop carries. It is nominal: a reference is usable exactly where this callable is expected. */
export const contractStop = "probe/Stop";
/** Makes a binding of a local Stop and answers the reference that names it. */
export function exportStop(owner: LiveOwner, value: Stop): unknown {
  return owner.exportValue((owner) => {
    const parent = owner;
    const reference = owner.export(contractStop, async (request, options) => {
      const owner = parent.child();
      const context = { ...options, owner };
      await value(context);
      return undefined;
    });
    return reference.toJSON();
  });
}
/** A Stop that calls the binding a reference names. */
export function importStop(owner: LiveOwner, raw: unknown): Stop {
  const invoke = owner.import(owner.scope.decode(raw), contractStop);
  const scope = owner.scope;
  return async (options?: { signal?: AbortSignal; owner?: LiveOwner }) => {
    const owner = options?.owner ?? scope.owner();
    if (owner.scope !== scope) throw new DuplexError('reference_foreign', 'the owner belongs to another connection');
    await invoke(undefined, options);
    return;
  };
}
/** Writes Subscription as it travels: each callable in it becomes a binding of the owner, and the reference that names it takes its place. */
export function exportSubscription(owner: LiveOwner, value: Subscription): unknown {
  return owner.exportValue((owner) => {
    const out: Record<string, unknown> = {};
    out["stop"] = exportStop(owner, (value["stop"]) as Stop);
    return out;
  });
}
/** Reads Subscription as it arrived: each reference in it becomes a typed proxy of the binding it names, so a handler is given native values. */
export function importSubscription(owner: LiveOwner, raw: unknown): Subscription {
  return owner.importValue((owner) => {
    const wire = raw as Record<string, unknown>;
    const out: Record<string, unknown> = {};
    out["stop"] = importStop(owner, wire["stop"]);
    return out as unknown as Subscription;
  });
}
/** Writes Watch as it travels: each callable in it becomes a binding of the owner, and the reference that names it takes its place. */
export function exportWatch(owner: LiveOwner, value: Watch): unknown {
  return owner.exportValue((owner) => {
    const out: Record<string, unknown> = {};
    out["label"] = value["label"];
    out["watcher"] = exportWatcher(owner, (value["watcher"]) as Watcher);
    return out;
  });
}
/** Reads Watch as it arrived: each reference in it becomes a typed proxy of the binding it names, so a handler is given native values. */
export function importWatch(owner: LiveOwner, raw: unknown): Watch {
  return owner.importValue((owner) => {
    const wire = raw as Record<string, unknown>;
    const out: Record<string, unknown> = {};
    out["label"] = wire["label"];
    out["watcher"] = importWatcher(owner, wire["watcher"]);
    return out as unknown as Watch;
  });
}
/** Writes Watcher as it travels: each callable in it becomes a binding of the owner, and the reference that names it takes its place. */
export function exportWatcher(owner: LiveOwner, value: Watcher): unknown {
  return owner.exportValue((owner) => {
    const out: Record<string, unknown> = {};
    out["notice"] = exportNotice(owner, (value["notice"]) as Notice);
    return out;
  });
}
/** Reads Watcher as it arrived: each reference in it becomes a typed proxy of the binding it names, so a handler is given native values. */
export function importWatcher(owner: LiveOwner, raw: unknown): Watcher {
  return owner.importValue((owner) => {
    const wire = raw as Record<string, unknown>;
    const out: Record<string, unknown> = {};
    out["notice"] = importNotice(owner, wire["notice"]);
    return out as unknown as Watcher;
  });
}

const contractTypes = {"types":{"Envelope":{"kind":"record","fields":[{"name":"version","type":"integer","required":true},{"name":"kind","type":"string","required":true},{"name":"id","type":"string","required":false},{"name":"method","type":"string","required":false},{"name":"params","type":"json","required":false},{"name":"result","type":"json","required":false},{"name":"error","type":"json","required":false},{"name":"event","type":"string","required":false},{"name":"data","type":"json","required":false},{"name":"traceparent","type":"string","required":false},{"name":"tracestate","type":"string","required":false},{"name":"meta","type":{"map":"string"},"required":false}]},"Handle":{"kind":"record","fields":[{"name":"channel","type":"integer","required":true}]},"Notice":{"kind":"callable","contract":"probe/Notice","request":"Payload"},"Payload":{"kind":"record","fields":[{"name":"text","type":"string","required":true},{"name":"count","type":"integer","required":true}]},"Stop":{"kind":"callable","contract":"probe/Stop"},"Subscription":{"kind":"record","fields":[{"name":"stop","type":"Stop","required":true}]},"Watch":{"kind":"record","fields":[{"name":"label","type":"string","required":true},{"name":"watcher","type":"Watcher","required":true}]},"Watcher":{"kind":"record","fields":[{"name":"notice","type":"Notice","required":true}]}}} as unknown as WireFamily;
/** Runtime validation applies equally to calls, replies, reverse calls and events; what fills a slot of a parameter is validated by the binding of the family that fills it. */
export const validateWire = createValidator(contractTypes, {  });
/** This family bound: its name and its validator, to fill a family slot in another family's client. */
export const family = { name: "probe", validate: validateWire } as const;
