// Code generated by nightseam. DO NOT EDIT.
import { createValidator, type AnyFamily, type FamilyBinding, type Slots, type TypeExpression, type WireType } from "@nightseam/runtime";
export type { AnyFamily, FamilyBinding, Slots, TypeExpression };
import type * as probe from "@example/probe-client";
import { validateWire as validate_probe } from "@example/probe-client";
export interface AttachParams {
  "id": string;
}
/** A channel that speaks S, and the last sequence it saw. */
export interface Attachment<S extends AnyFamily = SessionFamily> {
  "connection": S["Handle"];
  "last": number;
}
/** One message of the nightseam.duplex/1 profile: the members the peer acts on, and nothing else. */
export interface Envelope {
  /** The profile's version, 1. */
  "version": number;
  /** request, response, event or cancel. */
  "kind": string;
  /** What correlates a response or a cancel with its request. */
  "id"?: string;
  /** The method a request names. */
  "method"?: string;
  /** A request's parameters. */
  "params"?: unknown;
  /** A response's result. */
  "result"?: unknown;
  /** A response's error. */
  "error"?: unknown;
  /** The event an event frame names. */
  "event"?: string;
  /** An event's data. */
  "data"?: unknown;
  /** The W3C Trace Context of the frame. */
  "traceparent"?: string;
  /** The vendor state of that trace. */
  "tracestate"?: string;
  /** What a request or an event carries about the call, delivered to the handler beside the payload. */
  "meta"?: Record<string, string>;
}
/** One message of S with its place in the sequence. */
export interface Frame<S extends AnyFamily = SessionFamily> {
  "sequence": number;
  "message": S["Envelope"];
}
export type Frames<S extends AnyFamily = SessionFamily> = Array<Frame<S>>;
/** A reference to a channel on the connection that carries the message holding it. */
export interface Handle {
  /** The channel's id on that connection. */
  "channel": number;
}
/** The family: its name and the wire types a slot of it draws on. */
export interface Family { readonly name: "carrier"; AttachParams: AttachParams; Envelope: Envelope; Handle: Handle }
/** The session role: every family of the world that has a session tier. */
export type SessionFamily = probe.Family;

const contractTypes = {"AttachParams":{"kind":"record","fields":[{"name":"id","type":"string","required":true}]},"Attachment":{"kind":"record","fields":[{"name":"connection","type":"S.Handle","required":true},{"name":"last","type":"integer","required":true}]},"Envelope":{"kind":"record","fields":[{"name":"version","type":"integer","required":true},{"name":"kind","type":"string","required":true},{"name":"id","type":"string","required":false},{"name":"method","type":"string","required":false},{"name":"params","type":"json","required":false},{"name":"result","type":"json","required":false},{"name":"error","type":"json","required":false},{"name":"event","type":"string","required":false},{"name":"data","type":"json","required":false},{"name":"traceparent","type":"string","required":false},{"name":"tracestate","type":"string","required":false},{"name":"meta","type":{"map":"string"},"required":false}]},"Frame":{"kind":"record","fields":[{"name":"sequence","type":"integer","required":true},{"name":"message","type":"S.Envelope","required":true}]},"Frames":{"kind":"alias","type":{"array":"Frame"}},"Handle":{"kind":"record","fields":[{"name":"channel","type":"integer","required":true}]}} as unknown as Record<string, WireType>;
/** Runtime validation applies equally to calls, replies, reverse calls and events; what fills a slot of a parameter is validated by the binding of the family that fills it. */
export const validateWire = createValidator(contractTypes, { "probe": validate_probe });
/** This family bound: its name and its validator, to fill a slot of the session role in another family's client. */
export const family = { name: "carrier", validate: validateWire } as const;
