// Code generated by nightseam. DO NOT EDIT.
import { DuplexPeer, DuplexError, type PeerOptions, type CallOptions, type EmitOptions, type RequestContext, type EventContext, type FrameConnection } from "@nightseam/runtime";
import type { Tunnel } from "@nightseam/tunnel";
import { validateWire } from './types.ts';
import type { AnyFamily, FamilyBinding, TypeBinding, Slots } from './types.ts';
import type * as Protocol from './types.ts';
export * from './types.ts';
export { DuplexError };
/** Typed event handlers installed before the client reads its first frame. Omitted fields leave events unhandled. */
export interface Events<S extends AnyFamily = AnyFamily> {
}
export interface Handler<S extends AnyFamily = AnyFamily> {
}
export interface Caller<S extends AnyFamily = AnyFamily> {
  relay(params: Protocol.Carried<S>, options?: CallOptions): Promise<S["Envelope"]>;
}
export class Client<S extends AnyFamily = AnyFamily> implements Caller<S> {
  readonly peer: DuplexPeer;
  /** The argument bound to S validates values in its declaration scope. */
  readonly s: FamilyBinding<S>;
  readonly slots: Slots;
  constructor(peer: DuplexPeer, s: FamilyBinding<S>, handler: Handler<S> | undefined, events: Events<S>) {
    this.peer = peer;
    this.s = s;
    this.slots = { "S": s };
  }
  /** Connects to a WebSocket endpoint and speaks the family over it. */
  static async dial<S extends AnyFamily = AnyFamily>(url: string, s: FamilyBinding<S>, options: PeerOptions, handler: Handler<S> | undefined, events: Events<S>): Promise<Client<S>> { const peer = new DuplexPeer({ ...options, families: { ...options.families, "relay": "relay" } }); const client = new Client<S>(peer, s, handler, events); await peer.connect(url); return client; }
  /** Speaks the family over a connection of the seam — a tunnel channel, a pipe, an open socket — as the client side of it. */
  static async attach<S extends AnyFamily = AnyFamily>(connection: FrameConnection, s: FamilyBinding<S>, options: PeerOptions, handler: Handler<S> | undefined, events: Events<S>): Promise<Client<S>> { const peer = new DuplexPeer({ ...options, families: { ...options.families, "relay": "relay" } }); const client = new Client<S>(peer, s, handler, events); await peer.attach(connection); return client; }
  /** Resolves a handle to the channel it names on a tunnel and speaks the family over it. */
  static async open<S extends AnyFamily = AnyFamily>(tunnel: Tunnel, handle: Protocol.Handle, s: FamilyBinding<S>, options: PeerOptions, handler: Handler<S> | undefined, events: Events<S>): Promise<Client<S>> { const channel = tunnel.channel(handle.channel); if (!channel) throw new Error('no channel ' + handle.channel + ' on the connection'); return Client.attach<S>(channel, s, options, handler, events); }
  close(): void { this.peer.close(); }
  /** Relays one message of the bound family. */
  async relay(params: Protocol.Carried<S>, options?: CallOptions): Promise<S["Envelope"]> { validateWire("Carried", params, '$', this.slots); const result = await this.peer.call<S["Envelope"]>("relay", params, options); validateWire("S.Envelope", result, '$', this.slots); return result; }
}
