// Code generated by nightseam. DO NOT EDIT.
import { createValidator, withDeclaration, jsonAdapter, familyTypeAdapter, callableIdentity, DuplexError, type DeclarationIdentity, type AnyFamily, type FamilyBinding, type TypeBinding, type Slots, type TypeExpression, type WireFamily } from "@nightseam/runtime";
export type { AnyFamily, FamilyBinding, TypeBinding, Slots, TypeExpression };
import type { ValueAdapter, ValueContext } from "@nightseam/runtime";
import type { WireModelContext } from "@nightseam/runtime";
/** A message of the bound family, held as data. The parameter says the family has a live tier; what is drawn through it is data, which is why relaying one needs no live runtime of its own. */
export interface Carried<S extends AnyFamily = AnyFamily> {
  "message": S["Envelope"];
  "back": S["Handle"] | null;
}
/** One message of the nightseam.duplex/1 profile: the members the peer acts on, and nothing else. */
export interface Envelope {
  /** The profile's version, 1. */
  "version": number;
  /** request, response, event or cancel. */
  "kind": string;
  /** What correlates a response or a cancel with its request. */
  "id"?: string;
  /** The method a request names. */
  "method"?: string;
  /** A request's parameters. */
  "params"?: unknown;
  /** A response's result. */
  "result"?: unknown;
  /** A response's error. */
  "error"?: unknown;
  /** The event an event frame names. */
  "event"?: string;
  /** An event's data. */
  "data"?: unknown;
  /** The W3C Trace Context of the frame. */
  "traceparent"?: string;
  /** The vendor state of that trace. */
  "tracestate"?: string;
  /** What a request or an event carries about the call, delivered to the handler beside the payload. */
  "meta"?: Record<string, string>;
}
/** A reference to a channel on the connection that carries the message holding it. */
export interface Handle {
  /** The channel's id on that connection. */
  "channel": number;
}
/** The family: its name and the wire types a slot of it draws on. */
export interface Family { readonly name: "relay"; Envelope: Envelope; Handle: Handle }
/** Conversion only: use the value adapter or validate the entire wire value inside the same operation batch. */
/** Writes Carried using the supplied conversion for each type argument. */
export function exportCarriedUnchecked<S extends AnyFamily = AnyFamily>(value: Carried<S>, convert_S_Envelope: (value: S["Envelope"]) => unknown, convert_S_Handle: (value: S["Handle"]) => unknown): unknown {
  const out: Record<string, unknown> = {};
  out["message"] = convert_S_Envelope((value["message"]) as S["Envelope"]);
  out["back"] = (value["back"] === null ? null : convert_S_Handle((value["back"]) as S["Handle"]));
  return out;
}
/** Reads Carried using the supplied conversion for each type argument. */
/** Conversion only: validation belongs to the value adapter or its caller. */
export function importCarriedUnchecked<S extends AnyFamily = AnyFamily>(raw: unknown, convert_S_Envelope: (value: unknown) => S["Envelope"], convert_S_Handle: (value: unknown) => S["Handle"]): Carried<S> {
  const wire = raw as Record<string, unknown>;
  const out: Record<string, unknown> = {};
  out["message"] = convert_S_Envelope(wire["message"]);
  out["back"] = (wire["back"] === null ? null : convert_S_Handle(wire["back"]));
  return out as unknown as Carried<S>;
}
export function adapterCarried<S extends AnyFamily = AnyFamily>(slot_S: FamilyBinding<S, "Envelope" | "Handle">): ValueAdapter<Carried<S>> {
  const type_S_Envelope = familyTypeAdapter(slot_S, "Envelope");
  const type_S_Handle = familyTypeAdapter(slot_S, "Handle");
  const slots: Slots = { "S": slot_S };
  const binding: TypeBinding = { type: "Carried", validate: validateWire, slots };
  const needsContext = type_S_Envelope.needsContext || type_S_Handle.needsContext;
  return { binding, needsContext,
    export(context: unknown, value: Carried<S>): unknown {
      if (needsContext && context === undefined) throw new DuplexError('scope_closed', 'conversion requires a value context');
      const convert = (owner: unknown): unknown => {
        const converted = exportCarriedUnchecked<S>(value, (value: S["Envelope"]) => type_S_Envelope.export(owner, value), (value: S["Handle"]) => type_S_Handle.export(owner, value));
        binding.validate(binding.type, converted, '$', slots);
        return converted;
      };
      return convert(context);
    },
    import(context: unknown, raw: unknown): Carried<S> {
      if (needsContext && context === undefined) throw new DuplexError('scope_closed', 'conversion requires a value context');
      binding.validate(binding.type, raw, '$', slots);
      const convert = (owner: unknown): Carried<S> => {
        const converted = importCarriedUnchecked<S>(raw, (value: unknown) => type_S_Envelope.import(owner, value), (value: unknown) => type_S_Handle.import(owner, value));
        return converted;
      };
      return convert(context);
    },
  };
}
export interface ServerMethods<S extends AnyFamily = AnyFamily> {
  relay(params: Carried<S>, context?: ValueContext<Carried<S> | S["Envelope"], WireModelContext>): S["Envelope"] | Promise<S["Envelope"]>;
}
export interface ServerEvents<S extends AnyFamily = AnyFamily> {
}
export interface Server<S extends AnyFamily = AnyFamily> { methods: ServerMethods<S>; events: ServerEvents<S>; }
export interface ClientMethods<S extends AnyFamily = AnyFamily> {
}
export interface ClientEvents<S extends AnyFamily = AnyFamily> {
}
export interface Client<S extends AnyFamily = AnyFamily> { methods: ClientMethods<S>; events: ClientEvents<S>; }
export type ServerModel<S extends AnyFamily = AnyFamily> = (remote: Client<S>) => Server<S>;
export type ClientModel<S extends AnyFamily = AnyFamily> = (remote: Server<S>) => Client<S>;

const contractTypes = {"types":{"Carried":{"kind":"record","fields":[{"name":"message","type":"S.Envelope","required":true},{"name":"back","type":{"nullable":"S.Handle"},"required":true}]},"Envelope":{"kind":"record","fields":[{"name":"version","type":"integer","required":true},{"name":"kind","type":"string","required":true},{"name":"id","type":"string","required":false},{"name":"method","type":"string","required":false},{"name":"params","type":"json","required":false},{"name":"result","type":"json","required":false},{"name":"error","type":"json","required":false},{"name":"event","type":"string","required":false},{"name":"data","type":"json","required":false},{"name":"traceparent","type":"string","required":false},{"name":"tracestate","type":"string","required":false},{"name":"meta","type":{"map":"string"},"required":false}]},"Handle":{"kind":"record","fields":[{"name":"channel","type":"integer","required":true}]}},"parameters":[{"name":"S","of":"live"}]} as unknown as WireFamily;
/** Canonical language-neutral declaration bytes, the input to wireDigest. */
export const wireDeclaration = "{\"definitions\":{\"relay\":{\"client\":{\"ref\":\"relay/$client\"},\"errors\":[],\"kind\":\"family\",\"parameters\":[{\"name\":\"S\",\"of\":\"live\"}],\"server\":{\"ref\":\"relay/$server\"},\"types\":{\"Carried\":{\"ref\":\"relay/Carried\"}}},\"relay/$client\":{\"direction\":\"client\",\"events\":{},\"extends\":[],\"kind\":\"side\",\"methods\":{},\"parameters\":[{\"name\":\"S\",\"of\":\"live\"}]},\"relay/$server\":{\"direction\":\"server\",\"events\":{},\"extends\":[],\"kind\":\"side\",\"methods\":{\"relay\":{\"errors\":[],\"request\":{\"ref\":\"relay/Carried\"},\"result\":{\"draw\":{\"parameter\":\"relay/S\"},\"name\":\"Envelope\"}}},\"parameters\":[{\"name\":\"S\",\"of\":\"live\"}]},\"relay/Carried\":{\"captures\":[{\"name\":\"S\",\"of\":\"live\"}],\"fields\":[{\"name\":\"message\",\"nullable\":false,\"required\":true,\"type\":{\"draw\":{\"parameter\":\"relay/S\"},\"name\":\"Envelope\"},\"unique\":false},{\"name\":\"back\",\"nullable\":false,\"required\":true,\"type\":{\"nullable\":{\"draw\":{\"parameter\":\"relay/S\"},\"name\":\"Handle\"}},\"unique\":false}],\"kind\":\"record\",\"open\":false,\"parameters\":[]}},\"root\":{\"ref\":\"relay\"},\"version\":1}";
/** SHA-256 of the canonical full declaration's exact UTF-8 bytes. */
export const wireDigest = "5b6ad4f2c0b7351d518c56998592cd3e16e33c2cfd179df69c80445143fbce84";
/** Runtime validation applies equally to calls, replies, reverse calls and events; what fills a slot of a parameter is validated by the binding of the family that fills it. */
export const validateWire = withDeclaration(createValidator(contractTypes, wireDigest, {  }), wireDeclaration);
/** This family's declaration and reusable interpretations, with no operation context or owner. */
export const family = { name: "relay", validate: validateWire, types: { "Envelope": jsonAdapter<Envelope>({ type: "Envelope", validate: validateWire }), "Handle": jsonAdapter<Handle>({ type: "Handle", validate: validateWire }) } } as const;
