// Code generated by nightseam. DO NOT EDIT.
import { createValidator, type AnyFamily, type FamilyBinding, type TypeBinding, type Slots, type TypeExpression, type WireFamily } from "@nightseam/runtime";
export type { AnyFamily, FamilyBinding, TypeBinding, Slots, TypeExpression };
import type * as worker from "@example/worker-client";
import { validateWire as validate_worker } from "@example/worker-client";
import { LiveScope, type Reference } from "@nightseam/live";
import * as live_worker from "@example/worker-client";
/** One message of the nightseam.duplex/1 profile: the members the peer acts on, and nothing else. */
export interface Envelope {
  /** The profile's version, 1. */
  "version": number;
  /** request, response, event or cancel. */
  "kind": string;
  /** What correlates a response or a cancel with its request. */
  "id"?: string;
  /** The method a request names. */
  "method"?: string;
  /** A request's parameters. */
  "params"?: unknown;
  /** A response's result. */
  "result"?: unknown;
  /** A response's error. */
  "error"?: unknown;
  /** The event an event frame names. */
  "event"?: string;
  /** An event's data. */
  "data"?: unknown;
  /** The W3C Trace Context of the frame. */
  "traceparent"?: string;
  /** The vendor state of that trace. */
  "tracestate"?: string;
  /** What a request or an event carries about the call, delivered to the handler beside the payload. */
  "meta"?: Record<string, string>;
}
/** A reference to a channel on the connection that carries the message holding it. */
export interface Handle {
  /** The channel's id on that connection. */
  "channel": number;
}
/** Self-contained data, declared where data belongs. */
export interface Shift {
  "name": string;
}
/** A live value drawn from an imported family: the callable is worker's declaration, and the reference carries worker's contract wherever it travels. */
export interface Watch {
  "shift": Shift;
  "sink": worker.ProgressSink;
  "spares"?: Array<worker.ProgressSink>;
}
/** The family: its name and the wire types a slot of it draws on. */
export interface Family { readonly name: "supervisor"; Envelope: Envelope; Handle: Handle; Shift: Shift; Watch: Watch }
/** Writes Watch as it travels: each callable in it becomes a binding of the scope, and the reference that names it takes its place. */
export function exportWatch(scope: LiveScope, value: Watch): unknown {
  const out: Record<string, unknown> = {};
  out["shift"] = value["shift"];
  out["sink"] = live_worker.exportProgressSink(scope, value["sink"] as worker.ProgressSink);
  if (value["spares"] !== undefined) out["spares"] = (value["spares"] as unknown[]).map((item) => live_worker.exportProgressSink(scope, item as worker.ProgressSink));
  return out;
}
/** Reads Watch as it arrived: each reference in it becomes a typed proxy of the binding it names, so a handler is given native values. */
export function importWatch(scope: LiveScope, raw: unknown): Watch {
  const wire = raw as Record<string, unknown>;
  const out: Record<string, unknown> = {};
  out["shift"] = wire["shift"];
  out["sink"] = live_worker.importProgressSink(scope, wire["sink"]);
  if (wire["spares"] !== undefined) out["spares"] = (wire["spares"] as unknown[]).map((item) => live_worker.importProgressSink(scope, item));
  return out as unknown as Watch;
}

const contractTypes = {"types":{"Envelope":{"kind":"record","fields":[{"name":"version","type":"integer","required":true},{"name":"kind","type":"string","required":true},{"name":"id","type":"string","required":false},{"name":"method","type":"string","required":false},{"name":"params","type":"json","required":false},{"name":"result","type":"json","required":false},{"name":"error","type":"json","required":false},{"name":"event","type":"string","required":false},{"name":"data","type":"json","required":false},{"name":"traceparent","type":"string","required":false},{"name":"tracestate","type":"string","required":false},{"name":"meta","type":{"map":"string"},"required":false}]},"Handle":{"kind":"record","fields":[{"name":"channel","type":"integer","required":true}]},"Shift":{"kind":"record","fields":[{"name":"name","type":"string","required":true}]},"Watch":{"kind":"record","fields":[{"name":"shift","type":"Shift","required":true},{"name":"sink","type":"worker.ProgressSink","required":true},{"name":"spares","type":{"array":"worker.ProgressSink"},"required":false}]}}} as unknown as WireFamily;
/** Runtime validation applies equally to calls, replies, reverse calls and events; what fills a slot of a parameter is validated by the binding of the family that fills it. */
export const validateWire = createValidator(contractTypes, { "worker": validate_worker });
/** This family bound: its name and its validator, to fill a slot of the session role in another family's client. */
export const family = { name: "supervisor", validate: validateWire } as const;
