// Package spec renders a family as its specification: one Markdown
// document per family, from every tier it declares — the types with their
// fields and constraints, the two sides with their operations and errors,
// the parameters it is generic in, the governance of a session of it —
// so that what a family means is written once, in the declaration, and
// the document is never behind it. It implements spi.Target and reserves
// nothing: it declares no identifier a family could collide with.
package spec

import (
	"encoding/json"
	"fmt"
	"path"
	"regexp"
	"sort"
	"strings"

	"github.com/Bitspark/nightseam/internal/diag"
	"github.com/Bitspark/nightseam/internal/emit"
	"github.com/Bitspark/nightseam/internal/model"
	"github.com/Bitspark/nightseam/internal/render"
	"github.com/Bitspark/nightseam/internal/spi"
)

// Config places the documents: Layout is where a family's document lives,
// as a pattern over the family's name; Place puts named families elsewhere.
type Config struct {
	Layout string
	Place  map[string]string
}

// DefaultLayout is api/spec/<family>, holding README.md.
const DefaultLayout = "api/spec/{family}"

// Name is the target's name.
const Name = "spec"

// File is the document's name within the family's directory.
const File = "README.md"

// New returns the spec target with its config.
func New(c Config) spi.Target {
	if c.Layout == "" {
		c.Layout = DefaultLayout
	}
	return &target{c}
}

type target struct{ config Config }

var pathPattern = regexp.MustCompile(`^[A-Za-z0-9_][A-Za-z0-9_./{}-]*$`)

// Validate reports what is wrong with the config.
func (c Config) Validate() error {
	patterns := []string{c.Layout}
	for _, placed := range c.Place {
		patterns = append(patterns, placed)
	}
	for _, pattern := range patterns {
		if !strings.Contains(pattern, "{family}") {
			return fmt.Errorf("a layout pattern names the family with {family}: %q", pattern)
		}
		dir := strings.ReplaceAll(pattern, "{family}", "x")
		if dir == "." || dir == ".." || strings.Contains(dir, "\\") || strings.Contains(dir, ":") || strings.HasPrefix(dir, "/") || path.Clean(dir) != dir || strings.HasPrefix(dir, "../") || !pathPattern.MatchString(dir) {
			return fmt.Errorf("invalid output path pattern %q", pattern)
		}
	}
	return nil
}

func (c Config) dir(family string) string {
	if placed, ok := c.Place[family]; ok {
		return strings.ReplaceAll(placed, "{family}", family)
	}
	return strings.ReplaceAll(c.Layout, "{family}", family)
}

func (*target) Name() string { return Name }

// Consumes is every concern: a specification documents all of them.
func (*target) Consumes() []spi.Concern { return []spi.Concern{spi.Model, spi.Protocol, spi.Session} }

func (t *target) Owns(family string) []string { return []string{t.config.dir(family)} }

func (t *target) Roots() []string {
	seen := map[string]bool{spi.PatternRoot(t.config.Layout): true}
	roots := []string{spi.PatternRoot(t.config.Layout)}
	for _, placed := range t.config.Place {
		if root := spi.PatternRoot(placed); !seen[root] {
			seen[root] = true
			roots = append(roots, root)
		}
	}
	sort.Strings(roots)
	return roots
}

func (t *target) Family(p string) (string, bool) {
	for family, placed := range t.config.Place {
		if matched, ok := spi.MatchPattern(placed, p); ok && matched == family {
			return family, true
		}
	}
	if family, ok := spi.MatchPattern(t.config.Layout, p); ok {
		if _, placed := t.config.Place[family]; !placed {
			return family, true
		}
	}
	return "", false
}

// Check holds the output layout to its rules. The specification describes
// every settled form the neutral checks accept.
func (t *target) Check(f *render.Family) []diag.Diagnostic {
	if err := t.config.Validate(); err != nil {
		return []diag.Diagnostic{{Family: f.Name, Code: "invalid_config", Message: err.Error()}}
	}
	return nil
}

// Reserved is what the target reserves: nothing.
func Reserved() []string { return nil }

// Render emits the family's document.
func (t *target) Render(f *render.Family) ([]spi.File, error) {
	if err := t.config.Validate(); err != nil {
		return nil, err
	}
	w := emit.NewWriter("")
	d := &doc{f: f, w: w}
	d.render()
	return []spi.File{{Path: path.Join(t.config.dir(f.Name), File), Data: []byte(w.String())}}, nil
}

type doc struct {
	f *render.Family
	w *emit.Writer
}

func (d *doc) line(text string)                 { d.w.Line(text) }
func (d *doc) linef(format string, args ...any) { d.w.Linef(format, args...) }

func (d *doc) render() {
	f := d.f
	d.linef("# %s", f.Name)
	d.line("")
	d.line("<!-- Generated by nightseam from " + d.source() + "; do not edit. -->")
	d.line("")
	d.linef("A family of the `nightseam.duplex/1` profile, declared in %s.", d.tiers())
	if len(f.References) > 0 {
		d.linef("It imports %s.", d.families(f.References))
	}
	if len(f.Carries) > 0 {
		d.linef("The tiers it declares bring the built-in %s, imported implicitly.", d.list(f.Carries, "family", "families"))
	}
	if len(f.Parameters) > 0 {
		d.line("")
		d.line("## Parameters")
		d.line("")
		d.line("The family is instantiated by filling these parameters:")
		d.line("")
		for _, p := range f.Parameters {
			var drawn []string
			for _, use := range p.Uses {
				drawn = append(drawn, "`"+use.Type+"`")
			}
			d.parameter(p.Name, p.Of, p.Description, drawn)
		}
	}
	d.types()
	if f.HasProtocol() {
		d.side("Server", "The server implements these methods and emits these events.", f.Server)
		d.side("Client", "The client implements these methods, which the server calls, and emits these events.", f.Client)
		if len(f.Errors) > 0 {
			d.line("")
			d.line("## Errors")
			d.line("")
			d.line("The public errors of the family, by code: what a call may fail with.")
			d.line("")
			d.line("| Code | Description |")
			d.line("|---|---|")
			for _, e := range f.Errors {
				d.linef("| `%s` | %s |", e.Code, cell(e.Description))
			}
		}
	}
	if s := f.Session; s != nil {
		d.line("")
		d.line("## Session")
		d.line("")
		d.line("How a session of the family is governed.")
		d.line("")
		for _, inherited := range s.Inherited {
			d.linef("Governance inherited from the %s side of `%s`.", inherited.Side, inherited.Family)
		}
		if len(s.Inherited) > 0 {
			d.line("")
		}
		d.linef("- **Decides**: %s — the methods that need control to send.", codes(s.Decides))
		d.linef("- **Asks**: %s — the methods the server sends that raise a request the holder of control must answer.", codes(s.Asks))
		if s.Conversation != nil {
			d.linef("- **Conversation**: the id arrives in the `%s` event, at `%s` of its data.", s.Conversation.Event, s.Conversation.Path)
		}
	}
}

func (d *doc) source() string {
	if d.f.Source != "" {
		return strings.TrimSuffix(d.f.Source, "/") + "/"
	}
	return "api/contracts/" + d.f.Name + "/"
}

func (d *doc) parameter(name, of, description string, drawn []string) {
	meaning := "a type"
	if of != "" {
		meaning = "a family with the `" + of + "` tier"
		if len(drawn) > 0 {
			meaning += ", drawn at " + strings.Join(drawn, ", ")
		}
	}
	d.linef("- **%s**: %s.%s", name, meaning, suffix(description))
}

func (d *doc) tiers() string {
	var names []string
	for _, file := range d.f.Files {
		if source := d.source(); source != "api/contracts/"+d.f.Name+"/" {
			file = source + file
		}
		names = append(names, "`"+file+"`")
	}
	return strings.Join(names, ", ")
}

// list names a set of families as prose: one family, or several joined.
func (d *doc) list(names []string, one, many string) string {
	word := many
	if len(names) == 1 {
		word = one
	}
	if len(names) < 2 {
		return word + " " + d.families(names)
	}
	quoted := make([]string, len(names))
	for i, name := range names {
		quoted[i] = "`" + name + "`"
	}
	return word + " " + strings.Join(quoted[:len(quoted)-1], ", ") + " and " + quoted[len(quoted)-1]
}

func (d *doc) families(names []string) string {
	var out []string
	for _, name := range names {
		out = append(out, "`"+name+"`")
	}
	return strings.Join(out, ", ")
}

func (d *doc) types() {
	f := d.f
	var own, carried []*render.Type
	for _, t := range f.Types {
		if t.Carried {
			carried = append(carried, t)
		} else {
			own = append(own, t)
		}
	}
	if len(own) > 0 {
		d.line("")
		d.line("## Types")
		d.declarations(own)
	}
	if len(carried) > 0 {
		d.line("")
		d.line("## Carried types")
		d.line("")
		d.linef("These are this family's own types, declared in the same language by a built-in family Nightseam declares of itself and imported by the tier that brings it, with no `imports` line. A declaration of this family may not declare one and names it by the built-in that declares it — `%s.%s`.", carried[0].From, carried[0].Name)
		d.declarations(carried)
	}
}

func (d *doc) declarations(types []*render.Type) {
	for _, t := range types {
		d.line("")
		d.linef("### %s", t.Name)
		d.line("")
		what := t.Kind
		if t.Kind == "entity" {
			what = "entity, identified by `" + t.Key + "`"
		}
		if t.Open {
			what += ", open: fields beyond the declared ones are kept"
		}
		if len(t.Uses) > 0 {
			var names []string
			for _, use := range t.Uses {
				name := use.Parameter
				if use.Type != "" {
					name += "." + use.Type
				}
				names = append(names, code(name))
			}
			what += ", generic in " + strings.Join(names, ", ")
		}
		if t.Carried {
			what += ", carried from the built-in `" + t.From + "` family"
		}
		d.linef("%s %s.%s", article(what), what, suffix(t.Description))
		if t.Inline {
			d.line("")
			d.line("Declared inline; its name is derived from its declaration path.")
		}
		if len(t.Extends) > 0 {
			d.line("")
			d.linef("Extends %s.", codes(t.Extends))
		}
		if len(t.Parameters) > 0 {
			d.line("")
			d.line("#### Parameters")
			d.line("")
			for _, parameter := range t.Parameters {
				var drawn []string
				for _, use := range t.Uses {
					if use.Parameter == parameter.Name {
						drawn = append(drawn, "`"+use.Type+"`")
					}
				}
				d.parameter(parameter.Name, parameter.Of, parameter.Description, drawn)
			}
		}
		switch t.Kind {
		case "record", "entity":
			if len(t.Fields) == 0 {
				continue
			}
			d.line("")
			d.line("| Field | Type | Presence | Constraints | Description |")
			d.line("|---|---|---|---|---|")
			for _, field := range t.Fields {
				presence := "required"
				if !field.Required {
					presence = "optional"
				}
				if field.Nullable {
					presence += ", nullable"
				}
				description := field.Description
				if field.Owner != t.Name {
					description = strings.TrimSpace("inherited from `" + field.Owner + "`. " + description)
				}
				d.linef("| `%s` | %s | %s | %s | %s |", field.Name, cell(d.spell(field.Type, field.Origin.Family, t.Scope)), presence, constraints(field), cell(description))
			}
		case "enum":
			var values []string
			for _, value := range t.Values {
				values = append(values, "`"+value+"`")
			}
			d.line("")
			d.linef("One of %s.", strings.Join(values, ", "))
		case "alias":
			d.line("")
			d.linef("An alias of %s.", d.spell(t.Alias, t.Origin.Family, t.Scope))
		case "union":
			d.line("")
			d.linef("The `%s` member identifies the variant. A non-object payload is carried in `%s` beside the tag; an object payload contributes its members directly. A record declaring the tag itself carries the matching literal.", t.Tag, t.Value)
			d.line("")
			d.line("| Tag | Payload | Declared by |")
			d.line("|---|---|---|")
			for _, variant := range t.Variants {
				tag, _ := json.Marshal(variant.Tag)
				d.linef("| %s | %s | %s |", cell(code(string(tag))), cell(d.spell(variant.Type, variant.Origin.Family, t.Scope)), code(d.qualified(variant.Origin.Family, variant.Origin.Declaration)))
			}
		}
	}
}

func (d *doc) side(name, intro string, side render.Side) {
	if len(side.Methods) == 0 && len(side.Events) == 0 && len(side.Extends) == 0 {
		return
	}
	d.line("")
	d.linef("## %s side", name)
	d.line("")
	d.line(intro)
	if len(side.Extends) > 0 {
		d.line("")
		d.linef("Extends the %s side of %s.", strings.ToLower(name), d.families(side.Extends))
	}
	if len(side.Methods) > 0 {
		d.line("")
		d.line("| Method | Request | Result | Errors | Description |")
		d.line("|---|---|---|---|---|")
		for _, m := range side.Methods {
			requestType, resultType := m.Request, m.Result
			if m.Declaration != nil {
				requestType, resultType = m.Declaration.Request, m.Declaration.Result
			}
			request := "—"
			if requestType != nil {
				request = d.spell(requestType, m.Origin.Family, nil)
			}
			d.linef("| `%s` | %s | %s | %s | %s |", m.Name, cell(request), cell(d.spell(resultType, m.Origin.Family, nil)), codes(m.Errors), cell(d.inherited(m.Description, m.Origin.Family)))
		}
	}
	if len(side.Events) > 0 {
		d.line("")
		d.line("| Event | Data | Description |")
		d.line("|---|---|---|")
		for _, e := range side.Events {
			data := e.Type
			if e.Declaration != nil {
				data = e.Declaration.Type
			}
			d.linef("| `%s` | %s | %s |", e.Name, cell(d.spell(data, e.Origin.Family, nil)), cell(d.inherited(e.Description, e.Origin.Family)))
		}
	}
}

func (d *doc) inherited(description, family string) string {
	if family != "" && family != d.f.Name {
		return strings.TrimSpace("Inherited from `" + family + "`. " + description)
	}
	return description
}

func (d *doc) qualified(family, name string) string {
	if family != "" && family != d.f.Name {
		return family + "." + name
	}
	return name
}

// spell writes a type expression as the document reads it.
func (d *doc) spell(e model.TypeExpr, owner string, scope []model.Parameter) string {
	switch x := e.(type) {
	case model.Primitive:
		return "`" + string(x) + "`"
	case model.Named:
		for _, parameter := range scope {
			if parameter.Name == x.Name {
				return code(x.Name)
			}
		}
		return code(d.qualified(owner, x.Name))
	case model.Imported:
		return code(d.qualified(x.Family, x.Name))
	case model.Drawn:
		return "`" + x.Parameter + "." + x.Name + "`"
	case model.Array:
		return "array of " + d.spell(x.Elem, owner, scope)
	case model.Map:
		return "map of " + d.spell(x.Elem, owner, scope)
	case model.Nullable:
		return "nullable " + d.spell(x.Elem, owner, scope)
	case model.Literal:
		value, _ := json.Marshal(x.Value)
		return "the literal " + code(string(value))
	case model.Ref:
		return "reference to " + code(d.qualified(owner, x.Entity))
	case model.Inline:
		if declaration := d.f.InlineType(x); declaration != nil {
			return code(d.qualified(declaration.Origin.Family, declaration.Name))
		}
	case model.Apply:
		var with []string
		for _, parameter := range sortedKeys(x.With) {
			filler := x.With[parameter]
			value := filler.Family
			if value == "" {
				value = d.spell(filler.Type, owner, scope)
			}
			with = append(with, parameter+"="+value)
		}
		family := x.Family
		if family == "" {
			family = owner
		}
		return code(d.qualified(family, x.Name)) + " with " + strings.Join(with, ", ")
	}
	return "`" + model.String(e) + "`"
}

// code uses a delimiter longer than any backtick run in a literal, so its
// Markdown representation preserves the string rather than ending early.
func code(value string) string {
	delimiter := "`"
	for strings.Contains(value, delimiter) {
		delimiter += "`"
	}
	return delimiter + value + delimiter
}

// article is the indefinite article a word takes.
func article(word string) string {
	if strings.HasPrefix(word, "union") {
		return "A"
	}
	if strings.ContainsRune("aeiou", rune(word[0])) {
		return "An"
	}
	return "A"
}

// constraints lists a field's constraints, or nothing.
func constraints(field render.Field) string {
	var out []string
	if field.Unique {
		out = append(out, "unique")
	}
	if field.Min != nil {
		out = append(out, "min "+field.Min.String())
	}
	if field.Max != nil {
		out = append(out, "max "+field.Max.String())
	}
	if field.Length != nil {
		if field.Length.Min != nil {
			out = append(out, fmt.Sprintf("length ≥ %d", *field.Length.Min))
		}
		if field.Length.Max != nil {
			out = append(out, fmt.Sprintf("length ≤ %d", *field.Length.Max))
		}
	}
	if field.Pattern != "" {
		out = append(out, "matches `"+field.Pattern+"`")
	}
	if len(out) == 0 {
		return "—"
	}
	return cell(strings.Join(out, ", "))
}

func codes(names []string) string {
	if len(names) == 0 {
		return "—"
	}
	var out []string
	for _, name := range names {
		out = append(out, "`"+name+"`")
	}
	return strings.Join(out, ", ")
}

// cell makes text safe in a table cell.
func cell(text string) string {
	return strings.ReplaceAll(strings.ReplaceAll(strings.TrimSpace(text), "|", "\\|"), "\n", " ")
}

// suffix appends a description as a second sentence, or nothing.
func suffix(description string) string {
	if strings.TrimSpace(description) == "" {
		return ""
	}
	return " " + strings.TrimSpace(description)
}

func sortedKeys(m map[string]model.Filler) []string {
	keys := make([]string, 0, len(m))
	for key := range m {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}
